### ISSUE TITLE
FAQ and Troubleshooting guide

### ISSUE THREAD

**Issue by aravindavk** [kadalu/kadalu#100]
Prepare a Troubleshooting guide for Kadalu.

- When a storage pod is down, how will mounts behave?
- One storage pod/node is down in Replica3 volume
- PV is created, but my application pod is not coming up
- PVC status is still showing "Pending"
- Understanding all Log files
- I added storage, but not showing when I run `kubectl get pods -n kadalu`
- How to remove the storage?

**Comment by aravindavk** [comment]
@amarts @sac @fs-system Please add more failure scenarios.

**Comment by amarts** [comment]
:+1: 

Good to get started with these. We can open different issues, as we encounter the need in future!

**Comment by amarts** [comment]
#117 is a good start, but we need to further keep that document updated with all the observations.

**Comment by aravindavk** [comment]
Recording feedback from @sac here

My storage is not getting created
1. Check if the node name is right (it has to be other than master)
2. Check if the given path exists.
3. Check if there is any typo in path (Same as 2).
Otherwise things look good.
I'll test the disk based setup tomorrow or so.

**Comment by aravindavk** [comment]
Include this topic https://github.com/kadalu/kadalu/issues/165

**Comment by aravindavk** [comment]
ongoing. Not all the known cases updated.
