### ISSUE TITLE
[Bug]: PersistentVolumes get deleted when their relative PersistentVolumeClaims are deleted due to StorageClass reclaim policy ignoring the `--pv-reclaim-policy` value.

### ISSUE THREAD

**Issue by mariamatthews** [kadalu/kadalu#1016]
**Describe the bug**
When creating a new `KadaluStorage` with `--pv-reclaim-policy=retain` or `--pv-reclaim-policy retain`:

```bash
kubectl kadalu storage-add cluster-storage --type Replica3 --device ubuntu22-node-0:/dev/sdb --device ubuntu22-node-1:/dev/sdb --device ubuntu22-node-2:/dev/sdb --pv-reclaim-policy=retain
```
the new `StorageClass` that gets created has the `ReclaimPolicy` of `Delete`:
```bash
kubectl get sc
NAME                     PROVISIONER   RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
kadalu.cluster-storage   kadalu        Delete          Immediate           true                   7m35s
```
Which then applies to both `PersistentVolumeClaim`'s and `PersistentVolume`'s:
```bash
kubectl get pvc
NAME          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS             AGE
demo-pvc   Bound    pvc-c9c20ed7-b129-42f3-a7d6-3f8fc0f4e2c8   8Gi        RWX            kadalu.cluster-storage   5m50s
```
```bash
kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                 STORAGECLASS             REASON   AGE
pvc-c9c20ed7-b129-42f3-a7d6-3f8fc0f4e2c8   8Gi        RWX            Delete           Bound    default/demo-pvc   kadalu.cluster-storage            5m50s
```

Because of the above, when the `PersistentVolumeClaim` using the above `StorageClass` gets deleted, the `PersistentVolume` is deleted as well, loosing all the data.

**To Reproduce**
1. Create new kadalu storage:
`kubectl kadalu storage-add cluster-storage --type Replica3 --device ubuntu22-node-0:/dev/sdb --device ubuntu22-node-1:/dev/sdb --device ubuntu22-node-2:/dev/sdb --pv-reclaim-policy=retain`
2. Create new `PersistentVolumeClaim`:
```bash
# create yml file
nano demo-pvc.yml

# use following yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
spec:
  storageClassName: kadalu.cluster-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

# apply pvc
kubectl apply demo-pvc.yml
```

3. Create a pod that utilises the pvc
```bash
# create yml file
nano demo-alpine.yml

# use following yml
apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - mountPath: "/mnt/kadalu"
      name: kadalu-storage
  volumes:
  - name: kadalu-storage
    persistentVolumeClaim:
      claimName: demo-pvc

# apply pod
kubectl apply -f demo-alpine.yml

# exec into pod and create new file under /mnt/kadalu/
kubectl exec -it alpine-pod -- /bin/sh
touch /mnt/kadalu/testfile
```

4. Delete the pvc:
```bash
kubectl delete -f  demo-pvc.yml
```

5. Notice that your `PersistentVolume` with any data added via the `alpine` container is also deleted:
```bash
kubectl get pv
No resources found
```

**Expected behavior**
When creating new `KadaluStorage` and using `--pv-reclaim-policy=retain` flag, the `StorageClass` ReclaimPolicy should be set to `Retain`.

**Actual behavior**
When creating new `KadaluStorage` and using `--pv-reclaim-policy=retain` flag, the `StorageClass` ReclaimPolicy is still being set to `Delete`.

**Environment:**

- kubectl-kadalu plugin: 1.1.0
- kadalu pod(s) versions
- pod/operator-67b67665cf-p2hzc: 1.1.0
- pod/kadalu-csi-nodeplugin-ghqlk: 1.1.0
- pod/kadalu-csi-nodeplugin-9qw6v: 1.1.0
- pod/kadalu-csi-nodeplugin-q62r6: 1.1.0
- pod/kadalu-csi-provisioner-0: 1.1.0
- pod/server-cluster-storage-0-0: 1.1.0
- pod/server-cluster-storage-1-0: 1.1.0
- pod/server-cluster-storage-2-0: 1.1.0

**Comment by leelavg** [comment]
>Expected behavior
When creating new KadaluStorage and using --pv-reclaim-policy=retain flag, the StorageClass ReclaimPolicy should be set to Retain.
- I believe the feature is misunderstood, I don't blame you though 😄 , thanks for raising the issue as this calls for an improvement in the docs
- Assume you have two actors, one is kubernetes storage class (hereafter just sc) another is kadalustorage cr (hereafter just cr)
- The reclaim policy you mentioned in the cr doesn't get carried into sc that kadalu creates by default
- the policy in cr serves different purpose than the policy in sc, let me explain with two usecases

**Usecase 1:** When a PVC is deleted, unless cluster is deleted you want PV to be retained
**Solution:** Copy the sc that kadalu creates for a specific cr onto a new sc and set the parameter `reclaimPolicy: Retain`, this prohibits removal of cr unless you delete the retained PV(C)s.

**Usecase 2:** When a PVC is deleted, even when cluster is deleted you want PV to be retained
**Solution:** You set `--pv-reclaim-policy=retain` on cr and this doesn't prohibit cr removal and data is still retained in backend bricks. This provides you an option for recovery

- I believe you are trying to achieve **_Usecase 1_** by using **_Solution of Usecase 2_** which isn't intentionally allowed

**Comment by mariamatthews** [comment]
Hello!

Thanks for your feedback and for taking a look! :)

So, if I understand correctly - even if the `PersistentVolume` is deleted on the Kubernetes layer, you are saying that the actual volume does stay on the `KadaluStorage` layer ( would the files be found on, let's say `server-cluster-storage-0-0` pod? ).

After the initial deletion of the `PVC`, I tried recreating it again and hoped that if the above were true, the new `PV` would contain the data from the previous volume, but it has simply created a new `PV`.

On the contrary, allowing the `StorageClass` to be set to `Retain` does make the recovery of the files more generic ( as the old `PV` stays and can be reattached to another pod ), but I understand Kudalu does not support it.

Let me know what you think 👍

**Comment by leelavg** [comment]
> would the files be found on, let's say server-cluster-storage-0-0 pod?
- yep, to be exact, they are retained on the backend bricks, for `retain` on cr, it'll just be a no-op from kadalu perspective for delete volume rpc https://github.com/kadalu/kadalu/blob/devel/csi/volumeutils.py#L638-L645

> I tried recreating it again and hoped that if the above were true, the new PV would contain the data from the previous volume, but it has simply created a new PV.
- nope, it doesn't work that way, you might want to use the PV via static provisioning but not through PVC, my knowledge on this area reduced a bit, need to recheck

> but I understand Kudalu does not support it.
- no, it's a kubernetes feature, every storage class supports it, as mentioned above, recreate a new sc from kadalu created default sc and then use `reclaimPolicy: Retain` in this new sc
- it's just that kadalu doesn't provide you an option to mention `reclaimPolicy: Retain` on default sc's, think about it, it's not at all related to storage layer
- when that param is set, k8s just doesn't send delete volume rpc

**Comment by leelavg** [comment]
> need to recheck
- I think this is one https://github.com/kadalu/kadalu/issues/765 when I last looked into this area

**Comment by mariamatthews** [comment]
Hi!

Thanks that makes sense, it clarified a lot. I can see now why this is not a bug.

Would you say adding a potential ability to set the `reclaimPolicy: Retain` on the default sc could be considered a feature upgrade instead?

**Comment by leelavg** [comment]
Probably not because of below:
1. These two are separate concerns with a clear owner, i.e, kadalu vs kubernetes, so don't want to club
2. Adding a separate option in cr might work but we have to take more decisions unecessarily
3. Creating a new sc is one time task which doesn't warrant reconciliation

Basically I can see the appeal, at the same time, don't want to introduce yet another option for a standalone feature, pls excuse.

**Comment by mariamatthews** [comment]
I agree, 100% valid points. Thank you for your engagement on the matter! ❤️ The bug can be closed :)
