### ISSUE TITLE
[Bug]: kadalu-operator.storage missing, how to add performance options

### ISSUE THREAD

**Issue by OlivierMary** [kadalu/kadalu#1046]
**Describe the bug**
I installed kadulu with versions 1.1.0, I just upgraded to 1.2.0 by follofing steps in : [DOC](https://github.com/kadalu/kadalu/blob/ebe8797c10aff2dd35b114ee291986deb87b2cd9/doc/upgrade.adoc)

And I think I have some performance issues so I wanted to add some performance options to test with: [DOC](https://docs.kadalu.tech/k8s-storage/devel/storage-config-options/#_configuring_storage_pool_options)

And I have errors (see below)

I dont know if I have to create the `kadalu-operator.storage` resource manually to fix,

Actually the description of my storage is only in configmap (see below).

**Additionnal question:**
How to know on which node the csi driver plug a pod to a glustervolume node ? 
How to be sure pod on node1 is connected to a volume on node1 and not on node2/node3 or use "localhost" if available

**To Reproduce**
1. Install Kadulu 1.1.0
2. Create storage with `kubectl kadalu storage-add pool-1 --device node1:/dev/md4 --device node2:/dev/md4 --device node3:/dev/md4 --type Replica3 --pv-reclaim-policy Retain`
3. Upgrade to 1.2.0
4. add options ` k kadalu option-set gs-pool-1 performance.readdir-ahead on performance.io-cache on performance.read-ahead on performance.open-behind on performance.quick-read on performance.stat-prefetch on performance.client-io-threads on`

**Expected behavior**
option-set updated for storage 

**Actual behavior**
Get an error:

```
Failed to get CRD of storage "gs-pool-1"
error 1 Error from server (NotFound): kadalustorages.kadalu-operator.storage "gs-pool-1" not found
```

**Environment:**
```
 kubectl kadalu version
kubectl-kadalu plugin: 1.2.0
kadalu pod(s) versions
pod/kadalu-csi-nodeplugin-c8dfz: 1.2.0
pod/kadalu-csi-nodeplugin-wd4r6: 1.2.0
pod/kadalu-csi-nodeplugin-xzznq: 1.2.0
pod/kadalu-csi-provisioner-0: 1.2.0
pod/operator-54976f999c-8txnn: 1.2.0
pod/server-gs-pool-1-0-0: 1.2.0
pod/server-gs-pool-1-1-0: 1.2.0
pod/server-gs-pool-1-2-0: 1.2.0

```

**Screenshots or Logs**
N/A

**Additional context**

Storage class:

```
 k get storageclasses.storage.k8s.io -o yaml
apiVersion: v1
items:
- allowVolumeExpansion: true
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"kadalu.gs-pool-1"},"parameters":{"single_pv_per_pool":"False","storage_name":"gs-pool-1"},"provisioner":"kadalu"}
    creationTimestamp: "2023-12-08T10:23:13Z"
    name: kadalu.gs-pool-1
    resourceVersion: "2481066"
    uid: 3ef152e9-17f6-4efc-8ce1-f810ed19b93c
  parameters:
    single_pv_per_pool: "False"
    storage_name: gs-pool-1
  provisioner: kadalu
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
kind: List
metadata:
  resourceVersion: ""

```

configmap

```
k describe configmaps kadalu-info
Name:         kadalu-info
Namespace:    kadalu
Labels:       <none>
Annotations:  <none>

Data
====
gs-pool-1.info:
----
{"namespace": "kadalu", "kadalu_version": "1.1.0", "volname": "gs-pool-1", "volume_id": "cad3dd68-95b3-11ee-9021-42d316d1cd5d", "single_pv_per_pool": false, "type": "Replica3", "pvReclaimPolicy": "retain", "bricks": [{"brick_path": "/bricks/gs-pool-1/data/brick", "kube_hostname": "node1", "node": "server-gs-pool-1-0-0.gs-pool-1", "node_id": "node-0", "host_brick_path": "", "brick_device": "/dev/md4", "pvc_name": "", "brick_device_dir": "", "decommissioned": "", "brick_index": 0}, {"brick_path": "/bricks/gs-pool-1/data/brick", "kube_hostname": "node2", "node": "server-gs-pool-1-1-0.gs-pool-1", "node_id": "node-1", "host_brick_path": "", "brick_device": "/dev/md4", "pvc_name": "", "brick_device_dir": "", "decommissioned": "", "brick_index": 1}, {"brick_path": "/bricks/gs-pool-1/data/brick", "kube_hostname": "node3", "node": "server-gs-pool-1-2-0.gs-pool-1", "node_id": "node-2", "host_brick_path": "", "brick_device": "/dev/md4", "pvc_name": "", "brick_device_dir": "", "decommissioned": "", "brick_index": 2}], "disperse": {"data": 0, "redundancy": 0}, "options": {}}
uid:
----
60aa11ea-37ea-489f-9287-2b4da549a124
volumes:
----


BinaryData
====

Events:  <none>

```

No custom kadalustorages.kadalu-operator.storage

```
 k get kadalustorages.kadalu-operator.storage
No resources found in kadalu namespace.

```

Storage-List

```
k kadalu storage-list --detail
---
Name: gs-pool-1
ID  : cad3dd68-95b3-11ee-9021-42d316d1cd5d
Type: Replica3
Storage Unit 1:
  Kube hostname: node1
  Device: /dev/md4

Storage Unit 2:
  Kube hostname: node2
  Device: /dev/md4

Storage Unit 3:
  Kube hostname: node3
  Device: /dev/md4

Failed to get CRD of storage "None"
error 1 Error from server (NotFound): kadalustorages.kadalu-operator.storage "gs-pool-1" not found

```

**Comment by OlivierMary** [comment]
For the performances issues:

in the pod:
```
root@xxxxx:/var/www/html# dd if=/dev/zero of=./test1.img bs=1G count=1 oflag=dsync
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 50.7345 s, 21.2 MB/s
```

in the node in the `/mnt/xfs-drive-gluster/brick/subvol/` dir of the same volume:
```
 sudo dd if=/dev/zero of=./test1.img bs=1G count=1 oflag=dsync
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 1.78596 s, 601 MB/s

```

cant continue with this performances...

I can explain it cause all 3 nodes arent in same datacenter but csi must plug volume on the closest node (which is the same node cause storage volume is replicated in all node)

**Comment by leelavg** [comment]
there are multiple issues mentioned in this single thread and it's a bit confusing to focus on what to look at first, I'll try to answer in my capacity

> so I wanted to add some performance options to test with: [DOC](https://docs.kadalu.tech/k8s-storage/devel/storage-config-options/#_configuring_storage_pool_options)
- I don't think we are testing storage options set on the pool is working or not in CI https://github.com/kadalu/kadalu/blob/b39af6ed14ca3e026e79f0fd1db1f0f65e39f68f/tests/minikube.sh#L460-L461

> if I have to create the kadalu-operator.storage resource
- this is a CRD and deployment of operator should create it, if for any reason the CRD is deleted all the CRs will get deleted

> description of my storage is only in configmap
- this is an issue not sure how kds is deleted

> `kubectl kadalu storage-add pool-1; k kadalu option-set gs-pool-1`
- added the pool as `pool-1` and using as `gs-pool-1` I don't think that works

> name: kadalu.gs-pool-1
- I see the storageclass name as `gs-pool-1` and so I'm assuming the create command has a typo in the issue

> k kadalu storage-list --detail
- As mentioned the entries from configmap is parsed and failed to query kadalu storage as the CR is probably deleted

### Issue 1:
- Kadalu Storage CR is deleted `k get kds -A` returns empty
- This can only happen while operator is down the CRs were removed manually, couldn't help here

> but csi must plug volume on the closest node
- you should be deploying the workloads using the nodeAffinity for wherever storage nodes are deployed
- the other option is to have the CSIDriver topology aware which kadalu doesn't support, even then you user need to mention where the volume should be deployed

### Issue 2:
- Micro benchmark on the node where the gluster brick is vs in the mounted pod is very slow
- One, you shouldn't directly be writing to backend bricks and replication will not work
- You are using Replica3 and gluster is client heavy architecture, unless client writes the data to all 3 subvols the op isn't marked done
- Nonetheless, for a benchmark we should consider what's the performance of using gluster in k8s via kadalu vs gluster running standalone

**Comment by OlivierMary** [comment]
Hi,

> You are using Replica3 and gluster is client heavy architecture, unless client writes the data to all 3 subvols the op isn't marked done

we can't set up an asynchronous acknowledgement of changes?

> Nonetheless, for a benchmark we should consider what's the performance of using gluster in k8s via kadalu vs gluster running standalone

yes, I tried, it's same with other solutions... while ack is synchron no perfs... so apps slow...

**Comment by leelavg** [comment]
> we can't set up an asynchronous acknowledgement of changes?
- not possible, it's kinda set in stone architecture for gluster

> it's same with other solutions.
- you mean other CSI Solutions?

you can take a look at https://github.com/topolvm/topolvm project which uses LVM for storage and can provide better performance but you'll loose the distributed storage paradigm wherein a loss of node is regret of pod storage reachability

**Comment by OlivierMary** [comment]
will look that, I tried rook.io it's same perfs.

I have to test something with syncthing in k8s to replicate volumes on all nodes but not the same approach, and I also will lose the volume size limit.... but replications and perfs must be there.

I tried drbd but I didn't find any `free` way to enable volume master on node if pod in on node.

**Comment by OlivierMary** [comment]
I found this explaination on ceph : https://yourcmc.ru/wiki/Ceph_performance 

The image shows the reason for the performance on Ceph, I think it's in the same spirit on GlusterFS.

**Comment by leelavg** [comment]
Performance is a grey area and your requirements to achieve near disk level speeds w/ an sds solution isn't something I have come across often. I heard weka.io offers great performance however it's a paid product. I remember reading a paper in https://github.com/cubefs/cubefs which has some perf numbers readily available, take a look if interested.

As they say, it's a trade off and you should pick one based on your requirements and tolerance of your workloads.


> I tried drbd but I didn't find any free way to enable volume master on node if pod in on node.
- I didn't get this, you can use tolerations to schedule pod on control nodes if they are tainted and your disk is attached to those nodes

**Comment by OlivierMary** [comment]
> I didn't get this, you can use tolerations to schedule pod on control nodes if they are tainted and your disk is attached to those nodes

Yes, but if node down, service down :-1: 

After maybe I wanted to much things, Replication, High availability and Performance without cloud provider and Free :joy:
