### ISSUE TITLE
[Bug]: restart kadalu-csi-nodeplugin daemonset would make current gfs mount unavailable.

### ISSUE THREAD

**Issue by liyuntao** [kadalu/kadalu#1055]
We are using external glusterfs volume. After restart daemonset(or kadalu-csi-nodeplugin pod on specific node), business pod with glusterfs volume mounted cannot access mount point. 

To reproduce:
```bash
## 1. e.g. There's a business pod on node2, mount point is /nas
kubect exec -it  -n example business-pod-1 sh
> cd /nas
/nas #OK

## 2. Restart kadalu-csi-nodeplugin
kubectl -n kadalu rollout restart ds kadalu-csi-nodeplugin

## 3. Inside same pod. error occur, cannot auto-recover
kubect exec -it  -n example business-pod-1 sh
> cd /nas
sh: cd: can't cd to /nas: Socket not connected
```

```bash
## under business pod's namespace
> kubectl get events

68s         Warning   FailedMount         pod/front-v1-8f6c57cb8-pg8zs     MountVolume.SetUp failed for volume "dev-glusterfs-vol" : stat /var/lib/kubelet/pods/d41e083d-3c57-4eba-8d80-be193b8f0585/volumes/kubernetes.io~glusterfs/dev-glusterfs-vol: transport endpoint is not connected
```

**Comment by leelavg** [comment]
Yes, it is a knowm problem w/ fuse drivers implementing CSI. First, once the mount is established deamonset going down is rare, in extreme cases or user initiated restart we need to scale down & up business pod.

Another case when this is hit is during upgrades, closer solution exists but it's a bit invovled to implement it.

**Comment by liyuntao** [comment]
> Yes, it is a known problem w/ fuse drivers implementing CSI. First, once the mount is established deamonset going down is rare, in extreme cases or user initiated restart we need to scale down & up business pod.
> 
> Another case when this is hit is during upgrades, closer solution exists but it's a bit invovled to implement it.

Thanks a lot for the explanation. I've noticed [these](https://github.com/kubernetes/kubernetes/issues/70013) in the meantime. After a cursory look at Azure Blob CSI's complex solution, the most efficient way for our internal usage may be monitoring FailedMount events (mainly at the moment of daemonset upgrading).
