### ISSUE TITLE
Test: install operator from 0.4 version, and upgrade to latest (any release 0.5/0.6 etc)

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#106]
Ideally, the upgrade should be smooth, without loosing any information about previously created PVs, storage config etc. The process of upgrading the operator as of now is like below:

1. check if operator and other csi drivers are all running.
2. just do `kubectl apply -f new-operator-yaml-file`
3. see that all the new versions should be installed now.

Correct the steps, and document the steps if some other procedures are required for upgrade.

**Comment by aravindavk** [comment]
upgrade testing is needed.

**Comment by amarts** [comment]
no automated tests yet, but the feature is now available with `0.7.6`.
