### ISSUE TITLE
Enhancement: backup options for PVs

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#118]
Right now, no specific designs in place. We can consider multiple options:

1. Use Gluster's geo-replication.
2. Considering we use backend differently, use reflink, and transfer from the clone.
3. Use tools like https://backube.github.io/snapscheduler/ and backup natively in k8s way.
4. Shift to using ZFS / btrfs, and use their snapshots, and transfer data.
5. validate possibilities of xfs_dump to get incremental backup

Keeping the issue open for capturing attention of people passing through, and those who have suggestions. This is not in immediate Roadmap, but surely one thing we want to have if community/users are interested. Express what you think, and we can collaboratively get to a great solution :+1:

**Comment by amarts** [comment]
Still valid

**Comment by aravindavk** [comment]
Still valid

**Comment by KyleSanderson** [comment]
hi Team, thanks for keeping this one open. I am indeed looking at using this however I'm unable to specify redundancy using dispersed versus distributed. This is forcing me to use the External feature to get at this to dynamically provision storage, and then use the native driver to access my external server.

**Comment by aravindavk** [comment]
> hi Team, thanks for keeping this one open. I am indeed looking at using this however I'm unable to specify redundancy using dispersed versus distributed. This is forcing me to use the External feature to get at this to dynamically provision storage, and then use the native driver to access my external server.

Thanks. I opened new issue to support Disperse Volume type in Kadalu. https://github.com/kadalu/kadalu/issues/524

We will keep this open till we implement PV-to-PV backup solution.
