### ISSUE TITLE
Creation of `ReatWriteOnce` fails with `mounter.SetupAt failed: rpc error: code = Unknown desc = Exception calling application: [32] b`

### ISSUE THREAD

**Issue by papanito** [kadalu/kadalu#119]
Claiming volumes with `ReatWriteOnce` fails with

```
MountVolume.SetUp failed for volume "pvc-81e1f518-0249-41e8-b2d3-d9027e7c00bd" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = Exception calling application: [32] b'' b'mount: /var/lib/kubelet/pods/2611b8bf-ce6d-451a-adf8-f69d00cf0f1c/volumes/kubernetes.io~csi/pvc-81e1f518-0249-41e8-b2d3-d9027e7c00bd/mount: mount(2) system call failed: Transport endpoint is not connected.'
```

**Steps to reproduce**

Install `prometheus` using persistent volume claim when installing via helm chart

1. Create `values.yaml` defining persistence using `ReadWriteOnce`

   ```yaml
   ...
     persistentVolume:
       enabled: true
       accessModes:
         - ReadWriteOnce
   ...
   ```

1. Install helm chart

   ```bash
   helm install prometheus stable/prometheus -f prometheus.values.yml --namespace prometheus
   ```

**Expected Result**

No errors

**Actual Result** 

```bash
MountVolume.SetUp failed for volume "pvc-81e1f518-0249-41e8-b2d3-d9027e7c00bd" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = Exception calling application: [1] b'' b''
Unable to attach or mount volumes: unmounted volumes=[storage-volume], unattached volumes=[config-volume storage-volume prometheus-alertmanager-token-dhs7w]: timed out waiting for the condition
MountVolume.SetUp failed for volume "pvc-81e1f518-0249-41e8-b2d3-d9027e7c00bd" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = Exception calling application: [32] b'' b'mount: /var/lib/kubelet/pods/2611b8bf-ce6d-451a-adf8-f69d00cf0f1c/volumes/kubernetes.io~csi/pvc-81e1f518-0249-41e8-b2d3-d9027e7c00bd/mount: mount(2) system call failed: Transport endpoint is not connected.'
MountVolume.SetUp failed for volume "pvc-81e1f518-0249-41e8-b2d3-d9027e7c00bd" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = Exception calling application: [32] b'' b"mount: /var/lib/kubelet/pods/2611b8bf-ce6d-451a-adf8-f69d00cf0f1c/volumes/kubernetes.io~csi/pvc-81e1f518-0249-41e8-b2d3-d9027e7c00bd/mount: can't read superblock on /dev/loop0."
Unable to attach or mount volumes: unmounted volumes=[storage-volume], unattached volumes=[prometheus-alertmanager-token-dhs7w config-volume storage-volume]: timed out waiting for the condition
MountVolume.SetUp failed for volume "pvc-81e1f518-0249-41e8-b2d3-d9027e7c00bd" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = Exception calling application: [32] b'' b"mount: /var/lib/kubelet/pods/2611b8bf-ce6d-451a-adf8-f69d00cf0f1c/volumes/kubernetes.io~csi/pvc-81e1f518-0249-41e8-b2d3-d9027e7c00bd/mount: can't read superblock on /dev/loop1."
Unable to attach or mount volumes: unmounted volumes=[storage-volume], unattached volumes=[storage-volume prometheus-alertmanager-token-dhs7w config-volume]: timed out waiting for the condition
```

**Additional info**

Changing the access mode to `ReadWriteMany` works fine

```
# kubectl get pvc -n prometheus
NAME                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
prometheus-alertmanager   Bound    pvc-4309b9c4-22d7-434b-9f6b-8c4a9bace025   2Gi        RWX            kadalu.replica1   101m
prometheus-server         Bound    pvc-042277ec-abee-4e6b-a5e7-5d13f7959f07   8Gi        RWX            kadalu.replica1   101m
# kubectl get events -n prometheus
LAST SEEN   TYPE      REASON                   OBJECT                                   MESSAGE
<unknown>   Normal    Scheduled                pod/prometheus-server-76b7cf695-5qls6    Successfully assigned prometheus/prometheus-server-76b7cf695-5qls6 to node001
21m         Normal    SuccessfulAttachVolume   pod/prometheus-server-76b7cf695-5qls6    AttachVolume.Attach succeeded for volume "pvc-042277ec-abee-4e6b-a5e7-5d13f7959f07"
21m         Normal    Pulling                  pod/prometheus-server-76b7cf695-5qls6    Pulling image "jimmidyson/configmap-reload:v0.2.2"
21m         Normal    Pulled                   pod/prometheus-server-76b7cf695-5qls6    Successfully pulled image "jimmidyson/configmap-reload:v0.2.2"
21m         Normal    Created                  pod/prometheus-server-76b7cf695-5qls6    Created container prometheus-server-configmap-reload
21m         Normal    Started                  pod/prometheus-server-76b7cf695-5qls6    Started container prometheus-server-configmap-reload
21m         Normal    Pulling                  pod/prometheus-server-76b7cf695-5qls6    Pulling image "prom/prometheus:v2.13.1"
21m         Normal    Pulled                   pod/prometheus-server-76b7cf695-5qls6    Successfully pulled image "prom/prometheus:v2.13.1"
20m         Normal    Created                  pod/prometheus-server-76b7cf695-5qls6    Created container prometheus-server
20m         Normal    Started                  pod/prometheus-server-76b7cf695-5qls6    Started container prometheus-server
```

**Comment by amarts** [comment]
Is this consistent with RWO PVC ? Because I too had an issue with RWO when I tried, but noticed thats because of failing to mount the hostvolume, so, the file was not accessible on app pods.

When this happens, would need log of `csi-nodeplugin-*****` (in kadalu namespace), go with `--all-containers` option for logs. There were no issues in data path of RWO pv.

**Comment by papanito** [comment]
Here you go. I've deleted the installation (`helm delete`) and the reinstalled it with `ReadWriteOnce`.
[cis-nodeplugin.log](https://github.com/kadalu/kadalu/files/4053734/cis-nodeplugin.log)

**Comment by papanito** [comment]
RWO seems the same issue [cis-nodeplugin.log](https://github.com/kadalu/kadalu/files/4053768/cis-nodeplugin.log)

**Comment by papanito** [comment]
Here the log of `storage-pool-pod`: [storage-pool.log](https://github.com/kadalu/kadalu/files/4053931/storage-pool.log)

**Comment by amarts** [comment]
Interesting. The issue here seems to be related to disconnects happening when fd_cleanup happens. Still need to debug (as the same issue is not happening for me yet). Looks like we need to handle #75 for this same reason. At present this is a glusterfs disconnect between client and server.

**Comment by papanito** [comment]
Is there a way I can debug it or maybe give you more details? 
And why does `RWX` work and the others not?

**Comment by amarts** [comment]
I am suspecting the issue to be similar to https://lists.gluster.org/pipermail/gluster-users/2020-January/037557.html (in case of RWO). I recommend to use `direct-io-mode=disable` for mount point. This should help in applications which would need DB like access.

**Comment by papanito** [comment]
Still had not the chance to test `replica3`. Path requires `xfs` as underlying fs to simulate 3 nodes but I have `ext4`

**Comment by amarts** [comment]
If you could make a path to export, I recommend creating a file `truncate -s Ng $path/disk-image` and use that as `device: $path/disk-image` in the storage config file. Again, this is good only for testing.

Ref: https://github.com/kadalu/kadalu/blob/master/tests/minikube.sh#L153..L154

**Comment by papanito** [comment]
I've completely removed `kadalu` by running the `cleanup.sh` script and the used `replica3`. Here the logs trying a `replica3`. I'm actually using 3 nodes
[csi-nodeplugin-m8phv.log](https://github.com/kadalu/kadalu/files/4117040/csi-nodeplugin-m8phv.log)
[csi-provisioner-0.log](https://github.com/kadalu/kadalu/files/4117041/csi-provisioner-0.log)
[kadalu.events.log](https://github.com/kadalu/kadalu/files/4117042/kadalu.events.log)
[server-storage-pool-main-0-node001-0.log](https://github.com/kadalu/kadalu/files/4117043/server-storage-pool-main-0-node001-0.log)
[server-storage-pool-main-1-node002-0.log](https://github.com/kadalu/kadalu/files/4117044/server-storage-pool-main-1-node002-0.log)
[server-storage-pool-main-2-node003-0.log](https://github.com/kadalu/kadalu/files/4117048/server-storage-pool-main-2-node003-0.log)
[csi-nodeplugin-qmgzg.log](https://github.com/kadalu/kadalu/files/4117074/csi-nodeplugin-qmgzg.log)
[csi-nodeplugin-w6dfz.log](https://github.com/kadalu/kadalu/files/4117075/csi-nodeplugin-w6dfz.log)

The error is at the moment different, I assume cause the cleanup was not properly

```
E0127 12:14:01.463808       1 controller.go:700] error syncing claim "prometheus/prometheus-server": failed to provision volume with StorageClass "kadalu.replica3": rpc error: code = Unknown desc = Exception calling application: [1] b'' b'mkfs.xfs: /mnt/storage-pool-main/virtblock/b6/ce/pvc-d95bf5f5-2629-43ba-ba37-0ae57778b4f6 appears to contain an existing filesystem (xfs).\nmkfs.xfs: Use the -f option to force overwrite.'
I0127 12:14:01.463802       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"prometheus", Name:"prometheus-server", UID:"d95bf5f5-2629-43ba-ba37-0ae57778b4f6", APIVersion:"v1", ResourceVersion:"5363801", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "kadalu.replica3": rpc error: code = Unknown desc = Exception calling application: [1] b'' b'mkfs.xfs: /mnt/storage-pool-main/virtblock/b6/ce/pvc-d95bf5f5-2629-43ba-ba37-0ae57778b4f6 appears to contain an existing filesystem (xfs).\nmkfs.xfs: Use the -f option to force overwrite.'
```

**Comment by papanito** [comment]
[server-storage-pool-main-2-node003-0.log](https://github.com/kadalu/kadalu/files/4117047/server-storage-pool-main-2-node003-0.log)

**Comment by papanito** [comment]
@amarts will this be fixed?

**Comment by amarts** [comment]
@papanito we made changes in the image os, and with that the tool versions used for xfs etc.

Please see if `0.7.6` is any better for you. We will close this issue for now, as we have not seen the particular issue in long time now. If it exists with 0.7.6 please feel free to reopen. Thanks for patience :pray:
