### ISSUE TITLE
Automate the release of Python packages

### ISSUE THREAD

**Issue by aravindavk** [kadalu/kadalu#144]
Kadalu provides two Python packages which can be downloaded from Pypi website.

- kubectl-kadalu - Kubectl extension
- kadalu-quotad - To use Kadalu with External Gluster storage

Setup Github actions to publish these packages to Pypi

Ref: https://github.com/hyperledger/ursa-python/blob/master/.github/workflows/pythonpublish.yml

**Comment by amarts** [comment]
Fixed with #191 & #194
