### ISSUE TITLE
build for multiple architectures

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#164]
Currently kadalu is built only for linux/amd64 (x86_64), would be great if linux/arm64 can be provided as an option.

**Comment by egonbraun** [comment]
I have the same problem guys, is there an alternative for kadalu for ARM?

**Comment by amarts** [comment]
If you have arm system doing below should get you an image:

Checkout the repo:

`KADALU_VERSION=test_arm make prepare-release`! 

Let us know if this works.

**Comment by aravindavk** [comment]
This is now available in the latest version.
