### ISSUE TITLE
timeout logs seen in CSI/controller

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#178]
```
W0210 17:30:08.637771       1 controller.go:592] CreateVolume timeout: 15s has expired, operation will be retried
```

The above logs are commonly seen in controller. We need to increase the timeout to 120 seconds for kadalu.

**Comment by aravindavk** [comment]
I see the connection timeout increased to `3m`(https://github.com/kadalu/kadalu/pull/181). Closing this issue. Please reopen if this is still an issue
