### ISSUE TITLE
Pending pvc

### ISSUE THREAD

**Issue by bartpaczkows** [kadalu/kadalu#183]
Hi,
I was trying to follow the instruction but I'm stuck on step PVC creation - it's in pending stage.
Log file from PVC "kubectl describe pvc pv1":
"Events:
  Type     Reason                Age                     From                                                           Message
  ----     ------                ----                    ----                                                           -------
  Normal   Provisioning          8m37s (x13 over 123m)   kadalu_csi-provisioner-0_86eccce2-53d9-11ea-9da0-7a48491a4632  External provisioner is provisioning volume for claim "default/pv1"
  Warning  ProvisioningFailed    8m37s (x12 over 123m)   kadalu_csi-provisioner-0_86eccce2-53d9-11ea-9da0-7a48491a4632  failed to provision volume with StorageClass "kadalu.replica1": rpc error: code = Unknown desc = Exception calling application: [1] b'' b''
  Normal   ExternalProvisioning  3m39s (x482 over 123m)  persistentvolume-controller                                    waiting for a volume to be created, either by external provisioner "kadalu" or manually created by system administrator"

I have a Kuberentes cluster which consists of 2 nodes:
k8s-master   Ready    master   134m   v1.17.3
node-1       Ready    <none>   132m   v1.17.3
node-2       Ready    <none>   130m   v1.17.3

I created storage using the following command:
"kubectl kadalu storage-add storage-pool-1 --device node-1:/dev/vcs"

Do you have any clue what is wrong?

**Comment by amarts** [comment]
Hi @bartpaczkows. 

Is `/dev/vcs` available in your node `node-1` ? 

You need to attach an available device from nodes in your kube cluster (which you can get through `kubectl get nodes`)

In any case, can you check the output of `kubectl get pods -nkadalu` and `kubectl logs operator-* -nkadalu` where * part can be picked up from previous command.

**Comment by bartpaczkows** [comment]
Hi @amarts ,
/dev/vcs is available on node-1, see the output of the commands below


vagrant@k8s-master:~$ kubectl get nodes
NAME         STATUS   ROLES    AGE   VERSION
k8s-master   Ready    master   18h   v1.17.3
node-1       Ready    <none>   17h   v1.17.3
node-2       Ready    <none>   17h   v1.17.3



vagrant@node-1:/dev$ ll | grep vcs
crw-rw----  1 root    tty       7,   0 Feb 20 15:27 vcs
crw-rw----  1 root    tty       7,   1 Feb 20 15:27 vcs1
crw-rw----  1 root    tty       7,   2 Feb 20 15:27 vcs2
crw-rw----  1 root    tty       7,   3 Feb 20 15:27 vcs3
crw-rw----  1 root    tty       7,   4 Feb 20 15:27 vcs4
crw-rw----  1 root    tty       7,   5 Feb 20 15:27 vcs5
crw-rw----  1 root    tty       7,   6 Feb 20 15:27 vcs6
crw-rw----  1 root    tty       7, 128 Feb 20 15:27 vcsa
crw-rw----  1 root    tty       7, 129 Feb 20 15:27 vcsa1
crw-rw----  1 root    tty       7, 130 Feb 20 15:27 vcsa2
crw-rw----  1 root    tty       7, 131 Feb 20 15:27 vcsa3
crw-rw----  1 root    tty       7, 132 Feb 20 15:27 vcsa4
crw-rw----  1 root    tty       7, 133 Feb 20 15:27 vcsa5
crw-rw----  1 root    tty       7, 134 Feb 20 15:27 vcsa6

**Comment by bartpaczkows** [comment]
Hi @amarts ,
Just one question to clarify - what do you mean exactly by attaching an available device from nodes in kube cluster. Is just a matter of creating storage with a definition file like in the example below

apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: storage-pool-1
spec:
  storage:
  - device: /dev/vcs
    node: node-1
  type: Replica1

Also in case of kubernetes cluster consisting of two nodes, do I have to also attached device from second node ("kubectl kadalu storage-add storage-pool1 --device node-1:/dev/vcs --device node-2:/dev/vcs") ?

**Comment by amarts** [comment]
Yes, attaching the 'device' is same as calling with a config file.

Right now, you can't add 2 storage devices to same config (ie, same name). You have to run that command separately for each storage addition. If it is 'Replica3' type, then you will need to give 3 devices.

**Comment by bartpaczkows** [comment]
Hi @amarts 
I did everything once again and still there is an issue with pending PersistentVolumeClaim.
Is there anything else that I can check to debug this?

See the log below:
Events:
  Type     Reason                Age                From                                                           Message
  ----     ------                ----               ----                                                           -------
  Warning  ProvisioningFailed    30s                kadalu_csi-provisioner-0_a0e7a372-549f-11ea-83eb-4695a5aca165  failed to provision volume with StorageClass "kadalu.replica1": rpc error: code = Unknown desc = Exception calling application: [Errno 107] Transport endpoint is not connected: '/mnt/storage-pool-1'
  Normal   Provisioning          15s (x2 over 30s)  kadalu_csi-provisioner-0_a0e7a372-549f-11ea-83eb-4695a5aca165  External provisioner is provisioning volume for claim "default/pv1"
  Warning  ProvisioningFailed    15s                kadalu_csi-provisioner-0_a0e7a372-549f-11ea-83eb-4695a5aca165  failed to provision volume with StorageClass "kadalu.replica1": rpc error: code = Unknown desc = Exception calling application: [1] b'' b''
  Normal   ExternalProvisioning  9s (x3 over 30s)   persistentvolume-controller                                    waiting for a volume to be created, either by external provisioner "kadalu" or manually created by system administrator


I created two storages:
kubectl kadalu storage-add storage-pool-1 --device node-1:/dev/vcs
"""
Storage Yaml file for your reference:
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: storage-pool-1
spec:
  storage:
  - device: /dev/vcs
    node: node-1
  type: Replica1
"""

kubectl kadalu storage-add storage-pool-2 --device node-2:/dev/vcs
"""
Storage Yaml file for your reference:
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: storage-pool-2
spec:
  storage:
  - device: /dev/vcs
    node: node-2
  type: Replica1
"""

vagrant@k8s-master:~$ kubectl get pods -nkadalu
NAME                               READY   STATUS    RESTARTS   AGE
csi-nodeplugin-2tgjd               3/3     Running   0          12m
csi-nodeplugin-lk526               3/3     Running   0          12m
csi-provisioner-0                  4/4     Running   0          12m
operator-68649f4bb6-j45fb          1/1     Running   0          13m
server-storage-pool-1-0-node-1-0   2/2     Running   0          11m
server-storage-pool-2-0-node-2-0   2/2     Running   0          9m


I attached output from "kubectl logs operator-68649f4bb6-j45fb -nkadalu" command
[kadalu_log.docx](https://github.com/kadalu/kadalu/files/4235916/kadalu_log.docx)

**Comment by amarts** [comment]
thanks for operator logs. I initially suspected if storage pods were not running. But the issue is in provisioner. Please check `kubectl logs csi-provisioner-0 -nkadalu --all-containers -n 4000 > csi-controller.logs` and check if there is something fishy.

**Comment by bartpaczkows** [comment]
HI @amarts ,
I set up my kubernetes cluster from scratch (based on Cubespray) and tried again, unfortunately with the sa
[csi-provisioner-log.zip](https://github.com/kadalu/kadalu/files/4249502/csi-provisioner-log.zip)
me results.
I attached the log file from "kubectl logs csi-provisioner-0 -nkadalu --all-containers" command

**Comment by amarts** [comment]
@bartpaczkows is there a firewall (`iptables` or `ufw`) setup? Because the error on gluster client log is all about connection 'refused'.

**Comment by amarts** [comment]
you need to open up port `24007` (all servers are running on port 24007 when you use kadalu).

**Comment by bartpaczkows** [comment]
firewall is disabled.

**Comment by zhucan** [comment]
This issue had been sloved？ @bartpaczkows

**Comment by deba10106** [comment]
It seems, this is a frequent incident. Is this solved?
 I followed all the instructions but couldn't fix!
