### ISSUE TITLE
Creation of volumes fails with: No Hosting Volumes available, add more storage

### ISSUE THREAD

**Issue by papanito** [kadalu/kadalu#184]
Creation of volumes fails with

```console
7m25s       Warning   ProvisioningFailed     persistentvolumeclaim/nextcloud-nextcloud                failed to provision volume with StorageClass "kadalu.replica3": rpc error: code = ResourceExhausted desc = No Hosting Volumes available, add more storage
2m50s       Normal    Provisioning           persistentvolumeclaim/nextcloud-nextcloud                External provisioner is provisioning volume for claim "nextcloud/nextcloud-nextcloud"
2m50s       Warning   ProvisioningFailed     persistentvolumeclaim/nextcloud-nextcloud                failed to provision volume with StorageClass "kadalu.replica3": rpc error: code = ResourceExhausted desc = No Hosting Volumes available, add more storage
30s         Normal    ExternalProvisioning   persistentvolumeclaim/nextcloud-nextcloud                waiting for a volume to be created, either by external provisioner "kadalu" or manually created by system administrator
```

```bash
$ kubectl exec -it <server-pod-name> /bin/bash -c glusterfsd -n kadalu
cat /bricks/<storage-pool-name>/data/
```
shows

```bash
[root@server-storage-pool-main-0-node001-0 /]# cat /bricks/storage-pool-main/data/brick/.stat
{"size": 1861574914048, "free_size": -1031085559808}
```
However, there are no volumes at all in place, all I have are 3 pending pvcs

```bash
$ kubectl get pvc --all-namespaces
NAMESPACE   NAME                              STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS      AGE
nextcloud   data-nextcloud-mariadb-master-0   Pending                                      kadalu.replica3   36h
nextcloud   data-nextcloud-mariadb-slave-0    Pending                                      kadalu.replica3   36h
nextcloud   nextcloud-nextcloud               Pending                                      kadalu.replica3   36h

$ kubectl get pv --all-namespaces
No resources found

```

** Version Info **

- kadalu: `0.5.0`
- kubernetes: `1.17.2`
- OS: `Debian 10`

**Comment by amarts** [comment]
Thanks! Looks like there are some issues in how we are calculating the storage usage!

Will fix. Looks like this is same concern from #167

**Comment by papanito** [comment]
Even so I do not have any volume, I can see in the brick that there are a lot of "subvols" which have data in it
```bash
ls /bricks/storage-pool-main/data/brick/subvol/
11  16  1c  21  3c  58  63  68  69  6f  85  d2  f5
```

```
[root@server-storage-pool-main-1-node002-0 brick]# df -h subvol/
Filesystem      Size  Used Avail Use% Mounted on
/dev/md3        1.8T  1.9G  1.8T   1% /bricks/storage-pool-main/data
```
Still it is nowhere full but if there are no volumes, should this not be empty anyway?

**Comment by amarts** [comment]
@papanito we had not completed 'DeleteVolume', mainly as we wanted to keep it as optional till we reach v1.0 (we had seen this request to get back data after too earlier). If there were PVs created, and deleted, and data is no more required, feel free to delete the directories in backend directly for now.

The whole issue seems to be with the mangled update of the data usage stats

**Comment by rajasaur** [comment]
I think this is similar to what I experienced. If there are issues when creating the Volume, the update to the data['free_size'] keeps happening in the `update_free_size` method but its not reverted back in case there is a failure. Since this seems to be reconciling till the PVC is available, it keeps reducing the free_size each time this method is run, even though the actual PVC creation still hangs.

**Comment by ncresswell** [comment]
I see this issue still remains in Kadalu 0.7?

I can create a volume just fine that is 5Gi, 10Gi, 15Gi, but if i increase the size any larger than 15Gi it gets stuck forever with: failed to provision volume with StorageClass "kadalu.replica1": rpc error: code = ResourceExhausted desc = No Hosting Volumes available, add more storage"

my underlying storage is 100GB, and there is nothing in it.
![image](https://user-images.githubusercontent.com/23178133/81730320-72a21a00-94e1-11ea-99f3-fc984ed64423.png)

![image](https://user-images.githubusercontent.com/23178133/81730362-83529000-94e1-11ea-9da0-c6d1cc837b44.png)

**Comment by aravindavk** [comment]
I am thinking about changing the format of the info file. Instead of storing the aggregated values store individual pv sizes in sqlite db(inside mount). For example,

```
CREATE TABLE stat(pvname varchar primary key, size integer);
```

On each change update using,

```
INSERT OR REPLACE INTO stat VALUES("pvc-8541ac59-9373-4363-8e93-756b1b38a8ae", 524288000);
INSERT OR REPLACE INTO stat VALUES("pvc-7afc3109-b171-4568-8877-3b612388ac08", 1073741824);
```

To get the total used size,

```
SELECT SUM(size) FROM stat;
```

On pv delete, remove the record from Db.

@amarts do you think any issue to use SqliteDb inside Gluster mount? (Thread lock is used so no concurrent access). Also, it is easy to rebuild in case it gets corrupted by crawling all the available pvs in that directory.

**Comment by rajasaur** [comment]
I think a way to recalculate the right storage(and stored either like it is now or in a DB) as a command will definitely be helpful in case of installations that errored. 
I can simulate my error case where if i produce a wrong SC, it keeps looping and updates the stat file without allocating actual storage. This goes on till the requested size isnt available in the node, even though it is actually available. Its the ".stat" file that stores the info that causes it to say that there is no volume available

**Comment by amarts** [comment]
> @amarts do you think any issue to use SqliteDb inside Gluster mount?

I feel thats totally fine. We are providing storage for Databases anyways! Yes, this is better for accounting, and as things gets randomly inserted and deleted, handling it with DB is better.

**Comment by slash1387** [comment]
> @papanito we had not completed 'DeleteVolume', mainly as we wanted to keep it as optional till we reach v1.0 (we had seen this request to get back data after too earlier). If there were PVs created, and deleted, and data is no more required, feel free to delete the directories in backend directly for now.
> 
> The whole issue seems to be with the mangled update of the data usage stats

We use external gluster storage and would love the feature of deleting backend data folders after wiping pvc and pv's from k8s. How do we know what subfolder of the gluster volume to delete since we only have one gluster volume in the external scenario?

**Comment by pantxisto** [comment]
Hello, 
I'm still having this problem when using "Replica3" type with three nodes. I have tried advises posted on [web page throubleshooting](https://kadalu.io/docs/k8s-storage/devel/troubleshooting/) but does not solve the problem. There exist any solution for this problem?

Thanks.

**Comment by SakaZhang** [comment]
> Hello, I'm still having this problem when using "Replica3" type with three nodes. I have tried advises posted on [web page throubleshooting](https://kadalu.io/docs/k8s-storage/devel/troubleshooting/) but does not solve the problem. There exist any solution for this problem?
> 
> Thanks.

Same. How u fixed it?
