### ISSUE TITLE
server-storage-pools pod fails to create if the hostname is long

### ISSUE THREAD

**Issue by rhinduja** [kadalu/kadalu#185]
Description:
---------------

In my test environment, I had long hostname like [1, 35 char] which after being appended by pod id [2, 10] and volume name [3, 24] exceeded the limit of 63 chars and failed to start. 

Kadalu should handle such scenario at the time of adding storage pool [during 4] either by "alternate unique name" or "by throwing user a warning at the time of adding storage pool that the name is too long and use IP instead"

[1]: rah-123456789-lab-testing-envmn-com
[2]: 58658c8597
[3]: server-storage-pool-1-0
[4]: kubectl kadalu storage-add storage-pool-1 --device rah-123456789.lab.testing.envmn.com:/root/storage.img

Failure: 

# kubectl describe statefulsets -n kadalu

Invalid value: "server-storage-pool-1-0-rah-123456789-lab-testing-envmn-com-58658c8597": must be no more than 63 characters

**Comment by sankarshanmukhopadhyay** [comment]
I'm not sure if we've seen this - non UTF-8 encoded name handling. If this is an issue, we'd need a seperate bug.

**Comment by amarts** [comment]
Looks like we are hitting this in tests with 'minikube' hostname changed :-) in #225

**Comment by aravindavk** [comment]
> Looks like we are hitting this in tests with 'minikube' hostname changed :-) in #225

Oh, then it is good to skip using node name in Pod name and use numeric index.
