### ISSUE TITLE
Add pre-validation checks for the devices that can be added to storage pool

### ISSUE THREAD

**Issue by rhinduja** [kadalu/kadalu#206]
[node 1]# kubectl kadalu storage-add storage-pool-3 --device temp:/root/storage1.img
Storage add request sent successfully
kadalustorage.kadalu-operator.storage/storage-pool-3 created
[node 1]#

[node 1]# kubectl get pods -n kadalu | grep pool-3
server-storage-pool-3-0-temp-0          0/2     Pending   0          11m
[node 1]# 

temp is not a host name but was provided as a dummy name. We should enhance the pre-check validation for the hosts/image etc. Otherwise the storage add request is successful but later it fails because its not part of the cluster. This is what the describe output shows

Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  15s (x9 over 9m10s)  default-scheduler  0/3 nodes are available: 3 node(s) didn't match node selector.

**Comment by amarts** [comment]
Valid request / bug.

A good issue for someone to get used to kadalu. Before issuing the `kubectl create` in CLI, one can check if the 'node' part is in `kubectl get nodes` output.

**Comment by aravindavk** [comment]
https://github.com/kadalu/kadalu/pull/208 Fixed this issue
