### ISSUE TITLE
Deleting external volume and then creating a new one fails

### ISSUE THREAD

**Issue by StoneCut** [kadalu/kadalu#209]
I've successfully been able to set up external storage using kubectl-kadalu (v0.6.0) and then a PVC thanks to your help on the slack channel. I then successfully used that PVC in a test deployment. This all worked fine.

Next, I deleted the PVC and implemented kadalu-quotad as a service on my GlusterFS nodes. I then wanted to provision a new PVC using the same storage class that was previously set up when I added the storage using kubectl-kadalu.

This PVC goes into "pending", however. Using the same storage class for other workloads (Prometheus and Grafana) gives the same results.

Please advise how to fix this, thank you!

I've attached the csi-provisioner-0 log.
[csi-provisioner-0.log](https://github.com/kadalu/kadalu/files/4286502/csi-provisioner-0.log)

**Comment by StoneCut** [comment]
Fixed with [Pull 210](https://github.com/kadalu/kadalu/pull/210).

**Comment by aravindavk** [comment]
Good to know that the patch fixes the issue. We will keep this issue open till that patch gets merged.

**Comment by StoneCut** [comment]
Ah, sorry about that. I'm still having other issues, too.
