### ISSUE TITLE
Question: Are you joining rooks?

### ISSUE THREAD

**Issue by renich** [kadalu/kadalu#212]
Recently, I've been worried about the status of GlusterFS in k8s. They haven't been maintaining their offering, to the best of my knowledge. 

This made me look towards the Cloud Native Computing Foundation and noticed the rooks project. 

I think it gives us a bit of certainty to see projects being supported. 

BTW, I wanted to ask this is Slack but didn't find the link to join your slack; only to login.

**Comment by amarts** [comment]
@renich you can join slack from the links at the bottom of website @ https://kadalu.io

As per our understanding, 'joining' rook project would again add layers to kadalu's architecture, and hence we believe it is better to stay a small layer with operator and csi being provided. As kubernetes is 'complex' already, our goal is to reduce layers in storage, and make it easy for users. Hence, at least as of now, there are no thoughts of joining rook project.
