### ISSUE TITLE
Upgrade/Migration path required

### ISSUE THREAD

**Issue by renich** [kadalu/kadalu#213]
I'm a GlusterFS user on k8s. I want to know if there is an upgrade/migration plan.

**Comment by amarts** [comment]
When you say you are 'GlusterFS' user in k8s, how have you consumed GlusterFS?  through heketi? or wrote your own custom scripts etc to manage storage?

You may be interested in this article - https://kadalu.io/docs/k8s-storage/latest/external-gluster-storage

**Comment by renich** [comment]
Well, the article is interesting, thank you. I meant more of a k8s + gluster converged setup. If I wanted to remove that one and port all my pvs to Kadalu, what would I have to do?

I could add more nodes and create a kadalu cluster in three of them. But, then, how do I port stuff to kadalu?

**Comment by amarts** [comment]
Thanks for confirming @renich!

At very top level, when we started kadalu, we didn't had any such upgrade path, and as kadalu is a whole new thinking of management layer of glusterfs, the backward compatibility is not possible. We thought k8s usage would grow in future, and as current gluster converged setups would not support CSI too, there may be a day for people to do a migration anyways, so it is better they migrate the data to kadalu PVs with tools like rsync etc.

That decision has helped us to keep the management layer too thin, and simple.

Now, with the already available features, one can still consume the PVs created in converged mode of gluster + k8s. Here is how.

1. Prepare the list of PV name -> Gluster volume name mapping. (This is possible with gluster volume info).
2. Pick one of the Gluster Pod IP (or multiple of them), and treat that as the external volume, and use Yaml sample described in [this document](https://github.com/kadalu/kadalu/blob/master/doc/external-gluster-storage.md#using-external-storage-directly), to create the PVs.
3. Use this PV in your pods in higher version of k8s.

---

Now note that while we can support this model, our development focus will be for those setups which implement a kadalu native way of creating PVs.

Hope this helps.

**Comment by renich** [comment]
Thank you for the help and suggestions.
