### ISSUE TITLE
error while running "VolumeBinding" filter plugin for pod "pod1": pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by milodano** [kadalu/kadalu#216]
ubuntu@kubemaster1:~$ kubectl describe  pod pod1
Name:         pod1
Namespace:    default
Priority:     0
Node:         kubenode1/63.48.36.32
Start Time:   Tue, 17 Mar 2020 20:19:34 +0000
Labels:       app=sample-app
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"app":"sample-app"},"name":"pod1","namespace":"default"},"spec":{"c...
Status:       Succeeded
IP:           10.36.0.3
IPs:
  IP:  10.36.0.3
Containers:
  sample-app:
    Container ID:   docker://4996c6e258b31a6f7f51c2fb703e95b597a116c544586555b4075876f7fd2548
    Image:          docker.io/kadalu/sample-pv-check-app:latest
    Image ID:       docker-pullable://kadalu/sample-pv-check-app@sha256:7df30e4f4c3377b6408808a973cf09e0f49b255cbe981b54eedf271777063f09
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 17 Mar 2020 20:19:54 +0000
      Finished:     Tue, 17 Mar 2020 20:19:54 +0000
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /mnt/pv from csivol (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-cspwl (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  csivol:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  pv1
    ReadOnly:   false
  default-token-cspwl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-cspwl
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age        From                     Message
  ----     ------                  ----       ----                     -------
  Warning  FailedScheduling        <unknown>  default-scheduler        error while running "VolumeBinding" filter plugin for pod "pod1": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling        <unknown>  default-scheduler        error while running "VolumeBinding" filter plugin for pod "pod1": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled               <unknown>  default-scheduler        Successfully assigned default/pod1 to kubenode1
  Normal   SuccessfulAttachVolume  2m57s      attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-905a8f25-6dd3-4c57-9920-2a3998bcf548"
  Normal   Pulling                 2m40s      kubelet, kubenode1       Pulling image "docker.io/kadalu/sample-pv-check-app:latest"
  Normal   Pulled                  2m37s      kubelet, kubenode1       Successfully pulled image "docker.io/kadalu/sample-pv-check-app:latest"
  Normal   Created                 2m37s      kubelet, kubenode1       Created container sample-app
  Normal   Started                 2m37s      kubelet, kubenode1       Started container sample-app
  Normal   SandboxChanged          2m36s      kubelet, kubenode1       Pod sandbox changed, it will be killed and re-created.

**Comment by amarts** [comment]
Looks like sample app completed fine. Can you check `kubectl logs pod1`?

Yes, the errors happened initially (may be because of server pods not being ready), but in next tries it succeeded.

**Comment by milodano** [comment]
Hello Amar,
thanks for you prompt response.
Here is the output:

----------------------------------------------------------------------------------------------------
ubuntu@kubemaster1:~$ kubectl logs pod1
This is a sample application
# df -h
Filesystem                Size      Used Available Use% Mounted on
/kadalu/volfiles/storage-pool-1.client.vol
                          1.0G     10.2M   1013.8M   1% /mnt/pv
# mount
/kadalu/volfiles/storage-pool-1.client.vol on /mnt/pv type fuse.glusterfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072)
Write/Read test on PV mount
Wed Mar 18 12:40:40 UTC 2020
SUCCESS

----------------------------------------------------------------------------------------------------

Seems like everything is ok, but when you check a pod description, you get that WARNING.. i was wondering if something you are aware off... and  if that is the problem? DO you have that same warning in your environment.????


I have tried another application, so this time nginx... 3 replicas...3 nodes...

----------------------------------------------------------------------------------------------------

NAMESPACE     NAME                                  READY   STATUS              RESTARTS   AGE
default       nginx3-67d4b4dd6d-54f75               0/1     ContainerCreating   0          21m
default       nginx3-67d4b4dd6d-nhmm4               0/1     ContainerCreating   0          21m
default       nginx3-67d4b4dd6d-nvjpb               1/1     Running             0          21m

----------------------------------------------------------------------------------------------------

1 pod has successfully mounted all the volumes, still has that WARNING "volumebinding..." but, the other two pods are failing mount...

----------------------------------------------------------------------------------------------------

ubuntu@kubemaster1:~$ kubectl describe pod nginx3-67d4b4dd6d-54f75
Name:           nginx3-67d4b4dd6d-54f75
Namespace:      default
Priority:       0
Node:           kubenode2/63.48.36.35
Start Time:     Wed, 18 Mar 2020 12:50:36 +0000
Labels:         pod-template-hash=67d4b4dd6d
                run=nginx3
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/nginx3-67d4b4dd6d
Containers:
  nginx:
    Container ID:   
    Image:          nginx:1.13
    Image ID:       
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/lib/nginx from nginx3-persistent-vol (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-cspwl (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  nginx3-persistent-vol:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  nginx3-pvc
    ReadOnly:   false
  default-token-cspwl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-cspwl
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason              Age                   From                     Message
  ----     ------              ----                  ----                     -------
  Warning  FailedScheduling    <unknown>             default-scheduler        error while running "VolumeBinding" filter plugin for pod "nginx3-67d4b4dd6d-54f75": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling    <unknown>             default-scheduler        error while running "VolumeBinding" filter plugin for pod "nginx3-67d4b4dd6d-54f75": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled           <unknown>             default-scheduler        Successfully assigned default/nginx3-67d4b4dd6d-54f75 to kubenode2
  Warning  FailedAttachVolume  13m                   attachdetach-controller  Multi-Attach error for volume "pvc-f625e4f8-b06a-4780-8f7f-88d0d098141c" Volume is already used by pod(s) nginx3-67d4b4dd6d-nvjpb
  Warning  FailedMount         6m41s (x2 over 11m)   kubelet, kubenode2       Unable to attach or mount volumes: unmounted volumes=[nginx3-persistent-vol], unattached volumes=[nginx3-persistent-vol default-token-cspwl]: timed out waiting for the condition
  Warning  FailedMount         2m7s (x3 over 8m55s)  kubelet, kubenode2       Unable to attach or mount volumes: unmounted volumes=[nginx3-persistent-vol], unattached volumes=[default-token-cspwl nginx3-persistent-vol]: timed out waiting for the condition

--------------------------------------------------------------------------------

ubuntu@kubemaster1:~$ kubectl get pods -n kadalu
NAME                                  READY   STATUS    RESTARTS   AGE
csi-nodeplugin-9mf4l                  3/3     Running   0          17h
csi-nodeplugin-wqvf9                  3/3     Running   0          17h
csi-nodeplugin-z6lnd                  3/3     Running   0          17h
csi-provisioner-0                     4/4     Running   0          17h
operator-5885d8c7f7-s7nng             1/1     Running   0          17h
server-storage-pool-1-kubenode1-0-0   2/3     Running   192        17h
server-storage-pool-1-kubenode2-1-0   2/3     Running   202        17h
server-storage-pool-1-kubenode3-2-0   3/3     Running   0          17h

---------------------------------------------------------------------------------------------

ubuntu@kubemaster1:~$ kubectl describe pod server-storage-pool-1-kubenode2-1-0 -n kadalu
Name:         server-storage-pool-1-kubenode2-1-0
Namespace:    kadalu
Priority:     0
Node:         kubenode2/63.48.36.35
Start Time:   Tue, 17 Mar 2020 20:14:39 +0000
Labels:       app.kubernetes.io/component=server
              app.kubernetes.io/name=server
              app.kubernetes.io/part-of=kadalu
              controller-revision-hash=server-storage-pool-1-kubenode2-1-5df74ffbfc
              statefulset.kubernetes.io/pod-name=server-storage-pool-1-kubenode2-1-0
Annotations:  <none>
Status:       Running
IP:           10.40.0.3
IPs:
  IP:           10.40.0.3
Controlled By:  StatefulSet/server-storage-pool-1-kubenode2-1
Containers:
  glusterfsd:
    Container ID:   docker://1788c4c157d58e7b8e2868a108f4924d919b405e0c201d7ed8edb7d9d3bcc81e
    Image:          docker.io/kadalu/kadalu-server:0.6.0
    Image ID:       docker-pullable://kadalu/kadalu-server@sha256:809581aaab6eb1be68d23dbc5077b18e16c02399da7c2cdb36a1735de374dc2f
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    143
      Started:      Wed, 18 Mar 2020 13:15:29 +0000
      Finished:     Wed, 18 Mar 2020 13:18:09 +0000
    Ready:          False
    Restart Count:  198
    Liveness:       tcp-socket :24007 delay=120s timeout=1s period=20s #success=1 #failure=3
    Readiness:      tcp-socket :24007 delay=7s timeout=1s period=10s #success=1 #failure=3
    Environment:
      HOSTNAME:        kubenode2
      VOLUME:          storage-pool-1
      VOLUME_TYPE:     Replica3
      BRICK_PATH:      /bricks/storage-pool-1/data/brick
      NODEID:          ee12808a-688b-11ea-af9a-4a8b357d66b9
      VOLUME_ID:       ee127dc4-688b-11ea-af9a-4a8b357d66b9
      BRICK_INDEX:     1
      BRICK_DEVICE:    /var/vdb
      KADALU_VERSION:  0.6.0
    Mounts:
      /brickdev from brick-device-dir (rw)
      /bricks/storage-pool-1 from glusterfsd-mountdir (rw)
      /dev from gluster-dev (rw)
      /sys/fs/cgroup from gluster-cgroup (ro)
      /usr/lib/modules from gluster-kmods (ro)
      /var/lib/gluster from glusterfsd-volfilesdir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kadalu-server-sa-token-wx8nt (ro)
  quotad:
    Container ID:   docker://f6c67667071f46753f7c0868ea56a31287140dac165f476a48ff141fc15098c2
    Image:          docker.io/kadalu/kadalu-server:0.6.0
    Image ID:       docker-pullable://kadalu/kadalu-server@sha256:809581aaab6eb1be68d23dbc5077b18e16c02399da7c2cdb36a1735de374dc2f
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 17 Mar 2020 20:14:46 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      HOSTNAME:            kubenode2
      VOLUME:              storage-pool-1
      VOLUME_TYPE:         Replica3
      BRICK_PATH:          /bricks/storage-pool-1/data/brick
      NODEID:              ee12808a-688b-11ea-af9a-4a8b357d66b9
      VOLUME_ID:           ee127dc4-688b-11ea-af9a-4a8b357d66b9
      BRICK_INDEX:         1
      KADALU_SERVER_ROLE:  quotad
      SUBVOL_ROOT:         subvol
      BRICK_DEVICE:        /var/vdb
      KADALU_VERSION:      0.6.0
    Mounts:
      /bricks/storage-pool-1 from glusterfsd-mountdir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kadalu-server-sa-token-wx8nt (ro)
  shd:
    Container ID:   docker://d977fa662ee74b9dab9b888066ab973c89f38be04c48aef8d04c15c55c125d2d
    Image:          docker.io/kadalu/kadalu-server:0.6.0
    Image ID:       docker-pullable://kadalu/kadalu-server@sha256:809581aaab6eb1be68d23dbc5077b18e16c02399da7c2cdb36a1735de374dc2f
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 17 Mar 2020 20:14:46 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      HOSTNAME:            kubenode2
      VOLUME:              storage-pool-1
      VOLUME_TYPE:         Replica3
      BRICK_PATH:          /bricks/storage-pool-1/data/brick
      NODEID:              ee12808a-688b-11ea-af9a-4a8b357d66b9
      VOLUME_ID:           ee127dc4-688b-11ea-af9a-4a8b357d66b9
      BRICK_INDEX:         1
      KADALU_SERVER_ROLE:  shd
      SUBVOL_ROOT:         subvol
      BRICK_DEVICE:        /var/vdb
      KADALU_VERSION:      0.6.0
    Mounts:
      /var/lib/gluster from glusterfsd-volfilesdir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kadalu-server-sa-token-wx8nt (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  gluster-dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:  
  gluster-cgroup:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/fs/cgroup
    HostPathType:  
  gluster-kmods:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/lib/modules
    HostPathType:  
  glusterfsd-volfilesdir:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kadalu-info
    Optional:  false
  glusterfsd-mountdir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  brick-device-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var
    HostPathType:  Directory
  kadalu-server-sa-token-wx8nt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kadalu-server-sa-token-wx8nt
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                     From                Message
  ----     ------     ----                    ----                -------
  Warning  Unhealthy  6m57s (x3104 over 17h)  kubelet, kubenode2  Readiness probe failed: dial tcp 10.40.0.3:24007: connect: connection refused
  Warning  BackOff    116s (x2283 over 16h)   kubelet, kubenode2  Back-off restarting failed container
ubuntu@kubemaster1:~$ kubectl get svc
NAME         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
kubernetes   ClusterIP   10.96.0.1        <none>        443/TCP        18h
nginx3       NodePort    10.104.104.194   <none>        80:31536/TCP   33m

--------------------------------------------------------------------------------
I see service on port 24007... 

ubuntu@kubemaster1:~$ kubectl get svc -n kadalu
NAME             TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)     AGE
storage-pool-1   ClusterIP   None         <none>        24007/TCP   17h

--------------------------------------------------------------------------------

ubuntu@kubemaster1:~$ kubectl logs server-storage-pool-1-kubenode2-1-0 -n kadalu
error: a container name must be specified for pod server-storage-pool-1-kubenode2-1-0, choose one of: [glusterfsd quotad shd]

--------------------------------------------------------------------------------

Is this something you think is due to my environment or?

--------------------------------------------------------------------------------

btw i love this CSI so far, just to make it work completely... hehehhe...   you are doing a great job...

**Comment by milodano** [comment]
maybe also this will help

ubuntu@kubemaster1:~$ kubectl get pod server-storage-pool-1-kubenode1-0-0 -o yaml -n kadalu | less
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-03-17T20:14:39Z"
  generateName: server-storage-pool-1-kubenode1-0-
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: server
    app.kubernetes.io/part-of: kadalu
    controller-revision-hash: server-storage-pool-1-kubenode1-0-8bb686b88
    statefulset.kubernetes.io/pod-name: server-storage-pool-1-kubenode1-0-0
  name: server-storage-pool-1-kubenode1-0-0
  namespace: kadalu
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: server-storage-pool-1-kubenode1-0
    uid: 0a7a9e8e-678f-4b74-977c-3cc924768930
  resourceVersion: "204802"
  selfLink: /api/v1/namespaces/kadalu/pods/server-storage-pool-1-kubenode1-0-0
  uid: e0db8362-04c8-413d-b982-3fea0e7dae25
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - kubenode1
  containers:
  - env:
    - name: HOSTNAME
      value: kubenode1
    - name: VOLUME
      value: storage-pool-1
    - name: VOLUME_TYPE
      value: Replica3
    - name: BRICK_PATH
      value: /bricks/storage-pool-1/data/brick
    - name: NODEID
      value: ee127fd6-688b-11ea-af9a-4a8b357d66b9
    - name: VOLUME_ID
      value: ee127dc4-688b-11ea-af9a-4a8b357d66b9
    - name: BRICK_INDEX
      value: "0"
    - name: BRICK_DEVICE
      value: /var/vdb
    - name: KADALU_VERSION
      value: 0.6.0
    image: docker.io/kadalu/kadalu-server:0.6.0
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /kadalu/stop-server.sh
          - storage-pool-1
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 120
      periodSeconds: 20
      successThreshold: 1
      tcpSocket:
    controller-revision-hash: server-storage-pool-1-kubenode1-0-8bb686b88
    controller-revision-hash: server-storage-pool-1-kubenode1-0-8bb686b88
    statefulset.kubernetes.io/pod-name: server-storage-pool-1-kubenode1-0-0
  name: server-storage-pool-1-kubenode1-0-0
  namespace: kadalu
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: server-storage-pool-1-kubenode1-0
    uid: 0a7a9e8e-678f-4b74-977c-3cc924768930
  resourceVersion: "204802"
  selfLink: /api/v1/namespaces/kadalu/pods/server-storage-pool-1-kubenode1-0-0
  uid: e0db8362-04c8-413d-b982-3fea0e7dae25
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-03-17T20:14:39Z"
  generateName: server-storage-pool-1-kubenode1-0-
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: server
    app.kubernetes.io/part-of: kadalu
    controller-revision-hash: server-storage-pool-1-kubenode1-0-8bb686b88
    statefulset.kubernetes.io/pod-name: server-storage-pool-1-kubenode1-0-0
  name: server-storage-pool-1-kubenode1-0-0
  namespace: kadalu
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: server-storage-pool-1-kubenode1-0
    uid: 0a7a9e8e-678f-4b74-977c-3cc924768930
  resourceVersion: "204802"
  selfLink: /api/v1/namespaces/kadalu/pods/server-storage-pool-1-kubenode1-0-0
  uid: e0db8362-04c8-413d-b982-3fea0e7dae25
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - kubenode1
  containers:
  - env:
    - name: HOSTNAME
      value: kubenode1
    - name: VOLUME
      value: storage-pool-1
    - name: VOLUME_TYPE
      value: Replica3
    - name: BRICK_PATH
      value: /bricks/storage-pool-1/data/brick
    - name: NODEID
      value: ee127fd6-688b-11ea-af9a-4a8b357d66b9
    - name: VOLUME_ID
      value: ee127dc4-688b-11ea-af9a-4a8b357d66b9
    - name: BRICK_INDEX
      value: "0"
    - name: BRICK_DEVICE
      value: /var/vdb
    - name: KADALU_VERSION
      value: 0.6.0
    image: docker.io/kadalu/kadalu-server:0.6.0
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /kadalu/stop-server.sh
          - storage-pool-1
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 120
      periodSeconds: 20
      successThreshold: 1
      tcpSocket:
        port: 24007
      timeoutSeconds: 1
    name: glusterfsd
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 7
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: 24007
      timeoutSeconds: 1
    resources: {}
    securityContext:
      capabilities: {}
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /dev
      name: gluster-dev
    - mountPath: /sys/fs/cgroup
      name: gluster-cgroup
      readOnly: true
    - mountPath: /usr/lib/modules
      name: gluster-kmods
      readOnly: true
    - mountPath: /var/lib/gluster
      name: glusterfsd-volfilesdir
    - mountPath: /bricks/storage-pool-1
      mountPropagation: Bidirectional
      name: glusterfsd-mountdir
    - mountPath: /brickdev
      name: brick-device-dir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kadalu-server-sa-token-wx8nt
      readOnly: true
  - env:
    - name: HOSTNAME
      value: kubenode1
    - name: VOLUME
      value: storage-pool-1
    - name: VOLUME_TYPE
      value: Replica3
    - name: BRICK_PATH
      value: /bricks/storage-pool-1/data/brick
    - name: NODEID
      value: ee127fd6-688b-11ea-af9a-4a8b357d66b9
    - name: VOLUME_ID
      value: ee127dc4-688b-11ea-af9a-4a8b357d66b9
    - name: BRICK_INDEX
      value: "0"
    - name: KADALU_SERVER_ROLE
      value: quotad
    - name: SUBVOL_ROOT
      value: subvol
    - name: BRICK_DEVICE
      value: /var/vdb
    - name: KADALU_VERSION
      value: 0.6.0
    image: docker.io/kadalu/kadalu-server:0.6.0
    imagePullPolicy: IfNotPresent
    name: quotad
    resources: {}
    securityContext:
      capabilities: {}
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /bricks/storage-pool-1
      mountPropagation: Bidirectional
      name: glusterfsd-mountdir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kadalu-server-sa-token-wx8nt
      readOnly: true
  - env:
    - name: HOSTNAME
      value: kubenode1
    - name: VOLUME
      value: storage-pool-1
    - name: VOLUME_TYPE
      value: Replica3
    - name: BRICK_PATH
      value: /bricks/storage-pool-1/data/brick
    - name: NODEID
      value: ee127fd6-688b-11ea-af9a-4a8b357d66b9
    - name: VOLUME_ID
      value: ee127dc4-688b-11ea-af9a-4a8b357d66b9
    - name: BRICK_INDEX
      value: "0"
    - name: KADALU_SERVER_ROLE
      value: shd
    - name: SUBVOL_ROOT
      value: subvol
    - name: BRICK_DEVICE
      value: /var/vdb
    - name: KADALU_VERSION
      value: 0.6.0
    image: docker.io/kadalu/kadalu-server:0.6.0
    imagePullPolicy: IfNotPresent
    name: shd
    resources: {}
    securityContext:
      capabilities: {}
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/gluster
      name: glusterfsd-volfilesdir
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kadalu-server-sa-token-wx8nt
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: server-storage-pool-1-kubenode1-0-0
  nodeName: kubenode1
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: kadalu-server-sa
  serviceAccountName: kadalu-server-sa
  subdomain: storage-pool-1
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /dev
      type: ""
    name: gluster-dev
  - hostPath:
      path: /sys/fs/cgroup
      type: ""
    name: gluster-cgroup
  - hostPath:
      path: /usr/lib/modules
      type: ""
    name: gluster-kmods
  - configMap:
      defaultMode: 420
      name: kadalu-info
    name: glusterfsd-volfilesdir
  - emptyDir: {}
    name: glusterfsd-mountdir
  - hostPath:
      path: /var
      type: Directory
    name: brick-device-dir
  - name: kadalu-server-sa-token-wx8nt
    secret:
      defaultMode: 420
      secretName: kadalu-server-sa-token-wx8nt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-03-17T20:14:39Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-03-17T20:14:39Z"
    message: 'containers with unready status: [glusterfsd]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-03-17T20:14:39Z"
    message: 'containers with unready status: [glusterfsd]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-03-17T20:14:38Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  _- containerID: docker://3ec7663b1beb65a227f38e5b5079c3f5e9dce3ba2b4f48ef18a664953ce52b4b
    image: kadalu/kadalu-server:0.6.0
    imageID: docker-pullable://kadalu/kadalu-server@sha256:809581aaab6eb1be68d23dbc5077b18e16c02399da7c2cdb36a1735de374dc2f
    lastState:
      terminated:
        containerID: docker://3ec7663b1beb65a227f38e5b5079c3f5e9dce3ba2b4f48ef18a664953ce52b4b
        exitCode: 143
        finishedAt: "2020-03-18T15:31:33Z"
        reason: Error
        startedAt: "2020-03-18T15:28:34Z"
    name: glusterfsd
    ready: false
    restartCount: 213
    started: false
    state:
      waiting:
        message: **back-off 5m0s restarting failed container=glusterfsd pod=server-storage-pool-1-kubenode1-0-0_kadalu(e0db8362-04c8-413d-b982-3fea0e7dae25)**
        reason: CrashLoopBackOff
  - containerID: docker://815802c6ee9a9344ea38c908970b17a80e40fe673bacaf5c37f0546a2cea7e7b
    image: kadalu/kadalu-server:0.6.0
    imageID: docker-pullable://kadalu/kadalu-_server@sha256:809581aaab6eb1be68d23dbc5077b18e16c02399da7c2cdb36a1735de374dc2f
    lastState: {}
    name: quotad
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-03-17T20:14:46Z"
  - containerID: docker://9a6b3992453baa5bf3d447c713e01b7e69c64802814c27427bf1d787fcd710cc
    image: kadalu/kadalu-server:0.6.0
    imageID: docker-pullable://kadalu/kadalu-server@sha256:809581aaab6eb1be68d23dbc5077b18e16c02399da7c2cdb36a1735de374dc2f
    lastState: {}
    name: shd
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-03-17T20:14:46Z"
  hostIP: 63.48.36.32
  phase: Running
  podIP: 10.36.0.2
  podIPs:
  - ip: 10.36.0.2
  qosClass: BestEffort
  startTime: "2020-03-17T20:14:39Z"

**Comment by milodano** [comment]
root@kubenode1:/home/ubuntu# docker logs 53156cbd4ffc 
+ pid=0
+ cmd=/usr/bin/python3
+ script=/kadalu/server.py
+ trap 'kill ${!}; term_handler' SIGTERM
+ pid=6
+ true
+ /usr/bin/python3 /kadalu/server.py
+ wait 7
+ tail -f /dev/null
[2020-03-18 15:36:37,796] ERROR [glusterfsd - 107:create_and_mount_brick] - Failed to create file system         fstype=xfs device=/brickdev/vdb
++ kill 7
++ term_handler
++ '[' 6 -ne 0 ']'
++ kill -SIGTERM 6
/kadalu/startup.sh: line 12: kill: (6) - No such process
++ wait 6
++ exit 143

**Comment by milodano** [comment]
kubectl kadalu storage-add storage-pool-1 --type Replica3 --device kubenode1:/var/vdb --device kubenode2:/var/vdb --device kubenode3:/dev/vdb

ahhh, user error... :) sorry fo bothering you... keep up the good work, thanks again a lot

**Comment by milodano** [comment]
ahh, i got new error:

ubuntu@kubemaster1:~$ kubectl describe pod nginx3-67d4b4dd6d-gbrfb 
Name:           nginx3-67d4b4dd6d-gbrfb
Namespace:      default
Priority:       0
Node:           kubenode3/63.48.36.28
Start Time:     Wed, 18 Mar 2020 16:48:06 +0000
Labels:         pod-template-hash=67d4b4dd6d
                run=nginx3
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/nginx3-67d4b4dd6d
Containers:
  nginx:
    Container ID:   
    Image:          nginx:1.13
    Image ID:       
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/lib/nginx from nginx3-persistent-vol (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-2xk5v (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  nginx3-persistent-vol:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  nginx3-pvc
    ReadOnly:   false
  default-token-2xk5v:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-2xk5v
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason              Age        From                     Message
  ----     ------              ----       ----                     -------
  Warning  FailedScheduling    <unknown>  default-scheduler        error while running "VolumeBinding" filter plugin for pod "nginx3-67d4b4dd6d-gbrfb": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling    <unknown>  default-scheduler        error while running "VolumeBinding" filter plugin for pod "nginx3-67d4b4dd6d-gbrfb": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled           <unknown>  default-scheduler        Successfully assigned default/nginx3-67d4b4dd6d-gbrfb to kubenode3
  Warning  FailedAttachVolume  56s        attachdetach-controller  Multi-Attach error for volume "pvc-412f3bd3-61cb-4f02-8399-4076a56dcbbf" Volume is already used by pod(s) nginx3-67d4b4dd6d-82bc4

-----------------------------------------------------------------------------------------------

Isn't it supposed to work with multiple replicas?

**Comment by milodano** [comment]
It was user error, thanks a lot... this CSI is amazing BTW, good job
