### ISSUE TITLE
Enable support for K8s 1.18

### ISSUE THREAD

**Issue by aravindavk** [kadalu/kadalu#218]
Kubernetes 1.18 is released. Enable support for this version.

https://kubernetes.io/blog/2020/03/25/kubernetes-1-18-release-announcement/

**Comment by superbiche** [comment]
@aravindavk I've setup Kadalu on a managed Kubernetes running 1.18, using external pool, it works perfectly, and on another one (Bare Metal HA), running 1.18.2, provisioning with a native pool, both work like a charm. 
I guess you have some compatibility work to do but I just wanted to let you know and also, great job, the latest releases are really looking good.

**Comment by amarts** [comment]
Good to hear that!  We wanted to add 1.18 in our testing (.travis.yml) to say it is ready!

**Comment by amarts** [comment]
Implemented with #225
