### ISSUE TITLE
Broken reference link in "Try Kadalu" Web Page

### ISSUE THREAD

**Issue by rhinduja** [kadalu/kadalu#219]
Severity: Med

Description: 
We have broken link reference in "Try Kadalu" Web page

Steps: 
1: Access page "https://kadalu.io/docs/k8s-storage/master/try-kadalu#try-kadalu"
2: Scroll Down to "Gluster and Kadalu" Segment
3. Access the link mentioned under here in statement "We have compiled a list of things here"

Link mentioned under here is "https://kadalu.io/docs/k8s-storage/master/gluster-and-kadalu.md" which is broken...

**Comment by sankarshanmukhopadhyay** [comment]
Thank you for catching and reporting this. We'll address this quickly.

**Comment by aravindavk** [comment]
This is now fixed by the PR: https://github.com/kadalu/docs/pull/4

Thanks for reporting
