### ISSUE TITLE
Multiple Broken Reference Links under "kadalu.io" webpage

### ISSUE THREAD

**Issue by rhinduja** [kadalu/kadalu#221]
Severity: High
Impact: Usability / Troubleshooting / Product Engagement

Description:
Identified more broken links through the kadalu.io webpage. Raising a new issue then #219 as this is more of generic. Will keep this issue updated for any additional broken ref object before closure of this issue. 

Link 1: 
--------
Broken Link: https://github.com/kadalu/kadalu/extras/scripts/cleanup
Reference Under: https://kadalu.io/docs/k8s-storage/latest/troubleshooting 
Exact Issue: 404 link (Check script hyperlink under statement "Note: Use the cleanup script to properly cleanup kadalu.")

Link 2:
--------
Broken Link: https://kadalu.io/docs/running-a-webserver
Reference Under: https://kadalu.io/blog/kadalu-kubernetes-storage
Exact Issue: 404 link (Check here hyperlink under statement "Documentation for this use-case is available here")

Link 3:
---------
Broken Link: https://kadalu.io/docs/get-involved
Reference Under: https://kadalu.io/community
Exact Issue:  404 link issue (Click on "Get Involved")

Link 4:
---------
Broken Link: https://kadalu.io/author/sankarshanmukhopadhyay
Reference Under: https://kadalu.io/blog/how-are-we-building-for-kadalu-v1.0
Exact Issue: 404 page not found (Click on Name "Sankarshan Mukhopadhyay" just below the image on right most corner. This has reference to the broken link)

PS: All these are not the actual functional issue of the product but IMO are important to raise for community involvement and product perception and hence raising. 

Rgds,
Rahul

**Comment by aravindavk** [comment]
Thanks. I will fix the issues

**Comment by aravindavk** [comment]
Fixed now with PR https://github.com/kadalu/kadalu.github.io/pull/32 and https://github.com/kadalu/kadalu/pull/222
