### ISSUE TITLE
provide a way to uninstall

### ISSUE THREAD

**Issue by marklester** [kadalu/kadalu#238]
For a user who is testing out kadalu it would be useful to have uninstall command or instructions.

**Comment by unixfox** [comment]
:+1: I wanted to reinstall kadalu for testing purposes but I don't know where to start for the uninstall.

**Comment by amarts** [comment]
https://github.com/kadalu/kadalu/blob/devel/extras/scripts/cleanup is what we have provided! Will add it to Quick-Start guide! Check and remove what all you need to remove in that script!.

**Comment by amarts** [comment]
Added link to cleanup script in README (in #349)
