### ISSUE TITLE
csi-nodeplugin error

### ISSUE THREAD

**Issue by marklester** [kadalu/kadalu#239]
I get the following error
```
MountVolume.SetUp failed for volume "pods-mount-dir" : hostPath type check failed: /var/lib/kubelet/pods │
│  is not a directory
```
I am using microk8s and I don't think it uses that directory:
https://microk8s.io/docs/configuring-services

**Comment by marklester** [comment]
From: 
https://github.com/kadalu/kadalu/blob/master/templates/csi.yaml.j2#L66
it looks like that needs to be set to:
/var/snap/microk8s/common/var/lib/kubelet/plugins
for microk8s

**Comment by aravindavk** [comment]
Thanks for the pointer. We will see how to dynamically get the `kubelet/plugins` directory dynamically.

**Comment by marklester** [comment]
Looks like I got it working. Do you accept prs? 
They way I got it working was add an environment variable that can be replaced at operator deploy time.

**Comment by aravindavk** [comment]
Nice. Looked at the PR looks good. We do accept PRs, Thanks.

**Comment by aravindavk** [comment]
@marklester Do you know any mechanism to detect k8s distribution inside pod? If available then `KUBELET_DIR` can be determined runtime itself(Current approach requires different Operator Yaml file during deployment)

```
if is_microk8s():
    KUBELET_DIR = ...
else:
   KUBELET_DIR
```

**Comment by marklester** [comment]
not full proof. For microk8s it looks like they label their nodes
with: 
`microk8s.io/cluster=true`
I can ask in their chat to see if they plan on doing that indefinitely.

ok I will try to have pr up soon.

**Comment by marklester** [comment]
ok just confirmed in the microk8s chatroom. That is how they identify microk8s nodes.
so if node.labels.contains("microk8s") should be a reliable way to do it from microk8s

**Comment by marklester** [comment]
@aravindavk  are you thinking of adding a flag to the install cmd? 
`kubectl kadalu install type=microk8s`

or does it make sense to add it as an option like

`kubectl kadalu install --kubelet-dir=...`

the 2nd seems more general purpose. I could see a plugin for microk8s where you can do
`microk8s.enable kadalu` where it it just sets the kubelet dir

**Comment by aravindavk** [comment]
The first option looks good. We are already using `--type` for some customization for `openshift`.

Your approach based on env variable looks good. `kubectl kadalu` can substitute `KUBELET_DIR` based on k8s distribution.
