### ISSUE TITLE
[RFE] Storage Pods Upgrade during Operator Pod Start

### ISSUE THREAD

**Issue by aravindavk** [kadalu/kadalu#242]
After upgrading Kadalu Operator, it upgrades the CSI pods and other resources except Storage Pods.

Enhance the Operator to try upgrading Storage pods if the Version is different than the deployed version.

Pseudo code,

```
installed_version = get_version_from_configmap()
if operator_version != installed_version {
    servers = get_servers_data_from_configmap()
    for server <- servers {
        generate_server_yaml(server)
        kubectl_apply()
    }
}
```

**Comment by robojones** [comment]
We should be able to always use apply without explicitly checking if the version has changed. Kubernetes will only upgrade the objects if the yaml file has changed.

**Comment by amarts** [comment]
This is now partially complete with `0.7.6`. 

The next steps involved are actually checking for heal pending state before upgrading storage pods in replica2 and replica3 volumes. It involves us to use few of the PRs which are only in glusterfs `devel` branch. Will consider using a release for a cherry picked PRs from glusterfs repo to enable them. It would be done in v1.0 (when we start kadalu version of glusterfs). Will open another issue to track the RFE. For now advise is to have no load on the volume while upgrading.
