### ISSUE TITLE
Creation of volumes fails with: No Hosting Volumes available, add more storage

### ISSUE THREAD

**Issue by ncresswell** [kadalu/kadalu#247]
Using Kadalu 0.7 and replica1 storage class, I can create a volume just fine that is 5Gi, 10Gi, 15Gi, but if i increase the size any larger than 15Gi it gets stuck forever with: 

failed to provision volume with StorageClass "kadalu.replica1": rpc error: code = ResourceExhausted desc = No Hosting Volumes available, add more storage"

my underlying storage is 100GB, and there is nothing in it.
![image](https://user-images.githubusercontent.com/23178133/81730320-72a21a00-94e1-11ea-99f3-fc984ed64423.png)

![image](https://user-images.githubusercontent.com/23178133/81730362-83529000-94e1-11ea-9da0-c6d1cc837b44.png)

and here are my container logs from the storagepool pod
![image](https://user-images.githubusercontent.com/23178133/81731128-a3cf1a00-94e2-11ea-8dc6-39c4553eb74b.png)

seemingly, its reporting "free space" of only 19GB, which is weird as thats not the case.

Also, i can create multiple 15Gi volumes (concurrently), right up to my 100GB of storage used, no issue.. so this is only an issue when trying to create a single volume over 15Gi.

I also tried my storage class replica 2, and it also can only create volumes <15Gi in size. It however correctly reports "free space" of 100GB.

![image](https://user-images.githubusercontent.com/23178133/81733250-d2022900-94e5-11ea-8a53-84e6fd5c3dd6.png)

**Comment by aravindavk** [comment]
Thanks for reporting the issue.
