### ISSUE TITLE
[RFE] Include Kubectl Kadalu in Operator image

### ISSUE THREAD

**Issue by aravindavk** [kadalu/kadalu#250]
Installing a new package specific to Kadalu is not straight forward compared to Kubernetes setup. Many people are familiar with YAML based installation but not `pip` based installation.

Include Kubectl kadalu inside Operator, so that those utilities can be used using kubectl exec commands.

```
alias kadalucli='kubectl exec -it $(kubectl get pods -n kadalu -o name | grep operator | sed 's#pod/##') -n kadalu /usr/local/bin/kubectl-kadalu '
```

Now use Kadalu helper utility without installing any code in the host machine.

For example,

```
kadalucli storage-add ...
```

Document update required are:

* Kadalu install using `kubectl create -f` command.
* Storage add using YAML
* Alternate helper section explaining the above approach.
* Separate Doc for kubectl-kadalu install and use.

Changes required to Kubectl kadalu when installed inside the operator are:

* Don't expose `install` command(Since Kadalu Operator is already installed)
* Change `-h` or `--help` to something else, since it conflicts with `kubectl` command.(May be `kadalucli help storage-add`)

**Comment by aravindavk** [comment]
good to have and easy to implement(only `Dockerfile` changes)

**Comment by vatsa287** [comment]
> Installing a new package specific to Kadalu is not straight forward compared to Kubernetes setup. Many people are familiar with YAML based installation but not `pip` based installation.
> 
> Include Kubectl kadalu inside Operator, so that those utilities can be used using kubectl exec commands.
> 
> ```
> alias kadalucli='kubectl exec -it $(kubectl get pods -n kadalu -o name | grep operator | sed 's#pod/##') -n kadalu /usr/local/bin/kubectl-kadalu '
> ```
> 
> Now use Kadalu helper utility without installing any code in the host machine.
> 
> For example,
> 
> ```
> kadalucli storage-add ...
> ```
> 
> Document update required are:
> 
>     * Kadalu install using `kubectl create -f` command.
> 
>     * Storage add using YAML
> 
>     * Alternate helper section explaining the above approach.
> 
>     * Separate Doc for kubectl-kadalu install and use.
> 
> 
> Changes required to Kubectl kadalu when installed inside the operator are:
> 
>     * Don't expose `install` command(Since Kadalu Operator is already installed)
> 
>     * Change `-h` or `--help` to something else, since it conflicts with `kubectl` command.(May be `kadalucli help storage-add`)

Used /usr/bin and not /usr/local/bin for kubectl-kadalu.
