### ISSUE TITLE
[RFE] Push Manifest files to Release instead of keeping in source tree

### ISSUE THREAD

**Issue by aravindavk** [kadalu/kadalu#255]
Currently, manifest files are saved under `$SRC/manifests` directory and `kubectl kadalu install` uses files from the manifests directory.

- Add these manifest files to the release (Example: https://github.com/kadalu/kadalu/releases/tag/0.7.0)
- Change Documentation to use this path
- Change Kubectl kadalu CLI to use this path.

**Bonus**: Automatically copy the generated yaml files to release using Github actions.
https://github.com/marketplace/actions/upload-files-to-a-github-release

**Comment by aravindavk** [comment]
Also use the same approach to upload the `kubectl-kadalu` binary.

Example: `KADALU_VERSION=0.7.1 make cli-build` and then copy `./cli/build/kubectl-kadalu` to release page.

**Comment by amarts** [comment]
Done with `0.7.5` and now available in `0.7.6` too.
