### ISSUE TITLE
Could not mount the volume 

### ISSUE THREAD

**Issue by kannanvr** [kadalu/kadalu#257]
Hi All,
  I am trying to evaluate the performance between Heket-GFs and Kadalu GFS for my project purpose
I have attached 1 disk on the node  and able to provision Heketi-GFS... and on the same node, i have attached another disk(from Vsphere) on the same node and trying to enable Kadalu GFS.
The moment i have created the volume, server-storage-pool-1-0-0 pod is created and it is failing due to below error.

Please guide us to resolve this issue 
******************
[2020-05-20 08:53:14,862] ERROR [glusterfsd - 125:create_and_mount_brick] - Failed to mount export brick         fstype=xfs device=/dev/sdc mountdir=/bricks/storage-pool-1/data error=[32]  mount: /bricks/storage-pool-1/data: wrong fs type, bad option, bad superblock on /dev/sdc, missing codepage or helper program, or other error.
### 
***************

**Comment by aravindavk** [comment]
This is one known issue which we are working on. If the Host machine where Kubernetes is setup is having old Kernel(For example, CentOS 7). Kadalu Server pod creates XFS filesystem with latest version of `xfsprogs` which doesn't have mount support in host Kernel.

Work around: Preformat(`mkfs.xfs /devsdc`) the device in the host machine, before giving it to the Kadalu.

**Comment by kannanvr** [comment]
Thanks @aravindavk for your prompt Response...
