### ISSUE TITLE
Underlying storage is not deleted when PVC/PV is deleted

### ISSUE THREAD

**Issue by rajasaur** [kadalu/kadalu#265]
Kadalu branch: 0.6.0
Kubernetes: 1.16.0

When deleting the PVC/PV and Storage class of kadalu.replica1 (Althought it doesnt matter as all of them use a Reclaimpolicy: Delete), the underlying storage in the file system is not freed up. 
I can find the storage still getting used and the files retained on the physical disk.

It will be required to free-up the space from the underlying storage when the pvc is deleted.

Snippet from chat on #kadalu is attached.

> Raja  11:09 PM
> Shouldnt the underlying storage get deleted when a PVC (And PV) are deleted ? I find that the underlying storage is kept even though the PVC is deleted. The storageClass used in kadalu.replica1 which has a reclaimPolicy of delete
> 
> AmarTumballi  9:20 AM
> @Raja yes, it should. As we are not yet v1.0, we didn't want to deal with deleting data, just in case there are bugs... It is a line addition in Provisioner to delete the backend dir for Delete Volume...  We will enable that soon.

**Comment by papanito** [comment]
See also comment https://github.com/kadalu/kadalu/issues/184#issuecomment-589744596

**Comment by papanito** [comment]
Has this been fixed?

**Comment by amarts** [comment]
#254 fixes this issue. Please upgrade to 0.7.x version!

**Comment by papanito** [comment]
Cool thanks @amarts I will have a look. So I guess you can close the issue then
