### ISSUE TITLE
csi-provisioner fails to deploy on arm

### ISSUE THREAD

**Issue by FlexibleToast** [kadalu/kadalu#271]
I have a 4 node  cluster of Raspberry Pi 4 (4GB) nodes. I'm running Ubuntu 20.04 arm64 as the OS, using k3s, and running etcd for high availability, 3 master nodes and 1 worker node. Each node has two USB drives I would like to use as persistent storage. Upon deployment of a fresh cluster I attempted to deploy kadalu using the instructions for arm here: https://github.com/kadalu/kadalu#arm-support. The kadalu operator deploys successfully, the csi-nodeplogin containers hang at ContainerCreating, and the csi-provisioner errors eventually causing CrashLoopBackOff.

```
Events:
  Type     Reason     Age                  From                 Message
  ----     ------     ----                 ----                 -------
  Normal   Scheduled  <unknown>            default-scheduler    Successfully assigned kadalu/csi-provisioner-0 to pikubed-m1
  Normal   Pulling    23m                  kubelet, pikubed-m1  Pulling image "quay.io/k8scsi/csi-provisioner:v1.0.1"
  Normal   Pulled     23m                  kubelet, pikubed-m1  Successfully pulled image "quay.io/k8scsi/csi-provisioner:v1.0.1"
  Normal   Created    23m                  kubelet, pikubed-m1  Created container csi-provisioner
  Normal   Started    23m                  kubelet, pikubed-m1  Started container csi-provisioner
  Normal   Pulling    23m                  kubelet, pikubed-m1  Pulling image "quay.io/k8scsi/csi-attacher:v1.0.1"
  Normal   Pulled     23m                  kubelet, pikubed-m1  Successfully pulled image "quay.io/k8scsi/csi-attacher:v1.0.1"
  Normal   Started    23m                  kubelet, pikubed-m1  Started container csi-attacher
  Normal   Created    23m                  kubelet, pikubed-m1  Created container csi-attacher
  Normal   Pulling    23m                  kubelet, pikubed-m1  Pulling image "docker.io/kadalu/kadalu-csi:master"
  Normal   Pulling    22m                  kubelet, pikubed-m1  Pulling image "docker.io/kadalu/kadalu-csi:master"
  Normal   Pulled     20m                  kubelet, pikubed-m1  Successfully pulled image "docker.io/kadalu/kadalu-csi:master"
  Normal   Pulling    20m                  kubelet, pikubed-m1  Pulling image "busybox"
  Normal   Created    20m                  kubelet, pikubed-m1  Created container kadalu-provisioner
  Normal   Started    20m                  kubelet, pikubed-m1  Started container kadalu-provisioner
  Normal   Pulled     20m                  kubelet, pikubed-m1  Successfully pulled image "busybox"
  Normal   Created    20m                  kubelet, pikubed-m1  Created container kadalu-logging
  Normal   Started    20m                  kubelet, pikubed-m1  Started container kadalu-logging
  Normal   Pulled     20m (x2 over 22m)    kubelet, pikubed-m1  Container image "quay.io/k8scsi/csi-provisioner:v1.0.1" already present on machine
  Normal   Created    20m (x2 over 22m)    kubelet, pikubed-m1  Created container csi-provisioner
  Normal   Pulled     20m (x2 over 22m)    kubelet, pikubed-m1  Container image "quay.io/k8scsi/csi-attacher:v1.0.1" already present on machine
  Normal   Started    20m (x2 over 22m)    kubelet, pikubed-m1  Started container csi-provisioner
  Normal   Created    20m (x2 over 22m)    kubelet, pikubed-m1  Created container csi-attacher
  Normal   Started    20m (x2 over 22m)    kubelet, pikubed-m1  Started container csi-attacher
  Warning  BackOff    20m (x2 over 20m)    kubelet, pikubed-m1  Back-off restarting failed container
  Warning  BackOff    116s (x93 over 20m)  kubelet, pikubed-m1  Back-off restarting failed container
```

I'm new to Kubernetes and while I've learned a lot just initially toying with k3s I'm not sure where to get more useful logs for debugging.

**Comment by aravindavk** [comment]
Thanks for reporting, please share the logs from the failed pods/containers so that that helps us to root cause the issue.

**Comment by FlexibleToast** [comment]
```
k logs csi-provisioner-0 -c csi-provisioner -n kadalu
standard_init_linux.go:211: exec user process caused "exec format error"
```
Looks like it pulled the wrong architecture image

**Comment by iamenr0s** [comment]
you are right, it's wrong arch. if it should be useful I've just compiled some containers required to deploy kadalu in arm64 architecture.
[csi-node-driver-registrar](https://quay.io/repository/enr0s/csi-node-driver-registrar)
[csi-resizer](https://quay.io/repository/enr0s/csi-resizer)
[csi-provisioner](https://quay.io/repository/enr0s/csi-provisioner)
[csi-snapshotter](https://quay.io/repository/enr0s/csi-snapshotter)
[csi-attacher](https://quay.io/repository/enr0s/csi-attacher)
you need only to update the image reference in yaml file.

**Comment by FlexibleToast** [comment]
The only image I see referenced in the yaml is the kadalu operator. From my understanding the operator is then tasked with pulling and placing all the images. How do I then edit the image being pulled for that pod? Is it as simple as a kubectl edit podname -n kadalu? Shouldn't the operator be able to detect the architecture and pull the correct images?

**Comment by iamenr0s** [comment]
When I did my test I deployed all images on my own repo, but you should be able to modify your deployment images using the kubectl command:
`kubectl get deployment -nkadalu -o wide`
than 
`kubectl edit -nkadalu deployment [kadalu_deploy]`

**Comment by aravindavk** [comment]
Thanks, @enr0s for providing container images for Arm, We will accommodate soon within the repo.

**Comment by FlexibleToast** [comment]
`kubectl get deployment -n kadalu -o wide`
Only shows the deployment for the operator and if I edit it, I don't see any mention of the csi-provisioner at all.

**Comment by aravindavk** [comment]
csi pods are deployed as `DaemonSet` and `StatefulSet`. Please try the workaround by getting `kubectl get DaemonSet -n kadalu -o wide` and `kubectl get StatefulSet -n kadalu -o wide`

**Comment by amarts** [comment]
@FlexibleToast @enr0s the PR #274 should fix this for now.

I used @enr0s's images for arm for now. And note the change in tag to `master-arm`. The tag is pushed as part of the build test already, so one can verify if it is actually working!

**Comment by FlexibleToast** [comment]
I used the mentioned buildx-test branch's manifest to deploy kadalu to my pis. After some confusion about creating storage pools I created 4 different pools, (4 nodes, 2 devices each, replica2). I tried creating a test PVC and the PV isn't being created. I tried deleting the operator pod, because I had to do that to get it to deploy the storage servers... Still no dice. Here is the test-pv.yaml I used:

```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pv1
spec:
  storageClassName: kadalu.replica2
  accessModes:
    - ReadWriteOnce # You can also provide 'ReadWriteMany' here
  resources:
    requests:
      storage: 1Gi
```

Edit: After it just running for hours I looked and saw a lot of restarts and just outright failures. So, I've included logs earlier from the operator and I'm now adding logs from the glusterfsd container from a failed pod along with the shd container. I didn't see anything interesting in the quotad logs.

```
NAME                        READY   STATUS             RESTARTS   AGE
csi-nodeplugin-2rmz9        3/3     Running            6          7h22m
csi-nodeplugin-ln568        3/3     Running            6          7h22m
csi-nodeplugin-mt8ql        3/3     Running            12         7h22m
csi-nodeplugin-n5428        3/3     Running            6          7h22m
csi-provisioner-0           4/4     Running            8          7h22m
operator-77b8f46bd6-j9xm5   1/1     Running            3          4h53m
server-appdata-00b-0-0      2/3     CrashLoopBackOff   57         5h19m
server-appdata-00b-1-0      2/3     Running            57         5h19m
server-appdata-02a-0-0      2/3     CrashLoopBackOff   57         5h51m
server-appdata-02a-1-0      3/3     Running            3          5h51m
server-appdata-10a-0-0      2/3     Running            62         5h19m
server-appdata-10a-1-0      2/3     CrashLoopBackOff   55         5h19m
server-appdata-12b-0-0      2/3     Running            60         5h19m
server-appdata-12b-1-0      3/3     Running            3          5h19m
```

[logs-from-shd-in-server-appdata-00b-1-0.txt](https://github.com/kadalu/kadalu/files/4882093/logs-from-shd-in-server-appdata-00b-1-0.txt)
[logs-from-glusterfsd-in-server-appdata-00b-1-0.txt](https://github.com/kadalu/kadalu/files/4882094/logs-from-glusterfsd-in-server-appdata-00b-1-0.txt)
[logs-from-kadalu-operator-in-operator-77b8f46bd6-j9xm5.txt](https://github.com/kadalu/kadalu/files/4881293/logs-from-kadalu-operator-in-operator-77b8f46bd6-j9xm5.txt)

**Comment by FlexibleToast** [comment]
As asked in Slack, here are the logs for the csi-provisionor

[logs-from-csi-provisioner-in-csi-provisioner-0.txt](https://github.com/kadalu/kadalu/files/4885140/logs-from-csi-provisioner-in-csi-provisioner-0.txt)

**Comment by amarts** [comment]
@enr0s is there a version compatibility issue in CSI drivers? looks like csi-provisioner is not able to connect properly!

**Comment by amarts** [comment]
@FlexibleToast Sorry, had missed checking glusterfsd logs. Only checked operator logs earlier. Issue seems to be below:

```
[2020-07-07 02:04:01.532789] E [MSGID: 113063] [posix-common.c:660:posix_init] 0-appdata-00b-posix: mismatching volume-id (bb3d005e-bfca-11ea-8061-46ae8a3be135) received. already is a part of volume b5e4f74c-bfca-11ea-8061-46ae8a3be135  
[2020-07-07 02:04:01.533506] E [MSGID: 101019] [xlator.c:626:xlator_init] 0-appdata-00b-posix: Initialization of volume 'appdata-00b-posix' failed, review your volfile again 
```

Is this a fresh disk you want to provide for kadalu? Then mostly the volume-id was created in previous attempt. You need to delete the xattr.

`attr -r trusted.glusterfs.volume-id /mount/path`

**Comment by FlexibleToast** [comment]
Maybe I'm at a fundamental misunderstanding again. I wiped the drives and passed them as devices /dev/sda. Was this the correct way to do it? Was I supposed to partition, mount, then pass the mount path?

**Comment by aravindavk** [comment]
> Maybe I'm at a fundamental misunderstanding again. I wiped the drives and passed them as devices /dev/sda. Was this the correct way to do it? Was I supposed to partition, mount, then pass the mount path?

This is correct. `device` accepts raw device and `path` accepts mount path in Storage config file. You can also use CLI to add storage. `sudo pip3 install kubectl-kadalu`

**Comment by amarts** [comment]
ok... as a work around can you change the name of the storage pool when you passed the info? I suspect some stale data pending in configmap is causing the new server processes to not start. (surely a bug on our end),
@FlexibleToast your way of clean restart is valid.
i suspect that because server log is way earlier than the operator log/csi log
(or it may be also an issue with localtime/utc time of gluster) But trying changing of storage pool name once would help to validate our observation

**Comment by volkerCodeschoepfer** [comment]
I experience the same issue which is described here.

```
# kubectl create -f https://raw.githubusercontent.com/kadalu/kadalu/master/manifests/kadalu-operator-master.yaml
namespace/kadalu created
serviceaccount/kadalu-operator created
serviceaccount/kadalu-csi-nodeplugin created
serviceaccount/kadalu-csi-provisioner created
serviceaccount/kadalu-server-sa created
customresourcedefinition.apiextensions.k8s.io/kadalustorages.kadalu-operator.storage created
clusterrole.rbac.authorization.k8s.io/kadalu-operator created
clusterrolebinding.rbac.authorization.k8s.io/kadalu-operator created
deployment.apps/operator created
```

```
kadalu        operator-5b69d749d6-njslk                1/1     Running            0          21s   10.42.3.8    glupi3   <none>           <none>
kadalu        kadalu-csi-nodeplugin-ls5gm              3/3     Running            0          14s   10.42.4.14   glupi4   <none>           <none>
kadalu        kadalu-csi-nodeplugin-rsfnl              3/3     Running            0          14s   10.42.2.12   glupi2   <none>           <none>
kadalu        kadalu-csi-nodeplugin-htdzq              3/3     Running            0          14s   10.42.0.12   glupi0   <none>           <none>
kadalu        kadalu-csi-nodeplugin-d258j              3/3     Running            0          14s   10.42.1.7    glupi1   <none>           <none>
kadalu        kadalu-csi-nodeplugin-dnwb8              3/3     Running            0          14s   10.42.3.9    glupi3   <none>           <none>
kadalu        kadalu-csi-provisioner-0                 3/4     CrashLoopBackOff   1          14s   10.42.2.13   glupi2   <none>           <none>
kadalu        kadalu-csi-provisioner-0                 3/4     Error              2          26s   10.42.2.13   glupi2   <none>           <none>
```

```
# kubectl logs kadalu-csi-provisioner-0 csi-provisioner -n kadalu
standard_init_linux.go:211: exec user process caused "exec format error"
```

Up to fix #274 this should be solved. But this seems not be the case. Did I overlook something? I am on Raspberry PI 4 / aarch64:

`Linux glupi0 5.4.0-1015-raspi #15-Ubuntu SMP Fri Jul 10 05:34:24 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux`

**Comment by amarts** [comment]
Interesting... You used the correct tag. Will check what changed..

**Comment by volkerCodeschoepfer** [comment]
According to the patch #274 I should refer to 

`https://raw.githubusercontent.com/kadalu/kadalu/master/manifests/kadalu-operator-master-arm.yaml`

instead of 

`https://raw.githubusercontent.com/kadalu/kadalu/master/manifests/kadalu-operator-master.yaml`

but I cannot find it in the master tree.

**Comment by amarts** [comment]
That got removed in the latest commit as we fixed the buildx issue with using a multi-arch based csi images, instead of x86_64 one previously used (ref: #262 )

The fix is in picking right kubectl image in `operator/Dockerfile`.

**Comment by volkerCodeschoepfer** [comment]
ok, both the daemonset as well as the statefullset point to the following images:

```
# kubectl get ds -n kadalu -o yaml |grep "image: [a-z]"
          image: docker.io/raspbernetes/csi-node-driver-registrar:latest
          image: docker.io/kadalu/kadalu-csi:master
          image: busybox
```
```
# kubectl get sts -n kadalu -o yaml |grep "image: [a-z]"
          image: docker.io/raspbernetes/csi-external-provisioner:latest
          image: docker.io/raspbernetes/csi-external-attacher:latest
          image: docker.io/kadalu/kadalu-csi:master
          image: busybox
```

I assume that kadalu-csi ist wrong. Can you confirm?

**Comment by amarts** [comment]
Yes, the images look fine, and as per docker tags, all of them support linux/arm64 platform.

**Comment by volkerCodeschoepfer** [comment]
I was able to track it down: The images from raspbernetes are wrong:

https://github.com/raspbernetes/multi-arch-images/issues/144#issuecomment-685782568

**Comment by amarts** [comment]
@d7volker thanks for this. Was not aware of this.

**Comment by volkerCodeschoepfer** [comment]
The bug mentioned in my comment before, is fixed. But a another does exist with the csi-attacher.
I guess it is the same issue, there.

**Comment by volkerCodeschoepfer** [comment]
The problem with the csi-attacher is solved:

https://github.com/raspbernetes/multi-arch-images/issues/166

**Comment by volkerCodeschoepfer** [comment]
One outstanding bug is with csi-node-driver-registrar. I am going to open a bug report for it.
https://github.com/raspbernetes/multi-arch-images/issues/168

**Comment by jamesorlakin** [comment]
Hi folks, apologies for the images being wrong on the Raspbernetes collection for arm. The CSI build scripts have all been revamped in their recent major releases and they override GOARCH. I've updated our scripts to patch that out, otherwise you get weird behaviour where the arm64 Docker buildx environment creates an amd64 build. There's a schedule to automatically update the images for new releases and they got caught by this breaking behaviour.

As far as I know all of the images should now be fixed, but please raise any issues if they're not! The use of patching means the builds should outright fail if the build scripts are updated similarly in future. Cheers.

**Comment by amarts** [comment]
@jamesorlakin thanks for the updates!  Thanks @d7volker for following up.

Once we merge #312 we should have the issue fixed, and we can confirm if its working fine :+1:

**Comment by volkerCodeschoepfer** [comment]
@amarts: I know, you are waiting for #312 to be merged.
However I tested with the latest images, and I can say they are now working! :)

**Comment by amarts** [comment]
@FlexibleToast please try when you get a chance! Thanks. Will be closing this for now!
