### ISSUE TITLE
Lot of logs "Unverified HTTPS request is being made to host '10.43.0.1'"

### ISSUE THREAD

**Issue by papanito** [kadalu/kadalu#272]
I've updated kadalu to `0.7.0` and now I see that I `kadalu-operator` regularly issues the following warning

```bash
/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py:986: InsecureRequestWarning: Unverified HTTPS request is being made to host '10.43.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warning
```
Can this be suppressed in the log? or fixed?

The regularity of the warning generates an immense load of data which can be a problem in case you have a log management tool which you pay by size. In my case I already got 4.3GB of data in just 3 hours :open_mouth: 

![Screenshot from 2020-06-10 06-37-38](https://user-images.githubusercontent.com/15034009/84227638-37e1d080-aae5-11ea-9dad-155a19227828.png)

**Comment by papanito** [comment]
@aravindavk is there maybe a way to disable the log temporarily?

**Comment by aravindavk** [comment]
Unfortunately, the `DEBUG` mode is enabled in all the components. I will look into the issue to reduce the logs.

**Comment by tuunit** [comment]
@aravindavk are there any news about this issue? We do have this problem as well. Over the weekend it produced 45GB of logs and flooded our filesystem. Do you have any idea, what kind of request is causing the issue and how can we prevent it?

**Comment by tuunit** [comment]
@aravindavk are you aware of any possible workaround or fix?

**Comment by aravindavk** [comment]
> @aravindavk are there any news about this issue? We do have this problem as well. Over the weekend it produced 45GB of logs and flooded our filesystem. Do you have any idea, what kind of request is causing the issue and how can we prevent it?

That's bad. I will look into this. Is the above-mentioned log causing this issue or other log messages as well?

**Comment by aravindavk** [comment]
I will work on properly fixing these issues. As a workaround try to set env variable for the Pod using `kubectl edit ` command.

```
PYTHONWARNINGS="ignore:Unverified HTTPS request"
```

https://stackoverflow.com/questions/27981545/suppress-insecurerequestwarning-unverified-https-request-is-being-made-in-pytho

**Comment by tuunit** [comment]
> > @aravindavk are there any news about this issue? We do have this problem as well. Over the weekend it produced 45GB of logs and flooded our filesystem. Do you have any idea, what kind of request is causing the issue and how can we prevent it?
> 
> That's bad. I will look into this. Is the above-mentioned log causing this issue or other log messages as well?

Only the mentioned log message

**Comment by tuunit** [comment]
> I will work on properly fixing these issues. As a workaround try to set env variable for the Pod using `kubectl edit ` command.
> 
> ```
> PYTHONWARNINGS="ignore:Unverified HTTPS request"
> ```
> 
> https://stackoverflow.com/questions/27981545/suppress-insecurerequestwarning-unverified-https-request-is-being-made-in-pytho

Thanks a lot, that seems to work!

**Comment by papanito** [comment]
Still valid!?

**Comment by papanito** [comment]
Thanks!!
