### ISSUE TITLE
Kadalu without Python?

### ISSUE THREAD

**Issue by YamacorePriv** [kadalu/kadalu#290]
I wanted to use Kadalu on my K3s Cluster which runs on K3OS n sadly got no python or pip, i found some documentation that there is a binary but i cant find any link or anything. Maybe i misinterpreted something since my main language isnt eng, otherwise i would love to see a full yaml guide/doc

**Comment by amarts** [comment]
You can use `kubectl create -f file` to get the operator started.

Something like `kubectl create -f https://github.com/kadalu/kadalu/blob/master/manifests/kadalu-operator-master.yaml` (more options @ https://github.com/kadalu/kadalu/tree/master/manifests)

After this configure your storage with one of the below config, which is defined here:  https://github.com/kadalu/kadalu/tree/master/examples

Again do `kubectl create -f $file` 

After this you are ready to consume PVC from kadalu, like https://kadalu.io/docs/k8s-storage/latest/csi-to-claim-persistent-volumes

**Comment by aravindavk** [comment]
Thanks for reporting the issue.

Kadalu Kubectl plugin is completely optional. Without this tool,

Install the Kadalu Operator using,

```
kubectl create -f https://raw.githubusercontent.com/kadalu/kadalu/master/manifests/kadalu-operator-master.yaml
```

More yaml file available here: https://github.com/kadalu/kadalu/tree/master/manifests

and then Create Storage yaml file as required. Refer example yaml files here. https://github.com/kadalu/kadalu/tree/master/examples

Kadalu Kubectl plugin uses Python. In the upcoming release, you can use as single file if only Python is available(pip is not required).

**Comment by YamacorePriv** [comment]
Thanks for the fast replys, got it nearly working, the last question would be if its possible to use a folder instead of device like instead of /dev/sda /otp or /home or anything like that? Else i will just add a Partition for it.

Atm when i use a folder instead of /dev/sda i get Pending on all claims

**Comment by amarts** [comment]
Yes, check this:

https://github.com/kadalu/kadalu/blob/master/examples/sample-storage.yaml

Instead of `device: /dev/sda` give `path: /opt/export`, we recommend it to be xfs for now, as the quota setting is with xfs.

**Comment by YamacorePriv** [comment]
all i get when i try to set a simple 2 node replica is a pending pvc:
EDIT some info:
os: k3os running with k3s
gave it /otp after checking if its persistant and ext4 (cant change that on k3os)


`Name:          pv1
Namespace:     default
StorageClass:  kadalu.replica1
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: kadalu
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    pod1
Events:
  Type     Reason                Age                   From                                                                  Message
  ----     ------                ----                  ----                                                                  -------
  Normal   ExternalProvisioning  6m26s (x43 over 16m)  persistentvolume-controller                                           waiting for a volume to be created, either by external provisioner "kadalu" or manually created by system administrator
  Warning  ProvisioningFailed    82s (x5 over 13m)     kadalu_kadalu-csi-provisioner-0_27e532e2-4bbb-4ada-b3d8-3baa47cbf4ea  failed to provision volume with StorageClass "kadalu.replica1": rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Normal   Provisioning          66s (x6 over 16m)     kadalu_kadalu-csi-provisioner-0_27e532e2-4bbb-4ada-b3d8-3baa47cbf4ea  External provisioner is provisioning volume for claim "default/pv1"
  Normal   ExternalProvisioning  11s (x7 over 101s)    persistentvolume-controller                                           waiting for a volume to be created, either by external provisioner "kadalu" or manually created by system administrator
`

**Comment by amarts** [comment]
> StorageClass: kadalu.replica1

you are using replica1 here. If you are using replica2 (ie, 2 nodes, please give it as `kadalu.replica2`)

**Comment by YamacorePriv** [comment]
I get the same error, but thanks for the hint did an error there for sure, here is my step by step:
kubectl create -f https://raw.githubusercontent.com/kadalu/kadalu/master/manifests/kadalu-operator-master.yaml
kubectl get pod -n kadalu (check if all is fine)
kubectl create -f https://pastebin.com/raw/dLeYJudv (while /opt is on a ext4 formatted volume from k3os)
kubectl create -f https://pastebin.com/raw/CjZfYisZ
kubectl create -f https://raw.githubusercontent.com/kadalu/kadalu/master/examples/sample-app.yaml

Additional to the error above here from the pod:
`  Warning  FailedScheduling  <unknown>  default-scheduler  running "VolumeBinding" filter plugin for pod "pod1": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling  <unknown>  default-scheduler  persistentvolumeclaim "pv1" is being deleted
  Warning  FailedScheduling  <unknown>  default-scheduler  running "VolumeBinding" filter plugin for pod "pod1": pod has unbound immediate PersistentVolumeClaims
  Warning  FailedScheduling  <unknown>  default-scheduler  running "VolumeBinding" filter plugin for pod "pod1": pod has unbound immediate PersistentVolumeClaims
`

**Comment by FlexibleToast** [comment]
I'm using k3s on Raspberry Pis and Ubuntu Server 20.04. I found that my provisioner container sometimes hangs. After first deployment it hangs and if I give it something that will fail (like the replica1 error you had earlier) it will hang. If I delete the provisioner pod it gets recreated and starts working again. Not ideal, but it got things moving.

**Comment by amarts** [comment]
> I wanted to use Kadalu on my K3s Cluster which runs on K3OS n sadly got no python or pip, i found some documentation that there is a binary but i cant find any link or anything. Maybe i misinterpreted something since my main language isnt eng, otherwise i would love to see a full yaml guide/doc

Wrote the documentation here to use kadalu without python support..

* https://kadalu.io/docs/k8s-storage/devel/quick-start-yaml
* https://github.com/kadalu/kadalu/blob/devel/doc/quick-start-yaml.md (this is the source)

Also with latest release (0.7.5 (or latest `arm` tag)), kubectl kadalu (the python part of it) is usable with operator's image itself... (#250 )

With that information will close the Issue (as that solves the description).

@FlexibleToast @Thalooka will look into the hang part separately.
