### ISSUE TITLE
Gluster command line freeze

### ISSUE THREAD

**Issue by couloum** [kadalu/kadalu#301]
Hi,

I would like to use gluster command line in `server-storage-pool-*` pods to get information about glusterfs status. But every time I enter a command, it freezes. I have to do `ctrl+c` to 

```
$ kubectl -n kadalu exec -ti server-storage-pool-0-0 gluster
Defaulting container name to glusterfsd.
Use 'kubectl describe pod/server-storage-pool-0-0 -n kadalu' to see all of the containers in this pod.
Welcome to gluster prompt, type 'help' to see the available commands.
gluster> peer status
^Ccommand terminated with exit code 130
```

Is there something to do to be able to use gluster command?

Thanks

**Comment by amarts** [comment]
> Is there something to do to be able to use gluster command?

What do you want to do with gluster command? Kadalu operator + CSI are the management layer for glusterfs in this case. There is no gluster CLI, not glusterd running. 

If the pod is running on port 24007, then the service is all up and running.

For self-heal monitoring and all that, we will be providing a `kubectl kadalu monitor` command. Happy to hear what are the metrics / status you were thinking of

**Comment by couloum** [comment]
We use the gluster command to check status of all volumes, using a home-developped monitoring script:
1) Are all peer available?
2) Are all bricks online?
3) Are all pid running?
4) Is there any heal events on bricks

We also use the gluster command when we have issues on volume, like after a suddent crash of a node, we sometime need to perform some healing operation manually.

How should we do that with Kadalu?

Thanks

**Comment by aravindavk** [comment]
Thanks for the inputs.

> We use the gluster command to check status of all volumes, using a home-developped monitoring script:

> Are all peer available?

Clustering is delegated to K8s, no separate Cluster maintained for Kadalu.

> Are all bricks online?

Status of Bricks == `kubectl get pods -n kadalu | grep "server-"`   - If all are running then that means all are online.

> Are all pid running?

Same Pod status

> Is there any heal events on bricks

Heal commands are yet to be implemented. 

> We also use the gluster command when we have issues on volume, like after a suddent crash of a node, we sometime need to > perform some healing operation manually.

> How should we do that with Kadalu?
> Thanks

Also upcoming release will have a new subcommand `kubectl kadalu storage-list`. You can refer the sample output here https://github.com/kadalu/kadalu/pull/280#issuecomment-662560116

**Comment by couloum** [comment]
Ok, thanks for the information. I better understand the philosophy.
