### ISSUE TITLE
Use fixed versions of third-party docker images

### ISSUE THREAD

**Issue by robojones** [kadalu/kadalu#311]
I have noticed that we are using the `:latest` tag with third-party images. I suggest that going forward we select specific versions of the images. This will make Kadalu more reliable and easier to debug when there are breaking changes in those images.

Here's a list of the images:
- raspbernetes/csi-node-driver-registrar
- raspbernetes/csi-external-provisioner
- raspbernetes/csi-external-attacher

Using the `:latest` tag can cause issues which are hard to track down.

An example:

Let's say I installed Kadalu 30 days ago, my cluster would run version `v1.3.0` of the `raspbernetes/csi-node-driver-registrar` image (which was tagged `:latest` at that time).
Say I reboot one of my nodes today. When the node comes back online, Kubernetes recreates the `kadalu-csi-nodeplugin` pod. Following the default image pull policy of Kubernetes, it now pulls the `latest` version of the  `raspbernetes/csi-node-driver-registrar` image, which in this case is `v2.0.1` (which was released about 20 days ago and is now tagged `:latest`). `v2.0.1` is a new major version, introducing breaking changes. I now have a cluster where different nodes are running different major versions of the `csi-node-driver-registrar`. And there is no way for me to know that because there is no indication of it anywhere.

This could easily be avoided by using fixed versions of the third-party images.

**Comment by aravindavk** [comment]
Very good points. Thanks @robojones
