### ISSUE TITLE
 DELETED handle called, but not implemented when KadaluStorage is deleted.

### ISSUE THREAD

**Issue by hetii** [kadalu/kadalu#326]
Hello.
I back to this project after few months, to give it chance again, but again it seams it's not easy to use it as I expect :(
This time I deploy operator from file https://raw.githubusercontent.com/kadalu/kadalu/0.7.1/manifests/kadalu-operator-rke.yaml as I don't like to play with additional kubectl plugins and imho there are plenty scenarios (CI/CD) when this should be the optional, but the main way should based on yamls or helm chart (just my personal opinion).

But back to the topic. 
I deploy first file from: https://github.com/kadalu/kadalu/blob/0.7.1/examples/sample-storage-file-device.yaml
and when it fails on:
`ERROR [glusterfsd - 107:create_and_mount_brick] - Failed to create file system	 fstype=xfs device=/brickdev/userfiles`
I decide to remove it and then in operator logs I see:
`[2020-10-27 09:56:03,669] WARNING [main - 399:handle_deleted] - DELETED handle called, but not implemented`
finally the pod `server-storage-pool-1-0-0` is not removed.

Then when I apply again this storage pool, operator show:
`Ignoring already deployed server statefulsets	 storagename=storage-pool-1`

So general I would like to see some directory when I can apply and entire demo application will be spawn and running, because now it seams that this project is still in alpha stage then something that can be used in real world.

BTW also In the past there was idea regarding reusing provider pv/pvc that is in ReadWriteOnce mode and transform it to ReadWriteMany but so far I don't see such examples.

**Comment by amarts** [comment]
Hi @hetii! Welcome back.

Sorry about your experience. Looks like we should make sure our documentation covers details of using yamls directly with `kubectl` command itself, instead of `kubectl kadalu` too. Will fix that soon.

> So general I would like to see some direcotry when I can apply and entire demo application will be spawn and running, because now it seams that this project is still in alpha stage then something that can be used in real world.

Yes, valid point. We run the things for our tests to accept the PR, but providing them in a DIR is a good idea. Will work on that.
