### ISSUE TITLE
Move repo to its own separate org

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#33]
Considering this project has many potential to growth, and more user participations in future, it would be great to move the repo to its own org, so one can collaborate better.

If it is OK for you, please consider moving the repo to https://github.com/kadalu 

That way, project can have its own docs, webpage, and multiple repos.

**Comment by amarts** [comment]
'Forked' the repo to kadalu org, and made you an admin too. Let me know if that works :-) 

You can close the issue.

**Comment by aravindavk** [comment]
I think we can move the repo itself to kadalu org.

**Comment by aravindavk** [comment]
Moved both aravindavk/kadalu and aravindavk/kadalu-cookbook under kadalu org.
