### ISSUE TITLE
replica3 recovery after 1 device unavailable

### ISSUE THREAD

**Issue by galp** [kadalu/kadalu#330]
Hello,
I have been running happily kadalu on a small arm64 cluster and I like the project very much. 
 
However now I have an issue which I think should be documented a bit better

I have a replica3 storage pool on my cluster. One of the 3 nodes part of the pool is gone and the storage device on it will move to a new node.

First of all it seems that my  pods cannot work with two out of three replicas. That shouldnt be the case right?
My pods are stuck  creating with errors like this : 

`MountVolume.SetUp failed for volume "pvc-5bcb3600-d993-4e76-9b47-ca04ba70d6bd" : rpc error: code = Unknown desc = Exception calling application: [32]  mount: /var/lib/kubelet/pods/3cbe0ba9-059e-48cf-b09a-8a106805cc4a/volumes/kubernetes.io~csi/pvc-5bcb3600-d993-4e76-9b47-ca04ba70d6bd/mount: mount(2) system call failed: Transport endpoint is not connected.`
There is a possibility that the replicaset was already working with 2/3 replicas but I never noticed and now losing another killed it. 
Can you please explain a bit or perhaps point me to to the right place to understand how this works?

Also I would like to to know how to get the 3rd replica rebuild on a new node. What I am going to try in a minute when my new node is ready is to edit the relevant storage like 

` kubectl edit   KadaluStorage flash32 `
and change the node in there
Is this the way to recover?

Thank you very much.

**Comment by amarts** [comment]
Good to hear that kadalu is working for you on arm64.

About replica3, it should technically work when only 2 nodes are available. Is there any hint in `csi-provisioner` &  `csi-nodeplugin` logs? (`-nkadalu`)

We will get back to you on the right way to edit the config (to make changes to volume).

**Comment by galp** [comment]
Ok good. I think It might be beyond saving by now but it would be great to know how to recover in such cases.

**Comment by amarts** [comment]
Ok, we now (version 0.7.5) have support for `handle_modified()` (ie, an option to change the storage config). Please test the behavior, and let us know if that is good enough.

Will close the issue for now, re-open if there are concerns.

**Comment by amoravek** [comment]
I have the same problem on with kadalu 1.2.0 - it seems that every time i need to drain k8s node running the *first* replica, the pods using kadalu storage pvc remain in Terminating state forever. Some pods drained ok, but fail to initialize and log the following events:

` 
  Type     Reason       Age                   From               Message                                                                                                                                            
  ----     ------       ----                  ----               -------                                                                                                                                            
  Normal   Scheduled    30m                   default-scheduler  Successfully assigned xxxxxxxxxx to xxxxxx.xxxxxx.xx                                                    
  Warning  FailedMount  3m35s (x17 over 30m)  kubelet            MountVolume.SetUp failed for volume "pvc-8f8948d7-3cc3-448a-944c-3d117aebf219" : rpc error: code = Unknown desc = Exception calling application: lo
cal variable 'sock' referenced before assignment                                                                                                                                                                    
  Warning  FailedMount  3m23s (x4 over 26m)   kubelet            Unable to attach or mount volumes: unmounted volumes=[xxxxxxxxx], unattached volumes=[kube-api-access-tr26g xxxxxxxxx[]: timed out waiting for the condition                                                                                                                                            
  Warning  FailedMount  68s (x9 over 28m)     kubelet            Unable to attach or mount volumes: unmounted volumes=[xxxxxxxxxxx], unattached volumes=[xxxxxxxxxxx kube-api-access-tr26g[]: timed out waiting for the condition  
`
and this was logged by the csi-nodeplugin on the drained node:

kadalu-nodeplugin [2023-12-10 16:40:17,389] ERROR [_server - 508:_call_behavior] - Exception calling application: local variable 'sock' referenced before assignment                                                 
kadalu-nodeplugin Traceback (most recent call last):                                                                                                                                                                 
kadalu-nodeplugin   File "/kadalu/lib/python3.10/site-packages/grpc/_server.py", line 494, in _call_behavior                                                                                                         
kadalu-nodeplugin     response_or_iterator = behavior(argument, context)                                                                                                                                             
kadalu-nodeplugin   File "/kadalu/nodeserver.py", line 88, in NodePublishVolume                                                                                                                                      
kadalu-nodeplugin     mount_glusterfs(volume, mntdir, True)                                                                                                                                                          
kadalu-nodeplugin   File "/kadalu/volumeutils.py", line 934, in mount_glusterfs                                                                                                                                      
kadalu-nodeplugin     if not is_server_pod_reachable(hosts, 24007, 20):                                                                                                                                              
kadalu-nodeplugin   File "/kadalu/kadalulib.py", line 106, in is_server_pod_reachable                                                                                                                                
kadalu-nodeplugin     sock.close()                                                                                                                                                                                   
kadalu-nodeplugin UnboundLocalError: local variable 'sock' referenced before assignment  

I was able to reproduce it every time on several different clusters. I thought that the cluster will be operational with 2 replicas, however it seems that it is not the case.
