### ISSUE TITLE
trouble getting external GlusterFS working with KaDalu

### ISSUE THREAD

**Issue by JSN-1** [kadalu/kadalu#332]
I am having trouble getting external GlusterFS working with KaDalu.

here is my gluster volume info.

```
volume Name: vol001
Type: Distribute
Volume ID: xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx
Status: Started
Snapshot Count: 0
Number of Bricks: 3
Transport-type: tcp
Bricks:
Brick1: gluster001:/gfs/volume
Brick2: gluster002:/gfs/volume
Brick3: gluster003:/gfs/volume
Options Reconfigured:
transport.address-family: inet
storage.fips-mode-rchecksum: on
nfs.disable: on
```

Both kubernetes and gluster is on the same local network and all hostnames have been added to /etc/hosts

i use latest https://raw.githubusercontent.com/kadalu/kadalu/devel/manifests/kadalu-operator-devel.yaml

Here is how i add KadaluStorage

```
kubectl kadalu storage-add gfs --type External --external gluster001:/vol001

apiVersion: "kadalu-operator.storage/v1alpha1"
kind: "KadaluStorage"
metadata:
  name: "gfs"
spec:
  type: "External"
  storage: []
  details:
    - gluster_host: "gluster001"
      gluster_volname: "vol001"
      gluster_options: "log-level=INFO"
```

i create my pvc like this.

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gfs
spec:
  storageClassName: kadalu.external.gfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
```

status of pvc is in pending.

```
NAME   STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS          AGE
gfs    Pending                                      kadalu.external.gfs   5m53s
```

in operator everything seems normal, but for csi-provisioner i get errors.

```
I1109 11:04:22.165656       1 controller.go:1317] provision "default/gfs" class "kadalu.external.gfs": started
I1109 11:04:22.165805       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"gfs", UID:"44b9e17f-2294-4b4e-801d-7788b6cb20d8", APIVersion:"v1", ResourceVersion:"1004465", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/gfs"
W1109 11:04:22.572458       1 controller.go:943] Retrying syncing claim "44b9e17f-2294-4b4e-801d-7788b6cb20d8", failure 6
E1109 11:04:22.572527       1 controller.go:966] error syncing claim "44b9e17f-2294-4b4e-801d-7788b6cb20d8": failed to provision volume with StorageClass "kadalu.external.gfs": rpc error: code = InvalidArgument desc = External Storage provided not valid
I1109 11:04:22.572547       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"gfs", UID:"44b9e17f-2294-4b4e-801d-7788b6cb20d8", APIVersion:"v1", ResourceVersion:"1004465", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "kadalu.external.gfs": rpc error: code = InvalidArgument desc = External Storage provided not valid
```

i have manually tested that my GlusterFS is able to mount on worker nodes, and it is.

I have tried all types of GlusterFS from Distribute to Replicated, and it's the same error i get, also i have tried to setup external DNS for glusterfs nodes.

I am able to reach the Internal / External IP from inside operator pod, also able to telnet to port 24007.
I am however only able to resolve external DNS, internal DNS is from /etc/hosts but that's not working inside operator pod. 

What am i doing wrong here ? Please help.

Issue has been created by agreement with a maintainer of KaDalu and GlusterFS.

**Comment by JSN-1** [comment]
i have also tried to use external DNS address for gluster001 and it gives the same error "External Storage provided not valid"

`kubectl kadalu storage-add gfs --type External --external gluster001.external.fqdn:/vol001`

also tried to use --external internal_ip:/vol001 & --external external_ip:/vol001.

**Comment by amarts** [comment]
at this point, this looks like the csi-provisioner is not able to mount the volume..  Are these the only logs available in csi-provisioner? Can you dump the logs of csi-provisioner from all containers ? would like to see kadalu container's logs.

**Comment by JSN-1** [comment]
i located the error, and it was indeed DNS, i have used hostnames gluster001, 002, 003 while creating glusterfs.

when i stopped / deleted glusterfs and created it again using internal ips it worked.

thanks for your help and sorry for stealing your time.
