### ISSUE TITLE
disk quota exceeded

### ISSUE THREAD

**Issue by galp** [kadalu/kadalu#336]
Hello, 

Running 0.7.2alpha1 arm, 
kubernetes version  1.19.3

I created some new  storage :  
```
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: ssd-storage
spec:
  storage:
  - device: /dev/disk/by-id/scsi-SSamsung_SSD_860_QVO_1TB_641000107102
    node: node2
  type: Replica1
```

Not long after I started using it I get those in the logs of glusterfsd 

```
 [2020-11-10 22:36:20.818012] W [socket.c:4574:socket_init] 0-tcp.ssd-storage-server: disabling non-blocking IO
[2020-11-10 22:36:30.818669] W [socket.c:4574:socket_init] 0-tcp.ssd-storage-server: disabling non-blocking IO
[2020-11-10 22:36:07.503617] E [MSGID: 113069] [posix-entry-ops.c:2126:posix_create] 0-ssd-storage-posix: open on /bricks/ssd-storage/data/brick/subvol/fb/ba/pvc-d6178372-a919-4329-9f0e-e192e5ef6cc3/app/db/906a34e69aec8c0d/overlayrecent/db/LOG failed [Disk quota exceeded]

```
```kubectl get pvc 
NAME                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
app-data            Bound    pvc-d6178372-a919-4329-9f0e-e192e5ef6cc3   700Mi      RWX            kadalu.replica1   6h47m

kubectl get pv
pvc-d6178372-a919-4329-9f0e-e192e5ef6cc3   700Mi               RWX            Delete           Bound    default/app-data        kadalu.replica1            6h50m
```
Any idea what this is?

Thanks

**Comment by amarts** [comment]
> [2020-11-10 22:36:07.503617] E [MSGID: 113069] [posix-entry-ops.c:2126:posix_create] 0-ssd-storage-posix: open on /bricks/ssd-storage/data/brick/subvol/fb/ba/pvc-d6178372-a919-4329-9f0e-e192e5ef6cc3/app/db/906a34e69aec8c0d/overlayrecent/db/LOG failed [Disk quota exceeded]

The above log says, it reached posix layer in glusterfs (the last entry), and it failed there to create the file with QUOTA exceeded error, which means, the backend filesystem itself is giving this error. Can you check device ` /dev/disk/by-id/scsi-SSamsung_SSD_860_QVO_1TB_641000107102` on `node2` and see what its config are?

**Comment by galp** [comment]
Hello, I understand that is a quota error on the filesystem but there shouldnt be any quota settings.  It is a brand new ssd all setup by kadalu as shown in my original post. Noo idea what config you are referring to. Can you advice what to check on node2?

thank you.

**Comment by amarts** [comment]
@aravindavk do you think quota setting would be screwed up due to endian issues in `arm`? Any specific xfs quota commands to be checked?

@galp Can you try : 
`xfs_quota -x -c 'report -h' /mount-point/` (and pv directory on disk) on node2 ?

**Comment by aravindavk** [comment]
> @aravindavk do you think quota setting would be screwed up due to endian issues in arm? Any specific xfs quota commands to be checked?

Will confirm tomorrow. I got the Raspberry pi device now for testing.

**Comment by galp** [comment]
@amarts 

the above command inside glusterfsd container
```
[root@server-ssd-storage-0-0 /]# xfs_quota -x -c 'report -h' /bricks/ssd-storage/data
Project quota on /bricks/ssd-storage/data (/dev/sda)
                        Blocks              
Project ID   Used   Soft   Hard Warn/Grace   
---------- --------------------------------- 
#0            40K      0      0  00 [------]
#1074695817   700M      0   700M  00 [------]
```

**Comment by amarts** [comment]
@galp the output looks valid. And what I understand now, the behavior in this case also is valid, because PV was created with 700MB space, and it is getting EDQUOT after 700MB is utilized.

Please create a PV with higher size and start consuming it.

> NOTE: we are yet to have resize support, and will see if we can have it soon, so you can expand the existing PV itself.

**Comment by galp** [comment]
That was own mistake. It should have been 700G not M, 

sorry about that. 
As for resizing, I will just wipe the disk and start from scratch now. Thanks again.
