### ISSUE TITLE
Provide details of 'headless' service choice and improve behavior by few changes

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#340]
In the cloud eco-system, there is a fee for transferring data between availability zones. I want CSI node plugin pods to prioritize Storage Pool nodes within the same availability zone to minimize costs. It is possible with the [Service Topology](https://kubernetes.io/docs/concepts/services-networking/service-topology/) feature gate.

The Service Topology may create the imbalance problem, so it is better to implement it as an `--enable-service-topology` flag for the `storage-add` command. To make these changes one must know the reason why developers used [headless service](https://github.com/kadalu/kadalu/blob/08a316f57be45c5924000e70c6b90dabd85130aa/templates/services.yaml.j2#L13) for the volume service.

ServiceTopology hardly relies on kube-proxy, which is not used in the case of headless services. Probably, to get the closest effect to the ServiceTopology, one needs to implement priorities with the same labels ("kubernetes.io/hostname", "topology.kubernetes.io/zone", "topology.kubernetes.io/region") in the code of CSI Provisioner. 

--
Suggestions and details credits: Volodymyr Chernetskyi

**Comment by amarts** [comment]
```
diff --git a/templates/services.yaml.j2 b/templates/services.yaml.j2
index ba5255d..fbdc0e7 100644
--- a/templates/services.yaml.j2
+++ b/templates/services.yaml.j2
@@ -20,3 +20,8 @@ spec:
       protocol: TCP
       port: 24007
       targetPort: 24007
+  topologyKeys:
+    - "kubernetes.io/hostname"
+    - "topology.kubernetes.io/zone"
+    - "topology.kubernetes.io/region"
+    - "*"
```

One of the suggestion is, it may not work with 'headless' logic (ie, `ClusterIP: None`). More to be done on this.

**Comment by chernetskyi** [comment]
To explain the reason why developers used Headless Service for the volume service

> StatefulSets currently require a Headless Service to be responsible for the network identity of the Pods. You are responsible for creating this Service. [Kuberenetes Documentation on StatefulSet](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/).

Therefore the Headless Service is chosen because the [server](https://github.com/kadalu/kadalu/blob/devel/templates/server.yaml.j2) is a StatefulSet.

Possible ways to implement the enhancement:

1. Wait for the ServiceTopology support of Headless Services.
2. Change the server's kind to Deployment and resolve the resulting issues.
3. Implement prioritization in the code of the CSI Provisioner.
