### ISSUE TITLE
stat.db cleanup xfs quotas

### ISSUE THREAD

**Issue by galp** [kadalu/kadalu#341]
xfs quotas do not get cleared after a pvc is deleted.  This becomes obvious when  try to make a new one and there might not be enough space to do so.
@amarts thinks it due to the info file not being cleaned as it should

My workaround : 
xfs_quota -x -c 'report -h' /bricks/ssd-storage/data/       # here i have the stale quota ids                                                                      
xfs_quota -x -c "off -up" /bricks/ssd-storage/data/          # disable quota                                                                          
xfs_quota -x -c "remove -p" /bricks/ssd-storage/data    # remove metadata
reboot node where disk is plugged in

If I can help with something  let  me know

**Comment by amarts** [comment]
this shouldn't happen IMO.

Tried multiple deletes, and the info and quota setting is not causing the issue... https://github.com/kadalu/kadalu/pull/342

Need to debug why this is happening for you. Noticed that even if quota is set, it can make use of 'thin' provisioning, so if there is enough 'space', it should continue to allow writes.

**Comment by amarts** [comment]
@galp when you get some cycles, can you see if the issue persists with `0.7.6` version too?

**Comment by galp** [comment]
Hello, I have updated to 0.7.7  but I wont be able to test as I am using the replica set currently.
Lets  close it and I  reopen in the future. 

Thanks for looking at my issue.
