### ISSUE TITLE
error: a container name must be specified

### ISSUE THREAD

**Issue by floek** [kadalu/kadalu#351]
Hi all,

I've installed a fresh minikube on macOS with VirtualBox and deployed kadalu 0.7.2 on it. Then I created a simple storage on a file, as described in your minikube doc. One storage pod is not starting with the following error:
error: a container name must be specified for pod server-storage-pool-1-0-0, choose one of: [glusterfsd quotad]

Here are my steps:
```
~> kubectl kadalu storage-add storage-pool-1 \
     --device minikube:/mnt/sda1/storage-pool-1.disk.img
The following nodes are available:
  minikube

Storage Yaml file for your reference:

apiVersion: "kadalu-operator.storage/v1alpha1"
kind: "KadaluStorage"
metadata:
  name: "storage-pool-1"
spec:
  type: "Replica1"
  storage:
    - node: "minikube"
      device: "/mnt/sda1/storage-pool-1.disk.img"

Is this correct?(Yes/No): Yes
Storage add request sent successfully
kadalustorage.kadalu-operator.storage/storage-pool-1 created

~> kubectl -n kadalu get pods
NAME                          READY   STATUS    RESTARTS   AGE
kadalu-csi-nodeplugin-gfq84   3/3     Running   0          15m
kadalu-csi-provisioner-0      4/4     Running   0          15m
operator-74c9fb55c4-xd8bk     1/1     Running   0          16m
server-storage-pool-1-0-0     1/2     Running   2          8m30s
~> kubectl -n kadalu logs server-storage-pool-1-0-0
error: a container name must be specified for pod server-storage-pool-1-0-0, choose one of: [glusterfsd quotad]
```

Any ideas?

Thanks,

Floek

**Comment by aravindavk** [comment]
Server pod contains multiple containers, Specify container name while running log command. For example,

```
kubectl -n kadalu logs -c glusterfsd server-storage-pool-1-0-0
```

or

```
kubectl -n kadalu logs --all-containers=true server-storage-pool-1-0-0 
```

**Comment by floek** [comment]
Sure:
```
~> kubectl -n kadalu logs -c glusterfsd server-storage-pool-1-0-0
+ pid=0
+ cmd=/usr/bin/python3
+ script=/kadalu/server.py
+ trap 'kill ${!}; term_handler' SIGTERM
+ pid=7
+ true
+ /usr/bin/python3 /kadalu/server.py
+ wait 8
+ tail -f /dev/null
[2020-11-28 16:19:35,773] ERROR [glusterfsd - 125:create_and_mount_brick] - Failed to mount export brick	 
fstype=xfs device=/brickdev/storage-pool-1.disk.img mountdir=/bricks/storage-pool-1/data error=[32]  
mount: bricks/storage-pool-1/data: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage 
or helper program, or other error.
```

**Comment by vatsa287** [comment]
@floek If you are trying kadalu for first time with minikube, could you try /extras/scripts/kadalu-sample-setup and send any feedbacks?
Sample args:  `$ sudo ./extras/scripts/kadalu-sample-setup --device-file-path=/mnt/disk1 --storage-value=150Mi` given that there is device file called disk1 in /mnt.

**Comment by floek** [comment]
Just to be sure, I should do the following (from scratch):
```bash
# create new Minikube vm
minikube start --memory=4096 --driver=virtualbox

# install kadalu
kubectl-kadalu install

# create image file /mnt/sda1/storage-pool-1.disk.img
minikube ssh
cd /mnt/sda1/
sudo truncate -s 5G storage-pool-1.disk.img
exit

# get sources:
git clone git@github.com:kadalu/kadalu.git
cd kadalu

# run script from macOS (not minikube):
./extras/scripts/kadalu-sample-setup.sh --device-file-path=/mnt/sda1/storage-pool-1.disk.img --storage-value=150Mi
```

Why so I need to run the script with sudo on macOS? This doesn't make that much sense for me.

**Comment by vatsa287** [comment]
Coming from a Ubuntu on VM user....
Alternatively I have tried by creating storage-device file in the OS itself and not ssh into minikube.
 `$ sudo truncate -s 4g /mnt/disk1` 

This script copies examples/yaml files to /tmp directory and deploys the configured files. Since /tmp is one of those directories which require special permissions [Sticky Bit] to make changes inside. It might throw an error 'Operation not permitted'

```bash
vatsa@vatsa-VirtualBox:~/kadalu/extras/scripts$ sudo ./kadalu-sample-setup.sh -d /mnt/disk1 -v 100Mi
[sudo] password for vatsa: 
namespace/kadalu created
serviceaccount/kadalu-operator created
serviceaccount/kadalu-csi-nodeplugin created
serviceaccount/kadalu-csi-provisioner created
serviceaccount/kadalu-server-sa created
customresourcedefinition.apiextensions.k8s.io/kadalustorages.kadalu-operator.storage created
clusterrole.rbac.authorization.k8s.io/pod-exec created
clusterrole.rbac.authorization.k8s.io/kadalu-operator created
clusterrolebinding.rbac.authorization.k8s.io/kadalu-operator created
deployment.apps/operator created
Hostname is minikube
kadalustorage.kadalu-operator.storage/storage-pool-1 created
persistentvolumeclaim/pv1 unchanged
pod/pod1 configured
15: Waiting for pods to come up...
All Kadalu pods in status: 'Running'
PVC pv1 in status: 'Bound'
POD pod1 in status: 'Completed'
Successful after 29 seconds
```
Check pvc and pod status
```bash
vatsa@vatsa-VirtualBox:~$ sudo kubectl get pods -nkadalu
NAME                          READY   STATUS    RESTARTS   AGE
kadalu-csi-nodeplugin-ttp6l   3/3     Running   0          6m18s
kadalu-csi-provisioner-0      4/4     Running   0          6m17s
operator-59f656cf56-zm2gw     1/1     Running   0          6m35s
server-storage-pool-1-0-0     2/2     Running   0          6m6s
vatsa@vatsa-VirtualBox:~$ sudo kubectl get pvc
NAME   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
pv1    Bound    pvc-8297cb4e-ef1e-41b3-be65-813601a7b50e   100Mi      RWO            kadalu.replica1   30m
vatsa@vatsa-VirtualBox:~$ sudo kubectl get pod
NAME   READY   STATUS      RESTARTS   AGE
pod1   0/1     Completed   0          30m
```

Debugging...
Server logs from `$ kubectl logs -nkadalu server-storage-pool-1-0-0 glusterfsd`
Provisioner logs from `$ kubectl logs -nkadalu kadalu-csi-provisioner --all-containers`
Operator logs from `$ kubectl logs -nkadalu operator-???` Get ??? from `$ kubectl get pods -nkadalu`

**Comment by floek** [comment]
I debugged a little bit. The problem is the mount option 'prjquota' in https://github.com/kadalu/kadalu/blob/edb1312bd3ab815350a36c98cea3afe859431245/server/glusterfsd.py#L117

When I change into the containers context and execute the mount on the command line, I get the same error. Without the mount option, I works:

```
[root@server-storage-pool-1-0-0 /]# mount -oprjquota /brickdev/storage-pool-1.disk.img  /bricks/storage-pool-1/data
mount: /bricks/storage-pool-1/data: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.
[root@server-storage-pool-1-0-0 /]# mount /brickdev/storage-pool-1.disk.img  /bricks/storage-pool-1/data
[root@server-storage-pool-1-0-0 /]# df -hT /bricks/storage-pool-1/data
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/loop0     xfs   5.0G   68M  5.0G   2% /bricks/storage-pool-1/data
[root@server-storage-pool-1-0-0 /]#
```

This seems to be a problem with the linux kernel in my minikube/virtualbox ISO image. According to 
https://github.com/kubernetes/minikube/blob/master/deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
the kernel option CONFIG_XFS_QUOTA is not set. I will create an issue there.

**Comment by amarts** [comment]
Got it... we run minikube on VM with `--vm-driver=none` option, so it works as `-oprjquota` is present in host VM.

Thanks for getting to the root of it.

**Comment by amarts** [comment]
Thanks to @floek for opening the issue in minikube, motivated me to send the first PR to minikube, which is now accepted and merged.

Next version of `minikube` will have this support, and kadalu should be natively supported on it from then onwards!

**Comment by amarts** [comment]
@floek minikube 1.17.0 is out, which has support for `-oprjquota` I will give it a try this week. Let us know if you are able to test this out on minikube VM.

**Comment by floek** [comment]
@amarts the error seems to be gone. Thanks for the minikube patch!
