### ISSUE TITLE
upgrade guide

### ISSUE THREAD

**Issue by schmitch** [kadalu/kadalu#352]
since kadalu is a storage platform it should have a upgrade guide, especially to not loose data.
even if it is just `kubectl kadalu upgrade` or upgrading deployment versions.
I mean what nobody wants is loosing data ;-)

Especially with changes that might be disruptive like: #305 i.e. an existing cluster might not upgrade the same the newer clusters.

**Comment by amarts** [comment]
#242 #213 and #106 were opened with similar points.

**Comment by amarts** [comment]
@schmitch adding a comment here for your reference. There is still more work pending to handle replica2/replica3 type of volumes.

With the latest version `0.7.6`, to upgrade all storage pods, along with operator, we just have to pass the latest operator yaml file from one of latest releases to `kubectl apply -f`. That should automatically pick the newer version for CSI, Storage pods, and also the operator pods.

**Comment by schmitch** [comment]
I will try it out in the next few weeks. Well we only use replica3 volumes, does this also work? or what exactly does mean "more work pending"?

**Comment by amarts** [comment]
ok, for replica3 volume we need to do a 'rolling' upgrade. That is the work pending. Ie, the operator should pick the first storage node, upgrade it, and keep watching on heal pending, and once its 0, upgrade second, and watch for heal pending, and once its 0, proceed with node3. 

If there is no I/O during upgrade, then the current method of upgrading without checking for heal count would work without any issues.

**Comment by attrib** [comment]
Tried to upgrade from 0.8.3 to 0.8.4, but `kubectl kadalu install` said `Kadalu operator already installed`

I believe in https://github.com/kadalu/kadalu/blame/devel/cli/kubectl_kadalu/install.py#L55 is a check missing, which version is installed, otherwise it will never get to the `kubectl apply -f` mentioned in https://github.com/kadalu/kadalu/issues/352#issuecomment-762647907
