### ISSUE TITLE
Question: Howto create a backup of the kadalu data?

### ISSUE THREAD

**Issue by floek** [kadalu/kadalu#353]
Hi kadalu team, 

what is the best practice to create a backup of the kadalu data?
Write a script to tar the data in kubernetes?
Mount the glusterfs outside kubernetes?

I've found nothing relevant in the repo/docu.

Thank you for your help.

Floek

**Comment by amarts** [comment]
Right now, we don't have 'snapshot' support, so your volume may be live when you are backing up (unless you have a mechanism to stop I/O from application externally). If that is done, any of the method (ie, tar and copy out, or mount and do a `cp`) would work.

Would be great if you let us know what is your thoughts, and contribute a blog :-)

**Comment by floek** [comment]
Okay, I think I'll try to mount the Gluster on one of the hosts. I'll keep you informed.

**Comment by floek** [comment]
My current strategy is to create the Gluster filesystem myself on the worker nodes and use it as an external storage in kadalu. Therefore, I can mount the filesystem outside kubernetes and create a backup.

**Comment by mbu147** [comment]
Hi, is there an update on snapshot support for kadalu? Is it on the roadmap?
How you guys make backup currently?

**Comment by timbastin** [comment]
I am really interested in this as well. What is the best practice to do a backup, if there is none, switch to stop application I/O?

**Comment by shaky1024** [comment]
I am really interested in this as well. What is the best practice to do a backup, if there is none, switch to stop application I/O?
