### ISSUE TITLE
RFE: add 'heal info' command to kubectl kadalu

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#361]
With the[ recent patch](https://github.com/gluster/glusterfs/commit/dac553ce97bac23477109180b3c57280aa688d0d) to `glfsheal` command of glusterfs, one can use it without management layer, and we can now consume this with the volfile inside the operator. That way, one of the major confusions, and ask of users related to gluster cli for checking heal status would go away.

Will add more info in comments later!

**Comment by aravindavk** [comment]
@amarts is this fixed with https://github.com/kadalu/kadalu/pull/433 or anything pending?

**Comment by amarts** [comment]
All good here! with 0.8.1 itself this is fixed.
