### ISSUE TITLE
RFE: Add devices by uuid

### ISSUE THREAD

**Issue by FlexibleToast** [kadalu/kadalu#362]
Currently kadalu accepts a device by path or a mountpoint. If someone wants to have Kadalu use a device by its uuid, they first have to create an /etc/fstab mount using the uuid and pass that mount to Kadalu. It would be nice to have Kadalu be able to directly accept and handle the uuid when creating a storage pool.

**Comment by leelavg** [comment]
@FlexibleToast Kadalu doesn't add entries to fstab. 

If all you want is `device` to accept `disk` or `uuid` that can be done with relative ease if `blkid` is available on host.

Can you pls confirm your use case once?

**Comment by FlexibleToast** [comment]
I don't understand your question. From my understanding when adding storage to a pool, kadalu currently accepts either a device such as
```
kubectl kadalu storage-add storage-pool-1 \
    --device kube1:/dev/vdc
```

Or a mountpoint such as
```
kubectl kadalu storage-add storage-pool-1 \
    --path kube1:/some/mount
```

You can't specify a UUID directly. Using UUID is preferred because it will not change after a reboot. Currently this can be done by specifying the UUID to be mounted at a mount point in the fstab of the host, then point kadalu to that mountpoint. However, it would be nice to give kadalu that UUID directly. Something like
```
kubectl kadalu storage-add storage-pool-1 \
    --uuid kube1:328e56e8-5ad0-4a6f-943e-9bbd3e18fb32
```

**Comment by leelavg** [comment]
Ack, I also meant a similar setting
- Rather than having a separate `uuid` flag why not supply disk uuid to `device` flag itself, coz at the end of the day they both represent some disk and keep resulting diff to a minimum :)
- I mentioned `blkid` to resolve a UUID to it's disk path, coz we can only use a mounted path as gluster brick

Let me have a look at the codebase and implement if possible or i'll update the thread

**Comment by aravindavk** [comment]
> I don't understand your question. From my understanding when adding storage to a pool, kadalu currently accepts either a device such as
> 
> ```
> kubectl kadalu storage-add storage-pool-1 \
>     --device kube1:/dev/vdc
> ```
> 
> Or a mountpoint such as
> 
> ```
> kubectl kadalu storage-add storage-pool-1 \
>     --path kube1:/some/mount
> ```
> 
> You can't specify a UUID directly. Using UUID is preferred because it will not change after a reboot. Currently this can be done by specifying the UUID to be mounted at a mount point in the fstab of the host, then point kadalu to that mountpoint. However, it would be nice to give kadalu that UUID directly. Something like
> 
> ```
> kubectl kadalu storage-add storage-pool-1 \
>     --uuid kube1:328e56e8-5ad0-4a6f-943e-9bbd3e18fb32
> ```

Makes sense. `mount` command accepts `UUID` so server pod should be able to mount the disk by UUID. Let me explore this possibility.

Reference mount command

```
mount UUID=328e56e8-5ad0-4a6f-943e-9bbd3e18fb32 /bricks/...
```

**Comment by leelavg** [comment]
> mount command accepts UUID

Cool, we can directly pass UUID as brick_device in server yaml then.

In my k3d cluster disk is mounted as `devtmpfs` if it's not the case with other nodes, this rfe implementation will be straightforward.

**Comment by hunter86bg** [comment]
UUID always changes if you rebuild the FS (for example mkfs.xfs), it's far more reliable using the "/dev/disk/by-id/*" devices or "/dev/vg/lv".

Usually recreating the FS is far easier to wipe the old brick's file attributes
