### ISSUE TITLE
Upgrade guide / documentation

### ISSUE THREAD

**Issue by floek** [kadalu/kadalu#377]
Hi,

how do I upgrade my kadalu pods to the new 0.7.3 version? I found no documentation.
In the meantime, I reinstalled.

Thanks,
Floek

**Comment by floek** [comment]
I still wonder how to upgrade properly (#399). I'm at a testing environment now and do:
- delete all Kadalu pvs
- delete all ressources (including kadalustorage objects) in the kadalu namespace
- delete all Kadalu storageclasses
- delete the kadalu executable
- delete all data on the external Gluster volume
- run my ansible playbook and redeploy kadalu

But I think this is not the way to do it in production ;-).

**Comment by floek** [comment]
Hi, how do I upgrade to 0.7.7?

**Comment by ook** [comment]
Hi @floek . Not an authoritative answer but here "my" way to upgrade:

* run script https://github.com/kadalu/kadalu/blob/devel/extras/scripts/cleanup
* follow the installation instruction from https://github.com/kadalu/kadalu/blob/devel/doc/quick-start.md
* pray^W fix the issues by hand, case by case
HTH
