### ISSUE TITLE
Why are the kadalu containers used not tagged with a version?

### ISSUE THREAD

**Issue by floek** [kadalu/kadalu#392]
Hi,

I found the kadalu containers have no version tag:
```
> kubectl -n kadalu get pods operator-76b85b86b6-d48h9 -ojson | jq '.spec.containers[].image'
"docker.io/kadalu/kadalu-operator:devel"
```

How can I control the container versions that way?

Cheers,
floek

**Comment by amarts** [comment]
Please note that latest releases are doing it right! It was an issue with actions scripts.
