### ISSUE TITLE
storage pool in terminating state

### ISSUE THREAD

**Issue by monaminor** [kadalu/kadalu#410]
even after deleting storage pool, the pool not get deleted rather its in terminating state.

after kadalu operator is started i wanted to run storage, brick are successfully created on the node but as i want to delete the storage pool , its not deleting, rater it is in terminating state.
------------------------------------------------------------
here is my storage-config.yaml
------------------------------------------------------------
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  # This will be used as name of PV Hosting Volume
  name: storage-replica-pool-1
spec:
  type: Replica3  # Notice that this field tells kadalu operator to use replicate module.
  storage:
    - node: aks-agentpool-13701380-vmss000000      # node name as shown in `kubectl get nodes`
      device: /dev/sde # Device to provide storage to all PV
    - node: aks-agentpool-13701380-vmss000001      # node name as shown in `kubectl get nodes`
      device: /dev/sdd # Device to provide storage to all PV
    - node: aks-agentpool-13701380-vmss000002      # node name as shown in `kubectl get nodes`
      device: /dev/sdd # Device to provide storage to all PV

------------------------------------------------------------------------------------------------------------------------------
here storage pool is in terminating state:-
------------------------------------------------------------------------------------------------------------------------------

$ kubectl get po -n kadalu
NAME                                READY   STATUS        RESTARTS   AGE
server-storage-replica-pool-1-0-0   0/3     Terminating   0          114m

**Comment by amarts** [comment]
feel free to kill it with `kubectl delete pods --force -nkadalu server-storage-replica-pool-1-0-0`. There seems to be an issue with termination flow right now. This can be deleted forcefully for timebeing.
