### ISSUE TITLE
Issue with pod restart which caused availability of replica3 volume

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#415]
> User (in k8s slack)

Good morning Amar, we are using kadalu as our alpha service trial and encountered some interesting issue. so just check if you know any or your know how to forward the quesiton. thanks. we are using replica3 as our storage pool and everything works well until one node (we call it nodeA below) get some issue (from log it says failed to Failed to create file system fstype=xfs…) and then it is back after we do some troubleshotting from your doc. but the most interesting point is that when the nodeA is gone, it seems the entire nfs (created by glusterfs) is also down. have you seeing any behavior before?

> Amar (kadalu.io

Hi  Good morning. Good to hear you are using kadalu.
No, this shouldn't happen in ideal case, can you open an issue in kadalu repo? Will check it out.

> User

okay, what we knew is when server-storage-pool pod are somehow restarted, it failed as the attached devices has been formatted ( run by previous init ) and then it crashed (along with shd container with the following message DNS resolution failed on host server-storage-pool-3-2-0.storage-pool-3)

> Amar (kadalu.io)

DNS resolution is tied to the pod directly because of ClusterIP: none in config.

> User

no, my point is this pod are somehow restarted, it failed as the attached devices has been formatted ( run by previous init )

> Amar (kadalu.io)

but as you have quorum, (2/3 storage pools) replica3 completely shouldn't go down

> User

which the storage pod can’t be restarted.

> Amar (kadalu.io)

if you are OK, can i use the message here to create the issue in kadalu repo?

> User

sure, let me know if you require more config from our end

**Comment by amarts** [comment]
> User

pod are somehow restarted --> this node was in disk pressured, so maybe some pods war evicted and it just happened to the storage pod.

**Comment by hsinhoyeh** [comment]
Hi @amarts , thanks for posting the message for me. (and also introducing me this great tool for managing storage)
here are my steps to get the storage service back:
- took the nodeA out of the cluster
- run `kubeadm reset cleanup`
- run fdisk on devices (also format the target devices used in replica3, run mkfs.xfs /dev/sdaX )
- join back to the cluster

and 
storage-pool-3-2-0 is back and all pods can access their pvc, no data is gone.

Good job Team Kadalu!!
