### ISSUE TITLE
add 'helm' chart as part of release binary

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#447]
currently there is a helm directory, but we are not making a version specific release of helm chart. (and no automated tests to validate helm chart is at least working).

considering we can publish our own helm.tar.gz chart file, Recommend it to be pushed in `on release` job in actions.

For example the issue #441 is caused with using helm charts, and it was not being actively looked into from some of us. Having a tests would make it fail when a new feature is added, thus forcing us to keep it up-to-date.

**Comment by leelavg** [comment]
@amarts can i work on this issue and update the thread frequently so that others also can comment on improving the charts further?

**Comment by amarts** [comment]
@leelavg sure, and we are very happy if you can pick it up :+1:

**Comment by leelavg** [comment]
helm chart is tested as below:

```
# helm install --create-namespace https://github.com/kadalu/kadalu/releases/download/0.8.0alpha5/kadalu-helm-chart.tgz --generate-name
NAME: kadalu-helm-chart-1614048957
LAST DEPLOYED: Tue Feb 23 08:26:02 2021
NAMESPACE: kadalu
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The Kadalu Operator has been installed. Check its status by running:
  kubectl --namespace kadalu get pods

Visit https://kadalu.io/docs/k8s-storage/latest for instructions on how to add storage and create PVs out of it.

Important Notes:
- You can add storage pools with different types using 'KadaluStorage' type.
- The helm chart includes all the RBAC required to create kadalu.io CRD.

# helm ls
NAME                            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kadalu-helm-chart-1614048957    kadalu          1               2021-02-23 08:26:02.001786772 +0530 IST deployed        kadalu-0.1.4    0.8.0 

# bat storage-config-device.yaml --plain; k apply -f storage-config-device.yaml 
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: replica3-pool
spec:
  type: Replica3
  storage:
    - node: k3d-test-agent-0
      device: /dev/sdc
    - node: k3d-test-agent-1
      device: /dev/sdd
    - node: k3d-test-agent-2
      device: /dev/sde
kadalustorage.kadalu-operator.storage/replica3-pool created

# k get pods
NAME                          READY   STATUS    RESTARTS   AGE
operator-7f5d56f4c4-lpfz2     1/1     Running   0          15m
kadalu-csi-nodeplugin-q75k6   3/3     Running   0          15m
kadalu-csi-nodeplugin-msrnj   3/3     Running   0          15m
kadalu-csi-nodeplugin-tbpfh   3/3     Running   0          15m
kadalu-csi-nodeplugin-dkt5f   3/3     Running   0          15m
kadalu-csi-provisioner-0      5/5     Running   0          15m
server-replica3-pool-0-0      1/1     Running   0          24s
server-replica3-pool-2-0      1/1     Running   0          23s
server-replica3-pool-1-0      1/1     Running   0          23s

# k logs pod1 
This is a sample application
# df -h
Filesystem                Size      Used Available Use% Mounted on
kadalu:replica3-pool      2.0G         0      2.0G   0% /mnt/pv
# mount
kadalu:replica3-pool on /mnt/pv type fuse.glusterfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072)
Write/Read test on PV mount
Tue Feb 23 03:15:03 UTC 2021
SUCCESS
```

**Comment by leelavg** [comment]
Now that one of the requirements is verified, will validate CI wrt Helm when a change occurs. Please review below and provide feedback/comments

1. Using single version in Chart.yaml (appVersion vs Version)? (ref: https://codefresh.io/docs/docs/new-helm/helm-best-practices/#helm-packaging-strategies)
2. Interoperability between Jinja2 and Go templating? (Difficult to achieve but good to have a single source to edit)
3. Make helm chart part of any artifact repo? (IMHO we continue attaching archive as part of release asset for now)
4. If point 2 can't be met, change template to install suitable chart wrt Kubernetes distro (OpenShift, RKE, etc)
5. Use `crds/` folder in Helm v3, may not be suitable if we expand on adding EC vols as well? (ref: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#install-a-crd-declaration-before-using-the-resource)

Any agreed changes CAN be part of next release (0.9.0), please correct any discrepancies.

@amarts, @aravindavk thoughts?

**Comment by amarts** [comment]
I would treat this particular issue as resolved for now. Thanks @leelavg in resolving it. Now, coming to above question series: (technically we can open different issues per point in later point in time).

1. I am OK with not using appVersion for Chart.yaml, and let Chart.yaml can have its own version.
2. Why do we need it? Ie, currently, in helm chart, we are not using any templating at all. everything is handled inside of operator (and CSI drivers), during runtime.
3. open to this, but as I have some limited knowledge on helm, open to suggestions here. 
4. Agree with this, and thats what we have done with `make gen-manifests`, May be we can build 4 different charts for now. Or, if the templating you were talking about is about operator.yaml config, then yes, we can do a separate one in helm... open to using what many other projects use.
5. At least IMO, there is no need for EC volume in kadalu (at least in k8s focused solution). Haven't thought anything about `crds/` at all...

I agree. Considering that we have some basic CI done for helm, and release artifacts would contain a helm chart, I say, we can focus any other improvements to 0.9.0 series release. Well on that point, we have decided to not branch out and maintain specific release versions till we reach 1.0.0 version. So, we are OK with improvements as and when it comes.

**Comment by amarts** [comment]
lets move to specific issues on discussion from here. closing the issue.

**Comment by leelavg** [comment]
@amarts ack, will keep a tab on enhancing Helm and will work on resolving other issues.
