### ISSUE TITLE
RFE: make kadalu-server run on top of RWO PV itself.

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#46]
Most of the cloud providers provide a decent RWO PV support. Can kadalu-server run on top of the RWO PV, instead of having a need for admin manually setup a block device, or an export directory.

**Comment by amarts** [comment]
Addresses one of the usecases mentioned in #42

**Comment by amarts** [comment]
https://kubernetes.io/docs/concepts/storage/volumes/#awselasticblockstore 

If you notice, the PV here can take `fsType` parameter, with which, we can make our storage work on top of it. All it needs it have the proper config parameters to the PVC saying we need xfs.

**Comment by amarts** [comment]
above suggestion answers https://github.com/kadalu/kadalu/issues/42#issuecomment-545769621

**Comment by hetii** [comment]
I just add that in azure is possible to define fsType by using such storage class:

    ---
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: premium-azure-disk-sc
    provisioner: kubernetes.io/azure-disk
    reclaimPolicy: Retain
    # reclaimPolicy: Delete
    allowVolumeExpansion: true
    volumeBindingMode: Immediate
    parameters:
      storageaccounttype: Premium_LRS
      kind: Managed
      fsType: xfs
      #kind: Shared

**Comment by amarts** [comment]
It is tested on top of hostpath PVC of minikube right now, and added CI tests for the same.  The features should be available with v0.4 version.

**Comment by amarts** [comment]
@hetii our v0.4 release is now out, and this feature is available to try. Just make sure that the host PVC is available for `kadalu` namespace.
