### ISSUE TITLE
How to explicit name the KadaluStorage in a PVC?

### ISSUE THREAD

**Issue by hans-fischer** [kadalu/kadalu#460]
Example:
I have two storages. One is HDD other is SSD and both are of type Replica2. 

Question:
How can I create a PVC that askes for SSD storage?

**Comment by aravindavk** [comment]
Create two Storage classes by specifying the storage_name.

Refer this doc for creating custom Storage classes.

https://kadalu.io/docs/k8s-storage/latest/storage-classes
