### ISSUE TITLE
Potential update on running cluster

### ISSUE THREAD

**Issue by posone** [kadalu/kadalu#463]
Dear team,

is it possible to perform the update to 0.7.7 (we are currently running 0.7.1) on running kubernetes cluster? We have installed it through this way:
curl -LO https://github.com/kadalu/kadalu/releases/download/0.7.1/kubectl-kadalu
kubectl kadalu install

But we could not find any description how to perform the upgrade. Would you please support us on that? Appreciate any feedback, thank you!

**Comment by aravindavk** [comment]
Download the latest and replace the existing `kubectl-kadalu`

```
curl -LO https://github.com/kadalu/kadalu/releases/download/0.7.7/kubectl-kadalu
```

**Comment by posone** [comment]
And any other commands are not needed, will it be updated automatically?

**Comment by aravindavk** [comment]
After running `kubectl kadalu install` Operator gets upgraded, and the Operator will upgrade all the other entities.

@amarts any other changes required?

**Comment by leelavg** [comment]
@posone just a note, if gluster storage is external, above method updates operator and no changes are peformed on gluster nodes afaik.

Let's hear from @amarts as well and replica vols might get benefitted from healinfo in .8 (pre)release as well.

**Comment by amarts** [comment]
After install of new kubectl-kadalu, running `kubectl kadalu install`  should take care of upgrading all the versions.

About missing docs about upgrade, we wanted to get the healinfo into system before calling upgrade complete. Right now this is not complete for replica2 and 3.

**Comment by posone** [comment]
So just to make sure - we have internal storage - after we perform kubectl kadalu install - our data will not be touched? Only kadalu operator will be updated?

**Comment by posone** [comment]
After kubectl kadalu install nothing really happened
kubectl-kadalu install
Kadalu operator already installed

**Comment by amarts** [comment]
This looks to be the issue we had with #305. Considering you have 0.7.1 version, it may need a namespace cleanup and reinstall of the operator.

I guess only thing you would need to handle proper storage migration is #464. If there is not a lot of storage, my recommendation is to move over to new version now, as we now have at least a basic concept of 'upgrade' with 0.7.6 and above version.

**Comment by posone** [comment]
Team, 
thank you for tips, we did storage migration and re-install kadalu for 0.7.7. Everything is working fine now, thanks!
