### ISSUE TITLE
[CI] - Add more IO tests to qualify the release

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#471]
It is good if we add more IO tests to the PR merge CIs (or at least release CIs). That we we can avoid bugs like #468 which happen after upgrade!

Recommend some automated containers which can be used for testing!

**Comment by leelavg** [comment]
@amarts I've prepared an image (~75MB) consisting of Crefi, arequal and I believe this type of IO is good enough for a start.

If you are fine with the size and [dockerfile steps](https://thoughtexpo.com/setup-k3d-cluster-for-local-testing-or-development/#local-registry), i can give a try including that in CI.

**Comment by amarts** [comment]
Sure. It seems like a good idea.

**Comment by KyleSanderson** [comment]
Can this sample be added to CI https://github.com/kadalu/kadalu/issues/577#issuecomment-874283249

**Comment by leelavg** [comment]
@KyleSanderson definitely, dbench seems to be a good candidate to be included in CI.

@vatsa287 see if you can pick this up or I'll start working on it after a week's time.

**Comment by leelavg** [comment]
> Can this sample be added to CI [#577 (comment)](https://github.com/kadalu/kadalu/issues/577#issuecomment-874283249)

I revisited this and unfortunately current CI infra isn't suited for dbench, however we'll add more functional tests based on recent learnings around disk usage metrics
