### ISSUE TITLE
0.8.0 fails on AARCH64 (Pi 4 4GB)

### ISSUE THREAD

**Issue by DanielWinks** [kadalu/kadalu#474]
When attempting to run 0.8.0 on AARCH64/ARM64, the operator fails to start, giving error message:

`ModuleNotFoundError: No module named 'xxhash._xxhash'`

Seems the AARCH64 build is missing the above Python module. 0.7.7 does not display this issue and works properly.

**Comment by amarts** [comment]
Ack! 

This is my bad, there were some issues with `pynacl` (ie, cryptography pip install in arm/v7 tag). To figure that out, I had made both arm builds disabled. Added them back now, 0.8.1 should have the arm64 builds. (not yet ready with arm/v7).

Next time such things happen, it will have a pointer in Release notes.

**Comment by amarts** [comment]
The issue of ARM64 is a major one we wanted to resolve, and a lot of work has gone in last 6 months for the same. With latest `devel` tag everything is working. Will make a release 0.8.6 soon which should have most of the things covered.
