### ISSUE TITLE
[RFE] Update documentation to include making distributed storage volumes

### ISSUE THREAD

**Issue by FlexibleToast** [kadalu/kadalu#475]
Release 0.8.0 looks like it brought in support of distributed volumes. I can't find any documentation on how to use this feature. For example I have 4 nodes and would like to setup 2 replicas distributed over 2 nodes creating something similar to a RAID10.

**Comment by amarts** [comment]
Ack! Pending on our end. 

The only place an example is added is in 'testing', as we use it in our PR tests now. Check the [example here](https://github.com/kadalu/kadalu/blob/devel/tests/storage-add.yaml#L10..L15)

It would be similar for other type of volumes. If its Replica3, the storage config takes options in 3,6,9 or any multiple of 3s. They will be added to distribute group in the same order. first 3 will be a replica group, and second 3 another replica group.

**Comment by FlexibleToast** [comment]
Looks like it is as easy as setting type to ReplicaX and make sure the total number of nodes is a factor of X? So just type: Replica2 and list the four nodes?

**Comment by amarts** [comment]
Yes, that's right. Number of bricks in config should be multiple of replica count.

**Comment by aravindavk** [comment]
Valid issue, keep this open
