### ISSUE TITLE
Observation on volfiles on 0.8.0

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#478]
Observed two issues in Kadalu(k8s) volfiles in 0.8.0

1) Distribute is used in the shd volfiles https://github.com/kadalu/kadalu/blob/devel/templates/Replica3.shd.vol.j2#L28-L31 

2) Skips `afr-pending-xattr` in both client and shd volfiles https://github.com/gluster/glusterd2/issues/925

**Comment by amarts** [comment]
observations from @aravindavk...

Actually, point 1 above is a genuine issue, and I noticed that dht (nor utime) is used in self-heal daemon files. (sent a fix now)

where as, 2nd point, `afr-pending-xattr` gets automatically assigned if not provided, this shouldn't be an issue.

**Comment by aravindavk** [comment]
#481 fixes this issue.
