### ISSUE TITLE
W [fuse-bridge.c:1981:fuse_err_cbk] 0-glusterfs-fuse: 5928: FSYNC() ERR => -1 (Disk quota exceeded)

### ISSUE THREAD

**Issue by tivizi** [kadalu/kadalu#497]
my nodeplugin have some error logs.
[nodeplugin.txt](https://github.com/kadalu/kadalu/files/6163895/nodeplugin.txt)

Thanks kadalu Group.

**Comment by amarts** [comment]
missed seeing this earlier. 'Disk Quota Exceeded' is expected to come when the PV is completely consumed.

Now few more questions:

* Which version of kadalu deployment you have?
* what does pv describe, and a `df -h` output from inside of the nodeplugin show?

**Comment by tivizi** [comment]
Thanks. I'll close this issue first, and I'll reopen it after I catch it again.

**Comment by hsinhoyeh** [comment]
Hi @amarts 

we also see such issues on my cluster with replica1.
kadalu version: 0.8.2

go do node-plugins ( `kubectl exec -it kadalu-csi-nodeplugin-vtplp -n kadalu -c kadalu-nodeplugin -- sh` )
```
df -h

...

kadalu:storage-pool-1  500G  9.2G  491G   2% /mnt/storage-pool-1

```

But when I mount the external storage on the host, du shows
```

root@node1:/data-s1# mount /dev/sda1 /data-s1 && cd /data-s1 && du -sHM
627	.
```

some suspicious logs (`kubectl logs -f server-storage-pool-1-0-0 -n kadalu --all-containers`)

```
[2021-06-14 09:32:49.249896 +0000] W [simple-quota.c:862:sq_setxattr] 0-storage-pool-1-quota: request sent on non-namespace inode (glusterfs.quota.total-usage)
[2021-06-14 09:32:49.249920 +0000] I [MSGID: 115060] [server-rpc-fops.c:932:_gf_server_log_setxattr_failure] 0-storage-pool-1-server: 10708: SETXATTR /subvol/
01/35/pvc-8fdf2e5f-6378-4939-b4de-ec02cde4522d (a21434b0-927e-4d26-bca5-065da1abe3a6) ==> glusterfs.quota.total-usage, client: CTX_ID:c140aea7-ac62-4201-9b66-d6514ce10985-GRAPH_ID:0-PID:28-HOST:kadalu-csi-provisioner-0-PC_NAME:storage-pool-1-client-0-RECON_NO:-0, error-xlator: storage-pool-1-quota
```
