### ISSUE TITLE
Create homebrew package for kadalu cli

### ISSUE THREAD

**Issue by marklester** [kadalu/kadalu#508]
https://brew.sh/
Would be nice to be able to do `brew install kadalu`

k9s, helm, and kpt have formulas too

**Comment by leelavg** [comment]
@marklester can please mention whether you got limited by kadalu cli installed with pip?

Not at all against in implementing the functionality and at the same handling python environments with brew installed packages may create confusion i guess. :/

All pkgs referred in the issue are go version neutral.

**Comment by aravindavk** [comment]
> @marklester can please mention whether you got limited by kadalu cli installed with pip?

`kubectl-kadalu` is not available via pip(may be old version is available). `kubectl-kadalu` is released as single binary using the Python zipapp(https://docs.python.org/3/library/zipapp.html).

**Comment by aravindavk** [comment]
> https://brew.sh/
> Would be nice to be able to do `brew install kadalu`
> 
> k9s, helm, and kpt have formulas too

Nice idea, It surely improves the discoverability. Thanks for the suggestion.

**Comment by leelavg** [comment]
@aravindavk thanks a lot for the clarification, will look into this issue if possible.
