### ISSUE TITLE
setfattr errors on using external cluster in kadalu-native format

### ISSUE THREAD

**Issue by leelavg** [kadalu/kadalu#526]
In a cluster using external storage in kadalu native format observing below errors in provisioner logs (kadalu devel branch)

```
setfattr: /mnt/pv-ext/subvol/a6/bf/pvc-cab174b3-d77c-41f5-83e7-bc84ac75606c: Operation not supported
setfattr: /mnt/pv-ext/subvol/a6/bf/pvc-cab174b3-d77c-41f5-83e7-bc84ac75606c: Operation not supported
```

I have recycled the setup and can't provide other logs atm.

**Comment by aravindavk** [comment]
I am suspecting this is because Simple Quota is not available in the external Volume.

https://github.com/kadalu/kadalu/blob/291c3d49a46a0f8192db0523c79b16a6ce5cb41e/csi/volumeutils.py#L355-L367

**Comment by leelavg** [comment]
Yes, I also discussed this with @amarts and he's also on same opinion.

**Comment by michaltrmac** [comment]
Hi,

we have same problem. PVC with Kadalu operator create directory on gluster cluster but no quota is applied.

Is there something we can set on gluster volume to make Simple Quota available?

```
# lsblk -f
NAME                    FSTYPE      LABEL UUID                                   MOUNTPOINT
sda
├─sda1                  vfat              F5C4-DCD6                              /boot/efi
├─sda2                  ext4              12330c73-6c28-403f-932f-d3b61a53ae77   /boot
└─sda3                  LVM2_member       DwlGFu-p4xL-Wf8E-HJ0z-22y3-ouKc-WrMmG2
  ├─cl-root             xfs               0f2eff57-145b-47fc-a75c-108e90da9752   /
  └─cl-swap             swap              ff946fcd-3de9-44d4-8e10-fa20100c7d28
sdb                     LVM2_member       6f1f3m-bj1J-XVLT-jFEW-Wc2o-jZs9-HqDucC
└─storage_vg-storage_lv xfs               c63a9558-f2c3-42b5-b348-d5c16b05d656   /mnt/glusterfs
```
```
# gluster volume info

Volume Name: gv0
Type: Disperse
Volume ID: 1cf703f1-6347-4526-a417-d5a72b282181
Status: Started
Snapshot Count: 0
Number of Bricks: 1 x (2 + 1) = 3
Transport-type: tcp
Bricks:
Brick1: XXX.XXX.XXX.1:/mnt/glusterfs/gv0/b1
Brick2: XXX.XXX.XXX.2:/mnt/glusterfs/gv0/b1
Brick3: XXX.XXX.XXX.3:/mnt/glusterfs/gv0/b1
Options Reconfigured:
features.quota-deem-statfs: on
features.inode-quota: on
features.quota: on
storage.fips-mode-rchecksum: on
transport.address-family: inet
nfs.disable: on
```

**Comment by leelavg** [comment]
@michaltrmac Can you please confirm whether kadalu_quotad is running or not in the nodes of exported bricks as [stated](https://github.com/kadalu/kadalu/blob/devel/server/README.md#external-servers)? 

It's linked in [kadalu docs](https://kadalu.io/docs/k8s-storage/devel/external-gluster-storage/), search for 'the server documentation' it's easy to miss though.

This issue tracks a similar but different use case, nevertheless thanks for the comment.

**Comment by michaltrmac** [comment]
@leelavg thanks for comment. I missed that part of documentation.

Still having problem to get quotad working. I will open new issue for that,

**Comment by zhucan** [comment]
The "setfattr... unsupported"  is printed by the "quota-crawler.sh".
