### ISSUE TITLE
Normal life of kadalu storage: add and remove devices

### ISSUE THREAD

**Issue by ook** [kadalu/kadalu#536]
Hi,

I have working Kadalu storages, mainly two kind: a large storage non replicated (replica1) and a "serious" storage (replica3, with 3 nodes on 3 different machines).

I'd want to add new devices to those storage, and remove some (TBH honest: I want to add new bigger machines and remove the older ones without having downtime).

I didn't see a way to achieve that through `kubectl kadalu storage-add` command, and even `kubectk kadalu storage-remove` doesn't seem to work for the moment.

Is there a way to achieve this (even workaround) ?

Thank you

**Comment by amarts** [comment]
Thanks for mentioning the usecase clearly! This is not available right now! But, should be possible to bring soon.

We thought storage migration is a problem for everyone who tries to keep hardware warranty, so would happen once in 3-5yrs. It was not taken up for that reason.  Let me think and propose solution soon.

**Comment by amarts** [comment]
@ook we have introduced #573 and along with #570. Which should address these concerns. Please check them with 0.8.6 release and let us know if that works.

**Comment by ook** [comment]
Thank you @amarts,I'll give it a try soon. Is there an upgrade guide available?
