### ISSUE TITLE
Build a framework to handle 'gluster-options' efficiently

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#542]
Currently, we call kadalu as a opinionated storage. Which is good. But glusterfs has many options which work better for few workloads. Hence to reach to wider audience, and usecases, we need a clear way to add options to particular storage config. That will allow our releases to work for all work-loads.

**Comment by aravindavk** [comment]
This issue is adding support for Volume options https://github.com/kadalu/kadalu/issues/680

Is that sufficent or missing anything?
