### ISSUE TITLE
RFE: provide helm chart

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#55]
[helm charts](https://helm.sh/) are a good way to have more reach in k8s world. Would be good to have a helm chart implemented for kadalu project.

**Comment by amarts** [comment]
More on it here : https://docs.bitnami.com/kubernetes/how-to/create-your-first-helm-chart/

**Comment by amarts** [comment]
we don't have helm chart yet, and we still need one!

**Comment by unixfox** [comment]
Bump, still interested.

**Comment by amarts** [comment]
basic helm chart is provided in the repo now. Will keep tracking the issues separately for any specific bugs from now on.
