### ISSUE TITLE
[DOC] unknown field "kadalu_format"

### ISSUE THREAD

**Issue by hunter86bg** [kadalu/kadalu#558]
It seems that the sample code at [external-gluster-storage](https://kadalu.io/docs/k8s-storage/latest/external-gluster-storage/) has an unknown field names "kadalu_format"

~~~
root@kube1:~# cat storage.yaml 
# file: external-config.yaml
---
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: ext-config
spec:
  type: External
  details:
    # gluster_hosts: [ gluster1.kadalu.io, gluster2.kadalu.io ]
    gluster_host: kube3
    gluster_volname: kubernetes
    gluster_options: backup-volfile-servers=kube3
    # Omitting 'kadalu_format' or using 'native' as a value will create
    # 1 PV : 1 Subdir in external gluster volume
    #kadalu_format: native

# file: pvc-from-external-gluster.yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-ext-kadalu
spec:
  # Add 'kadalu.external.' to name from KadaluStorage kind
  storageClassName: kadalu.external.ext-config
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # This needs to be set using 'kadalu-quotad'
      storage: 1024Mi
~~~

~~~
root@kube1:~# kubectl apply -f storage.yaml 
error: error validating "storage.yaml": error validating data: ValidationError(KadaluStorage.spec.details): unknown field "kadalu_format" in storage.kadalu-operator.v1alpha1.KadaluStorage.spec.details; if you choose to ignore these errors, turn validation off with --validate=false
~~~

**Comment by leelavg** [comment]
@hunter86bg can you please update CRD and try? Or the issue is seen after CRD update too?

**Comment by leelavg** [comment]
Btw, 'kadalu_format' in CRD is in unreleased version. IOW, it's in devel branch currently :)

**Comment by hunter86bg** [comment]
I used latest and followed the documentation which actually is indeed jn devel branch :)
I've removed that line and it worked

**Comment by leelavg** [comment]
This [test](https://github.com/kadalu/kadalu/pull/527#issuecomment-828463648) was peformed while validating the feature.

It seems CRD default value shouldn't be supplied, confused :/

Thanks for the report, will get back at the earliest.

**Comment by leelavg** [comment]
> I've removed that line and it worked

Would it be possible for you to provide o/p of `kubectl get crd -o yaml | grep -C3 kadalu_format`?

**Comment by hunter86bg** [comment]
It doesn't return any output.
The setup was built yesterday using kubespray ontop Ubuntu 20.04 .
Theoretically, it should be fully updated.

**Comment by leelavg** [comment]
As discussed over slack and operator deployed was of v0.8.2 the above is expected. 

Pls comment if issue is observed on devel.
