### ISSUE TITLE
Glusterfs may consume reserved port

### ISSUE THREAD

**Issue by AndrzejOlender** [kadalu/kadalu#583]
Hi, 

I have a kadali deploy done as replica3. k8s cluster version 1.21.1 (kubespray) (3 nodes)
These are 3 vmware virtual machines (RedHat 7), disks for kadalu allocated via vmware. 

On the first two nodes I get this error over and over again.
1-2 node logs

``
W [MSGID: 101012] [common-utils.c:3275:gf_get_reserved_ports] 0-glusterfs: could not open/read file, getting ports info [{ /proc/sys/net/ipv4/ip_local_reserved_ports}, {errno=2}, {error=No such file or directory}]
``
cat from host node1/2/3
``
cat /proc/sys/net/ipv4/ip_local_reserved_ports
30000-32767
``
cat inside pod
````
root@server-storage-dbg-0-0:/# cat /proc/sys/net/ipv4/ip_local_reserved_ports
cat: /proc/sys/net/ipv4/ip_local_reserved_ports: No such file or directory
````
3 node log:

`
2021-06-22 12:49:50.256793 +0000] E [name.c:264:af_inet_client_get_remote_sockaddr] 0-storage-dbg-client-1: DNS resolution failed on host server-storage-dbg-1-0.storage-dbg
`
````
kubectl get pod -n kadalu -o wide
NAME                          READY   STATUS    RESTARTS   AGE   IP               NODE          NOMINATED NODE   READINESS GATES
kadalu-csi-nodeplugin-58dz7   3/3     Running   0          40m   192.168.151.14   cplsv010056   <none>           <none>
kadalu-csi-nodeplugin-jdzbp   3/3     Running   0          40m   192.168.151.15   cplsv010057   <none>           <none>
kadalu-csi-nodeplugin-qhlw4   3/3     Running   0          40m   192.168.151.16   cplsv010055   <none>           <none>
kadalu-csi-provisioner-0      5/5     Running   0          40m   192.168.151.17   cplsv010057   <none>           <none>
operator-7b6b9fdbc7-rrnl9     1/1     Running   0          40m   192.168.151.13   cplsv010057   <none>           <none>
server-storage-dbg-0-0        1/1     Running   0          39m   192.168.151.18   cplsv010055   <none>           <none>
server-storage-dbg-1-0        1/1     Running   0          39m   192.168.151.19   cplsv010056   <none>           <none>
server-storage-dbg-2-0        1/1     Running   0          39m   192.168.151.20   cplsv010057   <none>           <none>
````
What do you guys think about this issue?

[logs.txt](https://github.com/kadalu/kadalu/files/6694421/logs.txt)

kadalu 0.8.3

**Comment by aravindavk** [comment]
Looks like the log messages are misleading. All server pods will use `24007` port. May be some other error masking this. Will look into the error from the log and update here.

These errors may be related to Heal daemon, Are you able to create PVs?

**Comment by AndrzejOlender** [comment]
Thank you for your quick response. Any PVs are in pending status.

**Comment by leelavg** [comment]
Hi @AndrzejOlender 

If you are evaluating Kadalu on a test setup can you please perform a [cleanup](https://github.com/kadalu/kadalu/blob/devel/extras/scripts/cleanup) of kadalu namespace and install operator once again?

If the setup is still up, can you ping server pods from provisioner pods? 

- Like login to `kadalu-provisioner` container in `kadalu-csi-provisioner-0 pod` and `ping server-storage-dbg-1-0.storage-dbg`
- Likewise login to server pod and ping it's peers
- if pings are failing then it's possible there's some network policy inhibiting the communication or server pods aren't resolvable at all.

**Comment by AndrzejOlender** [comment]
Hi @leelavg 

Yes, I tried cleaning everything with the script.
I just tried ping from pod kadalu-csi-provisioner pod and I think you are right.
I need to check other ways now.
````
root@kadalu-csi-provisioner-0:/# ping server-storage-dbg-1-0.storage-dbg
ping: server-storage-dbg-1-0.storage-dbg: Name or service not known
````

**Comment by leelavg** [comment]
Hey @AndrzejOlender since you mentioned `vmware` i think this may be related to https://github.com/kadalu/kadalu/issues/614#issuecomment-895797501, if you didn't fix it already?

**Comment by AndrzejOlender** [comment]
It worked for me too, solved.
Thanks.

**Comment by kotnn** [comment]
I also use Wmware but have no file /etc/modprobe.d/vxlan.conf 
Please advise

**Comment by kotnn** [comment]
And Ilso I have no any service in kadalu ns:
![image](https://user-images.githubusercontent.com/38759038/131715997-9ffe564e-622d-4b80-9755-e0c8055b705a.png)

**Comment by kotnn** [comment]
if it matters,  we use Calico

**Comment by leelavg** [comment]
@kotnn 

1. VMware fix is suggested by an user and it seem to work for atleast 2 users that we know of
2. In Calicio can you please create a rule/policy to allow 24007 port on server pods? ( I use flannel so not sure how calicio is configured)

Edit: Small request, pls raise a new issue referring another one if closed (we don't get updates on slack if commented on issues 😅)
