### ISSUE TITLE
[RFE] Heketi to Kadalu Migration

### ISSUE THREAD

**Issue by aravindavk** [kadalu/kadalu#587]
Recently Volume ID option is added while adding Kadalu Storage. This is good enough to migrate the Heketi Volumes to Kadalu Storage. But once imported it will be used as common storage pool and new PVs may gets assigned from this Storage.

Proposal:

* Get the Gluster Volume ID, PV ID(Ex: `pvc-ed2e3167-5040-4ab0-9b6c-a2dbcc552b6e`), Volume Type and bricks list
* Join the Heketi nodes to Kubernetes Cluster and note the hostnames by running `kubectl get nodes` command.
* Note the device paths(`LVs`)
* Create Kadalu Storage(Using `storage-add`) with the name same as PV ID. Specify the Storage disks in the same order of bricks in Heketi managed Volume. **Note**: Use `--volume-id` option to specify the Heketi managed Gluster Volume ID.
* Change CSI Provisioner to not use Kadalu Storages if the name starts with `pvc-`
* Change CSI Provisioner to map the Kadalu Storage if PV ID matches the Kadalu Storage name(No Quota, Use full Volume)
* Create PV with the same name as used with Heketi.
* Change CSI node plugin to mount the Kadalu Storage root directory when a Pod requests the mount of a PV with ID same as Kadalu Storage name.

Many things can be automated, for example: Use the `kubectl` and Heketi CLI to get the Volume info and convert the Heketi Volume info to `kubectl kadalu` command.

**Comment by amarts** [comment]
I suggest, treating this and External storage with non-native format in a similar way. Way less code, and similar handling for heketi volume.

**Comment by leelavg** [comment]
My knowledge about Heketi is rather limited however I'm unsure whether block hosting volumes can also be migrated in the same or not 🤔

@amarts I guess we can map heketi independent mode to external non-native and everything else to kadalu native as they are deployed as pods already or count everything as External for a start?

**Comment by aravindavk** [comment]
> I suggest, treating this and External storage with non-native format in a similar way. Way less code, and similar handling for heketi volume.

Makes sense. But when all the Storage nodes are migrated to Kadalu then it should be handled as native way with a few changes to Provisioner code. But node plugin can share the code of non-native format.

**Comment by leelavg** [comment]
@aravindavk small query, did you design a way to move all volume handling logic to operator and serve through REST API (first referenced in https://github.com/kadalu/kadalu/issues/553#issuecomment-848597576)?

**Comment by amarts** [comment]
If we think of REST API, we can also consider running glusterfs's new [volfile-server xlator ](https://github.com/amarts/glusterfs_fork/blob/2427c2862ec56ceab7b489f0f6ce18f238c99bf6/xlators/mgmt/volfile-server/README.md) on operator, so even client vols are served from there. Just that this service now needs a constant domainname to refer to.

**Comment by aravindavk** [comment]
> @aravindavk small query, did you design a way to move all volume handling logic to operator and serve through REST API (first referenced in [#553 (comment)](https://github.com/kadalu/kadalu/issues/553#issuecomment-848597576))?

Not Yet. I am also thinking about getting ConfigMap write capability to CSI Provisioner Pod. Nothing finalised yet.

**Comment by amarts** [comment]
considering #597 is merged, good to test if 0.8.4 is ready for a migration from heketi with native kadalu approach. Any volunteers to help us test this ? (We recommend this only if you have a test setup where you already have heketi, or can setup heketi). For further steps, please join Slack channel and we can discuss. Once tests are successful, we can update this thread on exact steps needed, and we can also automate the process with `kubectl kadalu` CLI
