### ISSUE TITLE
Failed to generate grpc python code

### ISSUE THREAD

**Issue by fs-system** [kadalu/kadalu#59]
```
/usr/bin/python3: Error while finding module specification for 'grpc_tools.protoc' (ModuleNotFoundError: No module named 'grpc_tools')
```
Add Developer readme which will help for new  comers to setup the environment

**Comment by amarts** [comment]
Thanks for the suggestion. Will give and update those information soon.

Meantime, would be great if you can try it out, and say what are the improvements you suggest as issues too :-)
