### ISSUE TITLE
RFE: Allow kadalu to manage external volume quota ( gluster-native directory)

### ISSUE THREAD

**Issue by hunter86bg** [kadalu/kadalu#596]
It seems that kadalu can assign quota to PVCs initially on external volumes (native gluster directory quota), but has no option to extend it via kubectl.

Can we enable kadalu to change gluster's dir quota upon resize.
The feature from Kubernetes side is: https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/

**Comment by amarts** [comment]
Code to make changes (if someone is interested to pick this up).

in `update_subdir_volume()` (csi/volumeutils.py), handle the case separately for External volume (refer CreateVolume code in csi/controllerserver.py), and send a quota limit set command to cluster (with changed quota)).

**Comment by hunter86bg** [comment]
@amarts , I can't find csi/controller.py . Maybe you ment csi/controllerserver.py ?

**Comment by amarts** [comment]
> @amarts , I can't find csi/controller.py . Maybe you ment csi/controllerserver.py ?

@hunter86bg sorry about that. Yes. You are right. Editing my detail above.

**Comment by hunter86bg** [comment]
@amarts , @aravindavk , maybe this one can be closed ?

**Comment by leelavg** [comment]
RFE is implemented and verified via #607 and #619
