### ISSUE TITLE
doc: add document on upgrade procedure, and why csi-nodeplugin is started separately.

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#610]
I think, having a note here about why this is decoupled wrt upgrade and node drain would be good.

_Originally posted by @leelavg in https://github.com/kadalu/kadalu/pull/608#r680860526_

**Comment by hunter86bg** [comment]
@amarts ,
So far I have understood that we need the latest 'https://github.com/kadalu/kadalu/releases/latest/download/kubectl-kadalu' + applying the 2 manifests:
stable:
  - 'https://github.com/kadalu/kadalu/releases/latest/download/kadalu-operator.yaml'
  - 'https://github.com/kadalu/kadalu/releases/latest/download/csi-nodeplugin.yaml'

devel:
  - 'https://raw.githubusercontent.com/kadalu/kadalu/devel/manifests/kadalu-operator.yaml'
  - 'https://raw.githubusercontent.com/kadalu/kadalu/devel/manifests/csi-nodeplugin.yaml'

Do we need to do anything else to ensure kadalu was updated ?

**Comment by amarts** [comment]
@hunter86bg now that 0.8.5 is released, the expectation is, people will only upgrade operator... which internally upgrades storage pods.

Now, about CSI-nodeplugin, we need to do upgrade when we are ready, when applications can be drained and upgraded. Something similar to how they would do upgrade of clients in glusterfs, by stopping app, umount, upgrade, mount, and start the app... That can be done depending on when thats planned.
