### ISSUE TITLE
Can not delete the pod with name "server-storage-pool-*" when exec "kubectl kadalu storage-remove xx"

### ISSUE THREAD

**Issue by zhucan** [kadalu/kadalu#613]
![image](https://user-images.githubusercontent.com/13997135/128152553-e5198f17-1e2a-4f28-b2cd-6a9e17737c15.png)

![image](https://user-images.githubusercontent.com/13997135/128152747-af1beeb9-c469-45ee-b121-08403cae44a1.png)

The kadalu storage of "storage-pool" had been deleted. but the status of the "server-storage-pool-*" is Creating.

**Comment by aravindavk** [comment]
Try:

```
kubectl kadalu storage-remove storage-pool
```

**Comment by zhucan** [comment]
Still exists.

**Comment by leelavg** [comment]
@zhucan 

1. can you please look at operator logs around the time you tried to delete `storage-pool`
2. pls specify which version of `kadalu` is deployed
3. I anticipate atleast one PVC is carved from this `storage-pool` and operator is backing off from it's removal
4. there's no way to let k8s not to remove entry from `kadalustorages` unless there's no `pvc` from `storage-pool`

**Comment by zhucan** [comment]
I know how to reproduce:
1. Deploy a kadalu with a not exists path when execing storage add
2. the pod is always creating
3. exec storage-remove
@leelavg

**Comment by leelavg** [comment]
@zhucan 

i tried reproducing the issue with non-existing `device` and `path`. Yes, either they'll fail to get created or stuck in creating state, however I'm able to delete them without any issues.

Please not I mistakenly pulled `devel` and created cluster. Nevertheless, the issue doesn't exist in `devel` so, next release shouldn't have above observed behaviour.


```
# when non-existing device is supplied
# k logs server-storage-pool-0-0                                                              
[2021-08-09 03:30:09,921] INFO [glusterfsd - 106:create_and_mount_brick] - Failed to mount device, continuing with mkfs  err=[32]  mount: /bricks/storage-pool/data: special device /dev/sdz does not exist. fstype=xfs device=/dev/sdz mountdir=/bricks/storage-pool/data
[2021-08-09 03:30:09,922] ERROR [glusterfsd - 147:create_and_mount_brick] - Failed to mount export brick         fstype=xfs device=/dev/sdz mountdir=/bricks/storage-pool/data error=[32]  mount: /bricks/storage-pool/data: special device /dev/sdz does not exist.

# when non-existing path is supplied
# k describe pod server-storage-pool-0-0 | sed -n '/Events/,$p'
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    2m18s                default-scheduler  Successfully assigned kadalu/server-storage-pool-0-0 to k3d-test-agent-0
  Warning  FailedMount  16s                  kubelet            Unable to attach or mount volumes: unmounted volumes=[glusterfsd-mountdir], unattached volumes=[kube-api-access-4gb87 gluster-dev gluster-cgroup gluster-kmods glusterfsd-volfilesdir glusterfsd-mountdir]: timed out waiting for the condition
  Warning  FailedMount  11s (x9 over 2m19s)  kubelet            MountVolume.SetUp failed for volume "glusterfsd-mountdir" : hostPath type check failed: /tmp/dummy is not a directory
```
