### ISSUE TITLE
Create pvc on kadalu storage(internal gluster deployed by kadalu) failed

### ISSUE THREAD

**Issue by zhucan** [kadalu/kadalu#614]
server storage pool status:
![image](https://user-images.githubusercontent.com/13997135/128156686-baae2b9b-6b86-4b4e-9251-0a33ed1536ca.png)

storageclass:
![image](https://user-images.githubusercontent.com/13997135/128156827-dc425521-676c-4538-bd9b-a1707e92052b.png)

pvc:
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv2
spec:
  storageClassName: kadalu.storage-pool
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

pvc status:
![image](https://user-images.githubusercontent.com/13997135/128156936-94968a12-5ce8-4bce-b881-04d251d6368a.png)

logs in kadalu-provisioner:
![image](https://user-images.githubusercontent.com/13997135/128157178-0c2ab775-e0ad-4e57-833e-36028951103a.png)

**Comment by leelavg** [comment]
- it seems provisioner isn't able to access `server` pods, do you see any errors in `server-storage-pool`
- can you provide cmd run against `storage-add` if you used `kubectl kadalu` or manifest applied?

**Comment by zhucan** [comment]
cmd: kubectl kadalu storage-add storage-pool --path k8s-1.deeproute.ai:/root/gluster1

**Comment by leelavg** [comment]
Updating comment with status shared on slack [issue614.txt](https://github.com/kadalu/kadalu/files/6952021/issue614.txt)

**Comment by zhucan** [comment]
@leelavg  no binary cmd "ping", what did you do to test?

**Comment by Madhu-1** [comment]
CC @aravindavk @amarts

**Comment by zhucan** [comment]
kubectl -n kadalu logs kadalu-csi-provisioner-0 -c kadalu-logging
![image](https://user-images.githubusercontent.com/13997135/128666383-563fec42-a8c8-4e7d-90c7-9ae5d63f4974.png)

**Comment by leelavg** [comment]
@zhucan I hope you went through the attached file.
1. I port-forwarded server pods using `kubefwd` to verify all the resources created successfully or not
2. I was able to reach externally and can confirm that there's no issue with Kadalu build
3. You have mentioned earlier that there are no network policies denying port access however above logs states the opposite
4. It's not at all recommended to use brick path on root mount, if you have a device available in your node, i suggest to try with that

Since, I'm not able to reproduce it, rather than doing a guess work I'd wait for others to pitch in or if I can have access to the environment that'd help a lot.

**Comment by zhucan** [comment]
Is it needed to mount local "/etc/hosts" to container?

**Comment by zhucan** [comment]
I had disabled the firewalld.

**Comment by leelavg** [comment]
> Is it needed to mount local "/etc/hosts" to container?

No, not at all.
- As mentioned earlier, we are deploying a headless service with sts so pods are resolvable by internal DNS without any effort
- All I was mentioning from start is, port `24007` on server pods isn't reachable and there should be some policy disabling it
- IIRC, you mentioned you are able to access external gluster, that was successful cause, the socket connection <IP:port> on external gluster is accessible from provisioner pod

**Comment by zhucan** [comment]
The 'gluster host' of the external gluster is ip not hostname, but the internal gluster use the hostname. is it no affect?

**Comment by zhucan** [comment]
![image](https://user-images.githubusercontent.com/13997135/128678220-3323e96b-8330-4664-b1df-a0d3c7d7fd30.png)

**Comment by zhucan** [comment]
![image](https://user-images.githubusercontent.com/13997135/128687831-f2811dbf-ad0f-44a5-bb7e-e8f24d639b17.png)

**Comment by leelavg** [comment]
Cool, thanks for the update. Btw, above forwards all the services existing in Kadalu ns, however doesn't confirm ping is working fine or not.

1. The first four entries are unique, not sure why multiple entries exist for same dns query (will check `server` code once)
2. You deployed external cluster which was working fine
3. After 2, you deployed internal cluster which isn't working
4. So, did you try deploying only internal gluster cluster and facing the same issue?

**Comment by zhucan** [comment]
If we want to confirm ping is working fine or not, we need to rebuild the container.  
![image](https://user-images.githubusercontent.com/13997135/128698273-fdb221ef-706a-48c4-b3eb-ce07fe1690d5.png)

I had tried  to deploy the internal gluster cluster only and facing the same issue.

**Comment by leelavg** [comment]
Ack, thanks for your patience. 

Confirming the way you created internal cluster.

Here `/gluster` is some random directory on worker node.

 ```
 # k kadalu install
 # k kadalu storage-add storage-pool --path k3d-test-agent-0:/gluster
 # k apply -f ../pvc.yaml 
 # k get pv,pvc
 NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM          STORAGECLASS          REASON   AGE
 persistentvolume/pvc-f8652d52-2d8d-478c-8223-e8e7526d9ac7   1Gi        RWX            Delete           Bound    kadalu/pvc1g   kadalu.storage-pool            2m14s
 
 NAME                          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
 persistentvolumeclaim/pvc1g   Bound    pvc-f8652d52-2d8d-478c-8223-e8e7526d9ac7   1Gi        RWX            kadalu.storage-pool   2m15s
```

Btw, in the meantime, if it's a ping issue, `# k kadalu storage-add storage-pool-1 --device <node:disk>` should also fail. You can try using a free disk or create one just using truncate and loop device etc

Sure, we'll definitely include `ping` in container.

**Comment by leelavg** [comment]
@zhucan feeling bad on how I missed this.😔

We already deploy `busybox` in provisioner pod, you can use `ping` and `nc` to verify `host` and `port` reachability respectively. 😃

**Comment by zhucan** [comment]
@leelavg Thanks， what's the image version can I use?

**Comment by zhucan** [comment]
> Ack, thanks for your patience.
> 
> Confirming the way you created internal cluster.
> 
> Here `/gluster` is some random directory on worker node.
> 
> ```
> # k kadalu install
> # k kadalu storage-add storage-pool --path k3d-test-agent-0:/gluster
> # k apply -f ../pvc.yaml 
> # k get pv,pvc
> NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM          STORAGECLASS          REASON   AGE
> persistentvolume/pvc-f8652d52-2d8d-478c-8223-e8e7526d9ac7   1Gi        RWX            Delete           Bound    kadalu/pvc1g   kadalu.storage-pool            2m14s
> 
> NAME                          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
> persistentvolumeclaim/pvc1g   Bound    pvc-f8652d52-2d8d-478c-8223-e8e7526d9ac7   1Gi        RWX            kadalu.storage-pool   2m15s
> ```
> 
> Btw, in the meantime, if it's a ping issue, `# k kadalu storage-add storage-pool-1 --device <node:disk>` should also fail. You can try using a free disk or create one just using truncate and loop device etc
> 
> Sure, we'll definitely include `ping` in container.

I will use the free disk to test and give the test result.

**Comment by leelavg** [comment]
> @leelavg Thanks， what's the image version can I use?

- I've deployed `server` with `storage-pool` so below will be the command for me.
- Referring your pool name, pls replace `storage-pool` with `storage-pool1` in below command, like ` k exec -it sts/kadalu-csi-provisioner -c kadalu-logging -- sh -c 'ping -c 5 server-storage-pool1-0-0.storage-pool1; nc -zv server-storage-pool1-0-0.storage-pool1 24007'`
```
# k exec -it sts/kadalu-csi-provisioner -c kadalu-logging -- sh -c 'ping -c 5 server-storage-pool-0-0.storage-pool; nc -zv server-storage-pool-0-0.storage-pool 24007'
PING server-storage-pool-0-0.storage-pool (10.42.1.20): 56 data bytes
64 bytes from 10.42.1.20: seq=0 ttl=62 time=0.548 ms
64 bytes from 10.42.1.20: seq=1 ttl=62 time=0.254 ms
64 bytes from 10.42.1.20: seq=2 ttl=62 time=0.328 ms
64 bytes from 10.42.1.20: seq=3 ttl=62 time=0.378 ms
64 bytes from 10.42.1.20: seq=4 ttl=62 time=0.363 ms

--- server-storage-pool-0-0.storage-pool ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 0.254/0.374/0.548 ms
server-storage-pool-0-0.storage-pool (10.42.1.20:24007) open
```

**Comment by zhucan** [comment]
what's the image version of the provisoner pod can I use? Because I need to deploy the kadalu-csi-provisioner again.

**Comment by zhucan** [comment]
@leelavg I had tested with free disk, the same errors with before test.
![image](https://user-images.githubusercontent.com/13997135/128801329-daa56e62-12c9-4af2-a334-fb6d8689b982.png)
Used cmd: kubectl kadalu storage-add storage-pool --type=Replica1 --device k8s-1.deeproute.ai:/dev/vdb
![image](https://user-images.githubusercontent.com/13997135/128801472-d37d83c6-ecd8-4e78-ac74-12b7bc1ec56c.png)

Test result:
![image](https://user-images.githubusercontent.com/13997135/128801518-2ab160fb-9999-472e-a8cb-d3e8ffcc8143.png)

![image](https://user-images.githubusercontent.com/13997135/128801582-9981b2c3-0a48-4059-a914-65c0e1bec8e5.png)

@leelavg

**Comment by leelavg** [comment]
> what's the image version of the provisoner pod can I use? Because I need to deploy the kadalu-csi-provisioner again.

You can do `k kadalu install` again, it'll pull 0.8.4 operator (i suppose you are using this version) and then operator takes care of deploying provisioner again.

If you don't mind, can we continue this in slack as i feel it's not good to send notifications every now and then by updating the issue.

**Comment by zhucan** [comment]
ok

**Comment by leelavg** [comment]
Update from slack:
Finally, as mentioned earlier, issue is with DNS resolution, please refer this [doc](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/) to troubleshoot services.

After `ping` works `port` accessibility can be checked by `nc`.

**Comment by zhucan** [comment]
@leelavg Thanks for your help, because of the port 8472 was used

**Comment by zhucan** [comment]
![image](https://user-images.githubusercontent.com/13997135/128826131-7933212f-08e3-41f2-b03e-53637d9dda2a.png)
modify the default ports of vxlan from 8472 to 4789 and restart the node.
