### ISSUE TITLE
Tests using Binnacle

### ISSUE THREAD

**Issue by aravindavk** [kadalu/kadalu#623]
Currently the tests are in bash script and doesn't give clear picture about what tests failed. Also it is difficult to add more tests.

Use [Binnacle](https://github.com/kadalu/binnacle) framework for testing.

* `setup.t` - Install `minikube`, `kubectl` and `kubectl-kadalu`. Start minikube.
* `helm.t` - Helm charts testing.
* `operator.t` - Operator install (Yaml based, helm based and kubectl-kadalu based Operator install) and cleanup tests.
* `replica1.t`, `replica2.t`, `replica3.t` and for each Storage types supported.
    - Add Storage
    - Create PV
    - Test PV size
    - Create Pod(Sample App with I/O tests)
* External Volume tests
* `kubectl-kadalu.t` - Kubectl Kadalu tests for all the options CLI exposes.
* `cleanup.t` - stop minikube and other cleanups.

Additional tests files for focussed workloads. Separate container for each applications that runs Workload specific tests and publishes result to stdout. For example, Postgres, File Upload app, MySQL, MinIO, Prometheus etc.

**Comment by aravindavk** [comment]
Upgrade testing.

**Comment by leelavg** [comment]
- Going to be a heavy lifting ig 😅
- Quick question, so binnacle is stable enough to replace our entire testing in CI?
- I'll give a try to translate atleast the `setup.t` for a start in next release 
- For helm I'm thinking to retain existing model of testing

**Comment by aravindavk** [comment]
> * Going to be a heavy lifting ig 😅

Yeah. That is why I added it to `0.8.6`(Milestone date: Sept 23)

> * Quick question, so binnacle is stable enough to replace our entire testing in CI?

It is getting stable day by day. Here, we can start running these tests in parallel without replacing the existing tests. Once it is stable then we can disable the script based testing.

> * I'll give a try to translate atleast the `setup.t` for a start in next release

Some more fixes pending in Binnacle, I will push those changes by next week. Mainly related to support Unix Pipe within the tests and Timeout related commands `TEST_WITHIN`, `EXPECT_WITHIN` etc.

> * For helm I'm thinking to retain existing model of testing

Existing testing or test via script can be easily adopted with Binnacle. It provides metrics for each tests or script execution.

**Comment by aravindavk** [comment]
Still valid.
