### ISSUE TITLE
Reset sqlite3 db stats when external storage is deleted

### ISSUE THREAD

**Issue by leelavg** [kadalu/kadalu#625]
- Kinda tricky to solve, considering an empty storage pool may not always need to trigger db reset
- Will revisit or if anyone is interested pls pick it up

Edit: We can actually do it if there's availability of ssh key pair but may not be always true

**Comment by leelavg** [comment]
@aravindavk little help here, not able to think through the problem and side effects.

1. `stat.db` is created on external gluster volume and PVCs are carved from this storage pool
2. just before deletion of external pool all PVCs are deleted and so pv_records in `stat.db` should be empty and only table with pool name and summary exists

Ask:
1. If a new `stat.db` is created with same or different pool name will there be any consequences?
2. In internal gluster, we are deleting the brick itself so kadalu metadata will be erased and is it good (or must?) to have a similar functionality with external gluster as well?

**Comment by aravindavk** [comment]
How about documenting the steps while adding external Storage.

- Delete any previously created/used PVs directories.
- Delete the meta details files from the Volume.

**Comment by leelavg** [comment]
- ya, that's also a possibility and a better choice too, will do that.
