### ISSUE TITLE
Release Changes

### ISSUE THREAD

**Issue by aravindavk** [kadalu/kadalu#648]
As we are approaching Version 1 of this project, we need to adapt to a predictable release cycles.

- Change release versions from 0.8.5, 0.8.6, 0.8.7... to 0.9.0, 0.10.0, 0.11.0... and follow `MAJOR.MINOR.PATCH` format.
- Create a Branch for each major and minor versions. Update the release CI to handle this change.
- After Major version 1, no breaking change between minor releases. Breaking changes should be handled automatically or Upgrade guide should mention that explicitly.
- No new features for Patch versions.
- Minor release once a month and patch release every week. Reduce release frequency after the 1.0 release.
- No patch versions for previous releases till 1.0, after that depends on the release cycle.
- Versioned documentation support. Till 1.0, Last two releases documentation will be published/maintained.

Please add if I missed any points.

**Comment by aravindavk** [comment]
Changelog automation: Every patch that adds new feature should add a changelog file under changelogs directory. First line should be the title explaining the change. Leave one line and then add the description in Markdown format. For example,

```md
My Awesome feature

This adds a awesome feature to Kadalu.
```

Release automation picks all the changelog files from the directory and publishes the release notes.

**Comment by amarts** [comment]
Not just in kadalu/kadalu repo, but even in kadalu/glusterfs repo, we need to follow the same method for branches which are used by kadalu.

My take is, soon we need to rebase to latest glusterfs (say once we branch to glusterfs-10).
