### ISSUE TITLE
Failed to provision volume with StorageClass "kadalu.replica3"

### ISSUE THREAD

**Issue by hetii** [kadalu/kadalu#65]
Hi,
I try to setup kadalu on aks cluster but csi-provisioner raise error like:

    Warning  ProvisioningFailed    3s                 kadalu_csi-provisioner-0_27e261cc-0c6d-11ea-a863-7ec92e551436  failed to provision volume with StorageClass "kadalu.replica3": rpc error: code = Unknown desc = Exception calling application: [Errno 17] File exists: '/mnt/kadalu-storage-replica-pool-3'

Details:

    I1121 14:50:40.022459       1 controller.go:926] provision "default/kadalu-pvc" class "kadalu.replica3": started
    I1121 14:50:40.028583       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"kadalu-pvc", UID:"40c1247f-75dd-43da-b304-ed200e5874dd", APIVersion:"v1", ResourceVersion:"238587", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/kadalu-pvc"
    W1121 14:50:40.033254       1 controller.go:685] Retrying syncing claim "default/kadalu-pvc" because failures 5 < threshold 15
    E1121 14:50:40.033333       1 controller.go:700] error syncing claim "default/kadalu-pvc": failed to provision volume with StorageClass "kadalu.replica3": rpc error: code = Unknown desc = Exception calling application: [Errno 17] File exists: '/mnt/kadalu-storage-replica-pool-3'
    I1121 14:50:40.033410       1 event.go:221] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"kadalu-pvc", UID:"40c1247f-75dd-43da-b304-ed200e5874dd", APIVersion:"v1", ResourceVersion:"238587", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "kadalu.replica3": rpc error: code = Unknown desc = Exception calling application: [Errno 17] File exists: '/mnt/kadalu-storage-replica-pool-3'

    [2019-11-21 14:58:40,050] DEBUG [controllerserver - 42:CreateVolume] - Filters applied to choose storage   hostvol_type=Replica3
    [2019-11-21 14:58:40,051] DEBUG [controllerserver - 47:CreateVolume] - Got list of hosting Volumes   volumes=kadalu-storage-replica-pool-3
    [2019-11-21 14:58:40,051] ERROR [_server - 445:_call_behavior] - Exception calling application: [Errno 17] File exists: '/mnt/kadalu-storage-replica-pool-3'
    Traceback (most recent call last):
      File "/usr/local/lib64/python3.7/site-packages/grpc/_server.py", line 435, in _call_behavior
        response_or_iterator = behavior(argument, context)
      File "/kadalu/controllerserver.py", line 50, in CreateVolume
        hostvol = mount_and_select_hosting_volume(host_volumes, pvsize)
      File "/kadalu/volumeutils.py", line 122, in mount_and_select_hosting_volume
        mount_glusterfs(hvol, mntdir)
      File "/kadalu/volumeutils.py", line 420, in mount_glusterfs
        os.makedirs(target_path, exist_ok=True)
      File "/usr/lib64/python3.7/os.py", line 221, in makedirs
        mkdir(name, mode)
    FileExistsError: [Errno 17] File exists: '/mnt/kadalu-storage-replica-pool-3'

My test configuration:

    ---
    apiVersion: kadalu-operator.storage/v1alpha1
    kind: KadaluStorage
    metadata:
      # This will be used as name of PV Hosting Volume
      name: kadalu-storage-replica-pool-3
    spec:
      type: Replica3  # Notice that this field tells kadalu operator to use replicate module.
      storage:
        - node: aks-aks-35064155-0
          path: /mnt
        - node: aks-aks-35064155-1
          path: /mnt
        - node: aks-aks-35064155-2
          path: /mnt
    ---
    kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: kadalu-pvc
    spec:
      storageClassName: kadalu.replica3
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 5Gi
    ---
    apiVersion: v1
    kind: Pod
    metadata:
      name: volume-kadalu-access-pod
    spec:
      volumes:
      - name: kadalu-pvc-volume
        persistentVolumeClaim:
          claimName: kadalu-pvc
      containers:
      - name: alpine
        image: ubuntu
        command: ['sh', '-c', 'while true; do sleep 3;done']
        volumeMounts:
        # Configuration volumes:
        - name: kadalu-pvc-volume
          mountPath: /mnt/kadalu-pvc-volume

I login into each of my aks node and there is not /mnt/kadalu-storage-replica-pool-3 directory path.
I also change the paths in KadaluStorage /mnt to be like /mnt/aaa, /mnt/bbb, /mnt/ccc, and start from clean environment, but the error is still the same.

**Comment by aravindavk** [comment]
@fs-system this looks like the same issue which you observed. Are you planning to send PR?

**Comment by amarts** [comment]
@hetii thanks for the report... we will look into this soon, and get back to you.

**Comment by hetii** [comment]
@amarts No problem, I can help you somehow but just start digging into your code.
Even when I start from scratch and use device block like device: /dev/sdb1 container kadalu-provisioner from csi-provisioner-0 persist to create directory like /mnt/kadalu-storage-replica-pool-3 and as probably this is already a file then traceback happen.

I have no clue with filesystem it is as /mnt in csi-provisioner-0 is empty o_0, as well as in other kadalu component or even node agent.

Edit:
I just notice that csi-provisioner use args like --provisioner=kadalu --csi-address=/var/lib/csi/sockets/pluginproxy/csi.sock and csi.sock is mounted like `/dev/sda1 on /var/lib/csi/sockets/pluginproxy type ext4 (rw,relatime,discard,data=ordered)` 
So this is as I assume a target filesystem.

**Comment by amarts** [comment]
Fix available with #71
