### ISSUE TITLE
glusterfs: logs of /proc/0/status file not found

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#651]
These logs are found consistently in glusterfs client logs. Need to be checked and resolved.

**Comment by amarts** [comment]
#540 is closed as it was focused on the 'crash' after the log, which is now resolved.

**Comment by leelavg** [comment]
Attaching the logs from a clean setup which were shared long back in slack
[gluster.log](https://github.com/kadalu/kadalu/files/7134528/gluster.log)
[server-replica3-2-0.log](https://github.com/kadalu/kadalu/files/7134529/server-replica3-2-0.log)
[server-replica3-1-0.log](https://github.com/kadalu/kadalu/files/7134530/server-replica3-1-0.log)
[server-replica3-0-0.log](https://github.com/kadalu/kadalu/files/7134531/server-replica3-0-0.log)
