### ISSUE TITLE
Kadalu csi driver performance in context of kernel < 4.17

### ISSUE THREAD

**Issue by hetii** [kadalu/kadalu#66]
Hello.
As I play strongly about rook vs kadalu setup I notice that CSI driver in rook are affected by very low performance bug describe in [rook github](https://github.com/rook/rook/issues/3315). 

To solve that they require to switch to kernel >= 4.17 that support [quotas](https://docs.ceph.com/docs/master/cephfs/kernel-features/#quotas).

Unfortunate azure just have in plans to upgrade theirs kernels, as we can read [ here](https://feedback.azure.com/forums/914020-azure-kubernetes-service-aks/suggestions/37169017-use-kernel-4-18-in-aks-to-solve-cfs-throttling-iss)

So is it something to worry regarding kernel < 4.17 and kadalu?

**Comment by amarts** [comment]
@hetii Thanks for raising this issue. IMO, this shouldn't matter much for us, as quotas are offloaded to backend brick (xfs) in kadalu setup. If it was pure fuse module issue, then yes, there was a possibility of having impact, but it doesn't look like.

**Comment by amarts** [comment]
@hetii we will be treating this as closed. If you find any issues with v0.3 or above (ie, latest as of 26/11/2019), lets reopen this issue.
