### ISSUE TITLE
storage-remove failed

### ISSUE THREAD

**Issue by zhucan** [kadalu/kadalu#672]
After server-storage-pool**** crashed, exec "storage-remove" the pod and storage was not deleted.

storage-pool3 exists and crash
![image](https://user-images.githubusercontent.com/13997135/137665015-8509baf4-f900-45ba-b03a-4181c840239d.png)

No resouce found with cmd "kubectl get kadalustorages.kadalu-operator.storage"
![image](https://user-images.githubusercontent.com/13997135/137665103-8270c69b-b173-40ee-8d7a-f8137c23ac34.png)

**Comment by zhucan** [comment]
kadalu version is v0.8.4

**Comment by leelavg** [comment]
1. There might be some PVCs from the crashed pool and so `kds (kadalustorages)` CR states pool is deleted (from k8s perspective) but the corresponding `sc` will not be deleted, the same can be found from `kubectl get sc`
2. Please have a look at operator logs and that'll log the reason why it isn't able to remove the storage pool sts
3. Workaround should be re-apply the pool manifest, remove the PVCs which were carved from this and then delete the pool.

**Comment by zhucan** [comment]
There is no pvc in the storage pool, I will take a look at the code.

**Comment by zhucan** [comment]
![image](https://user-images.githubusercontent.com/13997135/137666338-5e661142-daf8-442c-b32f-394b5dcf1a01.png)
Because of the counts of the pvc is -1.

How to reproduce:
storage-add with a not exists  device.
![image](https://user-images.githubusercontent.com/13997135/137666560-a10b8e44-6285-4b62-8f4e-dc24a7d21202.png)

**Comment by leelavg** [comment]
- I remember handling that case as well https://github.com/kadalu/kadalu/blob/60567e9270eae8a2afc9e8e6563320d2463b3549/operator/main.py#L728-L742
- Can you please provide that specific pool, operator logs and applied pool manifest?

**Comment by leelavg** [comment]
@zhucan 
- sry, I overlooked the version that you provided (v0.8.4)
- above fix went into v0.8.5, pls upgrade and no need to provide any log

**Comment by zhucan** [comment]
@leelavg Thanks
