### ISSUE TITLE
Add debug stats/logs for all kadalu pods to ask user for easy reference 

### ISSUE THREAD

**Issue by vatsa287** [kadalu/kadalu#675]
Since Kadalu already has logs option making users easier and faster for debug. It would be better to include kadalu version info as well to it.
Quote by @amarts:
"_@aravindavk @leelavg can we get commands common for diagnosing into kubectl kadalu debug or something similar, so instead of asking all these question, we ask users to share output of this one command, which would capture logs, get version info, and more so its easier ?_ "

**Comment by leelavg** [comment]
- This alone doesn't fix version issues, will reopen and add the comments

**Comment by leelavg** [comment]
- @aravindavk can kadalu cli be embedded into operator also?
- it's better to add something like `k kadalu debug` which confirms the user's that specific logs and list of pools/sc/pvcs is collected.
- then we can ask the user to add these while creating an issue. 

@vatsa287 one edge case, let's say
- Someone inform that they built containers off of devel but they mistook old commit as HEAD
- In that scenario there'll be a confusion, what'd be the best way to collect version?
