### ISSUE TITLE
Update to 0.8.7 fails in OKD4

### ISSUE THREAD

**Issue by marcusaram** [kadalu/kadalu#685]
I'm trying to update Kadalu on OKD4, currently running 0.8.6 operator with csi-node 0.8.6. When I try to update the operator to 0.8.7 I get the following error (in a loop):

```
[2021-11-02 21:25:21,472] INFO [main - 936:deploy_config_map] - Found existing configmap. Updating	 name=kadalu-info
[2021-11-02 21:25:21,484] INFO [main - 958:deploy_config_map] - ConfigMap Deployed	 manifest=/kadalu/templates/configmap.yaml uid=274bff60-41f8-4dba-aa51-268a6bb7e1a4 upgrade=True
Traceback (most recent call last):
  File "/kadalu/main.py", line 1029, in <module>
    main()
  File "/kadalu/main.py", line 1005, in main
    deploy_csi_pods(core_v1_client)
  File "/kadalu/main.py", line 898, in deploy_csi_pods
    int_api_instance_minor = int(api_instance.minor)
ValueError: invalid literal for int() with base 10: '21+'
[2021-11-02 21:25:21,756] INFO [kadalulib - 403:monitor_proc] - Restarted Process	 name=operator
```
The error is not very helpful to see what is wrong in the kadalu-info config map.

**Comment by marcusaram** [comment]
I did a quick check. I guess that this has to do with the API major and minor versions. Seems that these are not only int on OKD.

This is my version
```
Client Version: 4.8.13
Server Version: 4.8.0-0.okd-2021-10-24-061736
Kubernetes Version: v1.21.2-1505+6438632813d726-dirty
```

**Comment by vatsa287** [comment]
I think “ int_api_instance_minor = int(float(api_instance_minor)) “ would solve this.

**Comment by leelavg** [comment]
@vatsa287
- that'll not work, here the issue is we are getting `21+` as minor version and float conversion also would fail
- either we need to extract digits out of the string or trim endings with `+` 
``` python
>>> '21+'.strip('+')
'21'

# or

>>> reg = re.compile(r'\d+')
>>> reg.search('21+').group()
'21'
```
- OKD version output skipped our minds 😞 

@marcusaram below would be the quick workaround, pardon the inconvenience.

```
-> k exec -it deploy/operator -n kadalu -- sed -e -i 's/api_instance.minor/api_instance.minor.strip('+')/g' /kadalu/main.py
```

**Comment by aravindavk** [comment]
@vatsa287 I think you can keep it as string itself instead of typecasting.

```
major, minor, patch = ver.split(".", 3)
```

Comparisons also work fine with strings

```
>>> "2-1505+6438632813d726-dirty" > "2"
True
>>> "2-1505+6438632813d726-dirty" > "2-14"
True
>>> "2-1505+6438632813d726-dirty" > "2-16"
False
>>> "2-1505+6438632813d726-dirty" > "2-1505+6438632813d727-dirty"
False
>>> "2-1505+6438632813d726-dirty" > "2-1505+6438632813d725-dirty"
True
```

**Comment by leelavg** [comment]
@aravindavk a little bit confused about usage of `ver.split` we actually get a class (from `client.VersionApi().get_code()`) which has `major` and `minor` attrs as a property.

IMHO, they are actually numbers and should be dealt as such. We aren't concerned about 'patch' and subsequent fields in semver.

So, I still believe we need to extract digits part from `minor` and `major` and compare them as ints, what do you say?

**Comment by marcusaram** [comment]
@leelavg Thanks for your quick reply. Since this cluster is also running production workload I will try to update kadalu in the next maintenance window. If you need some more information, just ask. Thanks for this great product. It should have more exposure for sure!

**Comment by leelavg** [comment]
- thanks for the feedback and passing on kudos to authors/maintainers of Kadalu

> I will try to update kadalu in the next maintenance window

- This worries me a bit, as the process in operator keeps on restarting it'll consume a lot of CPU cycles.
- Above workaround can be applied on a stage environment and can be applied to prod without any maintenance/downtime.

Edit: The way it's designed, above workaround will take into effect without any pod/container restarts 😄

**Comment by amarts** [comment]
> So, I still believe we need to extract digits part from minor and major and compare them as ints, what do you say?

While that may be one way, I believe for the lifetime of kadalu, and where we compare the k8s versions, I believe the string based comparison is good enough. We can add a comment saying it is compared in strings only to make sure we take care of OKD and other similar ecosystems.

No point in spending extra effort to crack our head around converting something from string to integer and getting into issues. If it was expected to be integer, k8s itself would have sent it as numbers. Lets just keep this as string comparison and make a release.

My personal opinion is there may be 10s/100s of different of ways to solve a problem, but we should pick something which helps the users, with less burden on 'maintenance'. IMO, as @aravindavk shared example, strings would do the job, lets keep to it till it is broken there.
