### ISSUE TITLE
Error calling metrics endpoint from k3s cluster within LXC/LXD infra 

### ISSUE THREAD

**Issue by vherrlein** [kadalu/kadalu#687]
https://github.com/kadalu/kadalu/blob/ffe706aeaa87d3f512961bfd36dfa1a7597485d7/operator/exporter.py#L175

In my case, unfortunately,  cgroups "cpuacct.usage" and "memory.usage_in_bytes" are not available, meaning throwing an 500 Internal Error from the webpage and the following error message in logs.
```
ERROR [httptools_impl - 378:run_asgi] - Exception in ASGI application
Traceback (most recent call last):
  File "/kadalu/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/kadalu/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/kadalu/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/kadalu/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/kadalu/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/kadalu/exporter.py", line 362, in collect_metrics
    collect_and_set_prometheus_metrics()
  File "/kadalu/exporter.py", line 291, in collect_and_set_prometheus_metrics
    metrics = collect_all_metrics()
  File "/kadalu/exporter.py", line 253, in collect_all_metrics
    set_operator_data(metrics)
  File "/kadalu/exporter.py", line 182, in set_operator_data
    with open(memory_usage_file_path, 'r') as memory_fd:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/fs/cgroup/memory/memory.usage_in_bytes'
```

**Comment by vherrlein** [comment]
this is the list of cgroups available
```
/ $ ls /sys/fs/cgroup
cgroup.controllers        cgroup.type               cpuset.cpus.effective     hugetlb.1GB.rsvd.max      io.stat                   memory.numa_stat          pids.events
cgroup.events             cpu.max                   cpuset.cpus.partition     hugetlb.2MB.current       io.weight                 memory.oom.group          pids.max
cgroup.freeze             cpu.pressure              cpuset.mems               hugetlb.2MB.events        memory.current            memory.pressure           rdma.current
cgroup.max.depth          cpu.stat                  cpuset.mems.effective     hugetlb.2MB.events.local  memory.events             memory.stat               rdma.max
cgroup.max.descendants    cpu.uclamp.max            hugetlb.1GB.current       hugetlb.2MB.max           memory.events.local       memory.swap.current
cgroup.procs              cpu.uclamp.min            hugetlb.1GB.events        hugetlb.2MB.rsvd.current  memory.high               memory.swap.events
cgroup.stat               cpu.weight                hugetlb.1GB.events.local  hugetlb.2MB.rsvd.max      memory.low                memory.swap.high
cgroup.subtree_control    cpu.weight.nice           hugetlb.1GB.max           io.max                    memory.max                memory.swap.max
cgroup.threads            cpuset.cpus               hugetlb.1GB.rsvd.current  io.pressure               memory.min                pids.current
```

**Comment by leelavg** [comment]
@vherrlein a little bit confused here and I only have a minimum knowledge on lxd (system) containers. 

1. We are using `debian:bullseye` as base image which by default has a cgroup v2 hierarchy. 
2. Afaik, lxc uses some customised fs (lxcfs i guess) to be able to support hybrid mode when docker containers are run on them.
3. So, the question is, is it safe to assume that above files will always not be available on lxd infra even with tweaking?

**Comment by vherrlein** [comment]
@leelavg , just for your information my Kubernetes cluster : 
1. Kubernetes version: K3S v1.21 
2. 3 Nodes (1 master + 2 workers)
3. Nodes under LXC Containers in priviledged mode with some tweaks for containerd
4. Hosted into an hypervisor, a Proxmox 7.0 Cluster of 3 nodes
5. 1 k3s node per machine

For your information, it seems the Proxmox 7.0 is running under "debian:bullseye" but with custom kernel which doesn't enable CGroupv2 Hierarchy.

May be I could trick it with an LXC setting (https://wiki.debian.org/LXC/CGroupV2).
I'll keep you informed of my progress.

However, that would be great to handle that kind of case within your exporter in order to avoid HTTP 500 errors.
May be having a warning message and forcing cpu and memory metrics being null.

**Comment by leelavg** [comment]
- Thanks for all the info
- Definitely, HTTP 500 will be handled gracefully and/or we'll try to get metrics from any other place if possible 🤔

**Comment by amarts** [comment]
@leelavg++

Lets first fix the backtraces and push them into another release, so users are not having issues. We will improve on better approaches later.
