### ISSUE TITLE
Is it possible to mount the GlusterFS volume into the host as a folder?

### ISSUE THREAD

**Issue by bodleytunes** [kadalu/kadalu#700]
Hi All,

Is it possible to mount what would normally be a glusterfs volume only accessible to the k3s cluster directly to the host so I could copy files there and they would be available to the pods?

I have setup glusterFS before directly on the hosts (manually) which enabled me to copy files to the mounted volume (mounted with fstab and glusterfs client) and then I just bind mounted to the pods as a folder, but I was wondering if this system whereby the k3s cluster is looking after creating volumes and mounting them into pods could also be accessible from the "outside" so to speak?

Many thanks,
Jon.

**Comment by aravindavk** [comment]
This is one feature asked by many users. Technically it is possible to mount the Volume on host if all the Server Pods IPs are reachable in host.

I think, we can introduce a kubectl sub-command to mount the Volume in the host machine.

```
kubectl kadalu mount <storage-pool-name> <mount-point>
```

- Generate the Client Volfile for the given Storage pool name(Accept Volume Options in CLI as well)
- Run Glusterfs command to mount the Volume.(Validate the compatible Gluster version and Storage pods should be reachable by host)

If storage pods are not reachable by the same name `<pod-name>.<volume>.<namespace>` then accept the hostname mapping in CLI.

@amarts ^^

**Comment by amarts** [comment]
Any glusterfs client should work in this case as we haven't done any changes in client side stack. 

Good start IMO.
