### ISSUE TITLE
kadalu 0.8.7 fails to work correctly after worker node is reprovisioned

### ISSUE THREAD

**Issue by RomanKisilenko** [kadalu/kadalu#702]
Reprovisioning worker node have lead to the gluster folder being cleared.

After connecting the node to cluster kadalu fails to provision any pvcs and it also fails to remove the storage class (KadaluStorage).

Fully removing kadaly, storageclass and then reinstalling kadalu from scratch did work but this is not something which can be done in production.

**Comment by hunter86bg** [comment]
Do we have any update for this ine ?

**Comment by leelavg** [comment]
- Uh oh missed this
- Isn't it the same one that you mention to create same directories from two app pods using same pvc as a repro @hunter86bg ?

**Comment by hunter86bg** [comment]
It looks more like the case we use via 'replace-brick' in non-container world (host is dead, reinstall and recover the redundancy).
