### ISSUE TITLE
Metrics - Wrong PVC usage values

### ISSUE THREAD

**Issue by vherrlein** [kadalu/kadalu#709]
When you are running a storage pool in 'PATH' mode, metrics sent by the CSI exporter are wrong and calculate the size based on the file system mount point instead of the PVC Directory.

https://github.com/kadalu/kadalu/blob/9c9625aba981948ffae868748f1f828531dc7266/csi/exporter.py#L111

The main culprit is `os.statvfs` which get information of the filesystem mount point related to the path provided as argument.
(cf. https://docs.python.org/3/library/os.html?highlight=statvfs#os.statvfs)

For a better compatibility across setups (Path or Volume) for PVC, the following metrics could be retrieved as following:
- **total_pvc_capacity_bytes** : Capacity property of the related PVC (spec.resources.requests.storage) coming from `kubectl get pvc -A -o json`
- **used_pvc_capacity_bytes** : Calculation of the PVC directory recursively by `os.scandir` and `os.stat().st_size`.
Exemple:
```python
used_pvc_capacity_bytes = 0
for p in os.scandir(pvcpath):
	used_pvc_capacity_bytes+=os.stat(p).st_size
```
- **free_pvc_capacity_bytes** : Calculation with `total_pvc_capacity_bytes - used_pvc_capacity_bytes`

Thank you in advance.
Regards,

**Comment by amarts** [comment]
the `statvfs()` call takes path as an argument, and gets the details of given directory. With glusterfs, we try to provide statvfs output at the simple-quota level, which gets handled properly on client, and you are supposed to get the proper usage without doing a recursive crawl. If that is not happening, then there seems to be a bug in glusterfs, and that needs to be checked. Doing a recursive crawl needs to be avoided unless absolutely required, as it has a serious performance cost on whole storage cluster.

**Comment by leelavg** [comment]
hi @vherrlein 

- thanks a lot for your debug analysis.
- we could also get usage of PVC irrespective of path/device mode based on xattrs (`trusted.gfs.squota.size`) rather than cumulative sum of recursion 🤔 
- we'll try to minimise the PR content seeing the issues in metrics, good learning.

**Comment by vatsa287** [comment]
PVC Inode and storage Inode data looks the same: 
```
{
  "operator": {
    "memory_usage_in_bytes": 118865920,
    "cpu_usage_in_nanoseconds": 25686075064,
    "pod_name": "operator-7dfcc8fb86-xb482",
    "ip_address": "172.17.0.2",
    "pod_phase": "Running",
    "total_number_of_containers": 1,
    "number_of_ready_containers": 1,
    "containers": [
      {
        "container_name": "kadalu-operator",
        "is_ready": true,
        "is_started": true,
        "start_time": "2021-11-22T06:57:26Z"
      }
    ]
  },
  "storages": [
    {
      "name": "storage-pool-1",
      "type": "Replica2",
      "total_capacity_bytes": 982900588544,
      "free_capacity_bytes": 902531317760,
      "used_capacity_bytes": 80369270784,
      "total_inodes": 61022208,
      "free_inodes": 60383768,
      "used_inodes": 638440,
      "pvc": [
        {
          "pvc_name": "pvc-5df508e4-a1aa-457c-bb66-99b6c2358fa3",
          "total_pvc_capacity_bytes": 104861696,
          "free_pvc_capacity_bytes": 104861696,
          "used_pvc_capacity_bytes": 0,
          "total_pvc_inodes": 61022208,
          "free_pvc_inodes": 60383768,
          "used_pvc_inodes": 638440
        }
      ],
      "bricks": [
        {
          "brick_path": "/bricks/storage-pool-1/data/brick",
          "kube_hostname": "thinkpad",
          "node": "server-storage-pool-1-0-0.storage-pool-1",
          "node_id": "node-0",
          "host_brick_path": "/mnt/disk1",
          "brick_device": "",
          "pvc_name": "",
          "brick_device_dir": "",
          "decommissioned": "",
          "brick_index": 0,
          "pod_phase": "Running",
          "memory_usage_in_bytes": 7436451840,
          "cpu_usage_in_nanoseconds": 10369346458220,
          "ip_address": "172.17.0.5",
          "total_number_of_containers": 1,
          "number_of_ready_containers": 1,
          "containers": [
            {
              "container_name": "server",
              "is_ready": true,
              "is_started": true,
              "start_time": "2021-11-22T06:58:05Z"
            }
          ]
        },
        {
          "brick_path": "/bricks/storage-pool-1/data/brick",
          "kube_hostname": "thinkpad",
          "node": "server-storage-pool-1-1-0.storage-pool-1",
          "node_id": "node-1",
          "host_brick_path": "/mnt/disk2",
          "brick_device": "",
          "pvc_name": "",
          "brick_device_dir": "",
          "decommissioned": "",
          "brick_index": 1,
          "pod_phase": "Running",
          "memory_usage_in_bytes": 7436451840,
          "cpu_usage_in_nanoseconds": 10369349355654,
          "ip_address": "172.17.0.6",
          "total_number_of_containers": 1,
          "number_of_ready_containers": 1,
          "containers": [
            {
              "container_name": "server",
              "is_ready": true,
              "is_started": true,
              "start_time": "2021-11-22T06:58:13Z"
            }
          ]
        }
      ]
    }
  ],
  "provisioner": {
    "pod_phase": "Running",
    "pod_name": "kadalu-csi-provisioner-0",
    "memory_usage_in_bytes": 82092032,
    "cpu_usage_in_nanoseconds": 15915090920,
    "ip_address": "172.17.0.4",
    "total_number_of_containers": 5,
    "number_of_ready_containers": 5,
    "containers": [
      {
        "container_name": "csi-attacher",
        "is_ready": true,
        "is_started": true,
        "start_time": "2021-11-22T06:58:17Z"
      },
      {
        "container_name": "csi-provisioner",
        "is_ready": true,
        "is_started": true,
        "start_time": "2021-11-22T06:58:05Z"
      },
      {
        "container_name": "csi-resizer",
        "is_ready": true,
        "is_started": true,
        "start_time": "2021-11-22T06:58:48Z"
      },
      {
        "container_name": "kadalu-logging",
        "is_ready": true,
        "is_started": true,
        "start_time": "2021-11-22T06:58:44Z"
      },
      {
        "container_name": "kadalu-provisioner",
        "is_ready": true,
        "is_started": true,
        "start_time": "2021-11-22T06:58:29Z"
      }
    ]
  },
  "nodeplugins": [
    {
      "pod_name": "kadalu-csi-nodeplugin-dfvp4",
      "pod_phase": "Running",
      "memory_usage_in_bytes": 67502080,
      "cpu_usage_in_nanoseconds": 8606210503,
      "ip_address": "172.17.0.7",
      "total_number_of_containers": 3,
      "number_of_ready_containers": 3,
      "containers": [
        {
          "container_name": "csi-node-driver-registrar",
          "is_ready": true,
          "is_started": true,
          "start_time": "2021-11-22T06:58:21Z"
        },
        {
          "container_name": "kadalu-logging",
          "is_ready": true,
          "is_started": true,
          "start_time": "2021-11-22T06:58:48Z"
        },
        {
          "container_name": "kadalu-nodeplugin",
          "is_ready": true,
          "is_started": true,
          "start_time": "2021-11-22T06:58:32Z"
        }
      ]
    }
  ]
}
```

**Comment by leelavg** [comment]
@vherrlein 

- do you have any posts/steps referring to your setup mentioned in https://github.com/kadalu/kadalu/issues/687#issuecomment-960622581?
- running k3s in a system container (lxd) might be quite different if we are touching the filesystem directly

**Comment by vherrlein** [comment]
@amarts, Agreed on the performance perspective.

So, in my case it seems the "simple-quota" doesn't work at all.
@leelavg, the issue with `xattrs` seems not working well in within LXC/LXD priviledged container.

**Comment by vherrlein** [comment]
@leelavg, I did the full setup by myself, no posts or full guidelines exits online :/

**Comment by leelavg** [comment]
- Ack, it might be a bit difficult to fix customised setup issues as it might break something else in the same/different infra.
- By no means I'm against supporting the usecase, I'm just saying it'll be easier if we have a reference which reduces to and fro 😀
- I'm not a fan of snap 😅 to setup lxd in fedora, will look for alternatives and see how the filesystem is laid out in system containers. 
- So, pls expect a delayed response.

Edit: I use k3d which is also docker in docker and didn't face any xattr issues so far. Since lxd provides different internals, need to see how it goes 😅

**Comment by vherrlein** [comment]
@leelavg, if you have any python script to test, I could try within my environment.

I understand that's not easy to identify as everyone have different setups with different distros.

In my case:
- Host machine: 
  - Debian Bullseyes based (Proxmox VE 7.0)
  - LXC v4.0.9-4
  - Additional Kernel Modules loaded at startup (/etc/modules):
```
br_netfilter
overlay
aufs
ip_vs
nf_nat
xt_conntrack
```
- LXC Guest Machine: 
  - Pure Debian Bullseyes
  - LXC extra settings:
```
lxc.apparmor.profile: unconfined
lxc.cgroup.devices.allow:
lxc.cgroup.devices.deny:
lxc.cap.drop:
lxc.mount.auto: "proc:rw sys:rw cgroup:rw:force"
```

**Comment by leelavg** [comment]
- Thanks a lot for the info
- We don't have any python script, Kadalu itself has some checks inbuilt for it to work 
- Metrics might be coming into your way of using Kadalu i guess or were you able to create PVC and use it in app pod?
- I think we can provide an option to disable metrics 🤔

**Comment by vherrlein** [comment]
From my side, I need metrics to monitor the infra.

My target is retrieving all of those metrics:
- Gluster Stats:
  - Status (based on the Quorum and/or Pods states)
  - Availability (SLA)
  - Avg Network Latency
  - Avg I/O Read/Write speed (Bytes/s)
- Storage Pool Stats:
  - Type of replica
  - Status
  - Size
  - Remaining Space
  - I/O Read/Write speed (Bytes/s)
- PVC Stats:
  - Requested Size
  - % Used
  - Status 

Currently, I'm trying to make a dashboard on Grafana which looks like so for my homelab:
![image](https://user-images.githubusercontent.com/24614045/143677064-70d4bbfb-2ac3-4f9f-9777-d9ba026e4b06.png)

**Comment by leelavg** [comment]
- Uh oh, your main use case seems to be around monitoring
- Need to prioritise this as well i guess, wrt metrics are you good enough with the available metrics that Kadalu exports if all things work correctly?
- @vatsa287 since you are on Ubuntu can you give a try with lxd, no need to setup k8s and kadalu etc, just look around the filesystem whether all the files specified in metrics are accessible if you have bandwidth 

> So, in my case it seems the "simple-quota" doesn't work at all.
@leelavg, the issue with xattrs seems not working well in within LXC/LXD priviledged container

@vherrlein what exactly isn't working? If you are able to create PVC let's say 1G are you able to write more than 1G without expanding the PVC?

**Comment by vherrlein** [comment]
> Uh oh, your main use case seems to be around monitoring

Monitoring at first glance, then alerting :)

> Need to prioritise this as well i guess, wrt metrics are you good enough with the available metrics that Kadalu exports if all things work correctly?

1. As soon as `total_pvc_capacity_bytes`, `used_pvc_capacity_bytes` and `free_pvc_capacity_bytes` metrics will work fine I could manage storage space's KPIs
2. For now, Kadalu doesn't export I/O Stat metrics which will be useful for analyzing later on performances or even troubleshooting (Storage and Network)

> what exactly isn't working? 

Only metrics coming from exporters which doesn't work as expected ( `total_pvc_capacity_bytes`, `used_pvc_capacity_bytes`, `free_pvc_capacity_bytes`).
All the rest works well.

> If you are able to create PVC let's say 1G are you able to write more than 1G without expanding the PVC?

I will try then keep you posted.

**Comment by leelavg** [comment]
@vherrlein 

- we made last 2 releases to fix monitoring issues, however some issues is still being hit by you
- can you pls try out devel once and list out what's not working for you and what more metrics are needed

**Comment by vherrlein** [comment]
> If you are able to create PVC let's say 1G are you able to write more than 1G without expanding the PVC?

@leelavg, it seems the quota is working within a pod, below the error I got from a dd write.

`dd: error writing '/mnt/pv/test.img': Disk quota exceeded`

> can you pls try out devel once and list out what's not working for you and what more metrics are needed

I prefer waiting on your next release, it's too risky.
I tried one time using the devel directly and I had some troubles with the existing setup.
