### ISSUE TITLE
Can't create volume after upgrading from 0.8.6 to 0.8.8

### ISSUE THREAD

**Issue by rafis** [kadalu/kadalu#719]
Trying to create simple volume which worked on 0.8.6.

kubectl -n kadalu logs kadalu-csi-provisioner-0 -c kadalu-provisioner
```
[2021-12-01 07:58:33,483] INFO [controllerserver - 296:CreateVolume] - Volume created    name=pvc-85cd7c47-647f-48be-bf1d-80c5230c217f size=21474836480 hostvol=out-dev-gluster pvtype=subvol volpath=subvol/cc/c9/pvc-85cd7c47-647f-48be-bf1d-80c5230c217f duration_seconds=4.545944929122925
[2021-12-01 07:58:33,483] ERROR [_server - 454:_call_behavior] - Exception calling application: None has type NoneType, but expected one of: bytes, unicode
Traceback (most recent call last):
  File "/kadalu/lib/python3.9/site-packages/grpc/_server.py", line 444, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/controllerserver.py", line 309, in CreateVolume
    return csi_pb2.CreateVolumeResponse(
  File "/usr/local/lib/python3.9/_collections_abc.py", line 940, in update
    self[key] = other[key]
TypeError: None has type NoneType, but expected one of: bytes, unicode
```
kubectl -n postgres describe pvc
```
  Type     Reason                Age                   From                                                                  Message
  ----     ------                ----                  ----                                                                  -------
  Warning  ProvisioningFailed    2m17s                 kadalu_kadalu-csi-provisioner-0_4d94c5d5-0ae0-44d7-994a-0234707bd05f  failed to provision volume with StorageClass "kadalu.out-dev-gluster": rpc error: code = InvalidArgument desc = Unable to set Gluster Quota via ssh
  Normal   Provisioning          73s (x8 over 3m46s)   kadalu_kadalu-csi-provisioner-0_4d94c5d5-0ae0-44d7-994a-0234707bd05f  External provisioner is provisioning volume for claim "postgres/postgres2-11-pv-claim"
  Warning  ProvisioningFailed    69s (x7 over 3m40s)   kadalu_kadalu-csi-provisioner-0_4d94c5d5-0ae0-44d7-994a-0234707bd05f  failed to provision volume with StorageClass "kadalu.out-dev-gluster": rpc error: code = Unknown desc = Exception calling application: None has type NoneType, but expected one of: bytes, unicode
  Normal   ExternalProvisioning  11s (x16 over 3m46s)  persistentvolume-controller                                           waiting for a volume to be created, either by external provisioner "kadalu" or manually created by system administrator
```

**Comment by rafis** [comment]
Downgrading to 0.8.6 didn't help, means that's our configuration issue.

**Comment by leelavg** [comment]
@rafis pardon the inconvenience

> Unable to set Gluster Quota via ssh

- Can you look into provisioner logs why it failed to set the quota?

> None has type NoneType, but expected one of: bytes, unicode

- Needs more investigation, is it possible for you to provide applied KadaluStorage yaml manifest?
- Error is in one of these lines (mostly the last one)https://github.com/kadalu/kadalu/blob/c0ba7c0fd795bdc4e2ee2cf6479da1f0115b04f9/csi/controllerserver.py#L318-L321

**Comment by rafis** [comment]
kubectl -n kadalu get kadalustorage out-dev-gluster -o yaml

```
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kadalu-operator.storage/v1alpha1","kind":"KadaluStorage","metadata":{"annotations":{},"name":"out-dev-gluster","namespace":"kadalu"},"spec":{"details":{"gluster_hosts":["10.10.10.12","10.10.10.13","10.10.10.11"],"gluster_options":"log-level=DEBUG","gluster_volname":"kadalu"},"kadalu_format":"native","pvReclaimPolicy":"delete","type":"External"}}
  creationTimestamp: "2021-09-27T09:22:57Z"
  generation: 2
  name: out-dev-gluster
  namespace: kadalu
  resourceVersion: "74342045"
  uid: 421d284a-d1bf-4727-97d1-6f976229c7c0
spec:
  details:
    gluster_hosts:
    - 10.10.10.12
    - 10.10.10.13
    - 10.10.10.11
    gluster_volname: kadalu
  kadalu_format: native
  pvReclaimPolicy: delete
  type: External
```

@leelavg please help.

**Comment by leelavg** [comment]
@rafis ack,

- Found the second issue, that can be confirmed if you do `k get sc kadalu.out-dev-gluster -n kadalu` and look for the **absence** of `gluster_options`
- Not able to find the reason for first issue `Unable to set Gluster Quota via ssh` as mentioned earlier, can you pls look into provisioner logs and search for the same?

**Comment by rafis** [comment]
* Yes, I was trying to delete `gluster_options` from StorageClass `kadalu.out-dev-gluster` to be compatible with the bug #716 in the current kadalu-operator 0.8.8, but it is impossible because StorageClass is immutable resource.

SSH secret seems to be correctly configured
kubectl -n kadalu get secret glusterquota-ssh-secret -o yaml
```
apiVersion: v1
data:
  glusterquota-ssh-username: <secret>
  ssh-privatekey: <secret>
kind: Secret
metadata:
  creationTimestamp: "2021-08-17T10:54:04Z"
  name: glusterquota-ssh-secret
  namespace: kadalu
  resourceVersion: "35883741"
  uid: a5c4f11b-7aa7-4ebd-bf73-73a46fd7da5b
type: Opaque
```
according to documentation
https://github.com/kadalu/kadalu/blob/devel/doc/external-gluster-storage.adoc

But the main issue are not quotas, the main issue is that PersistentVolumes are now not able to create.

**Comment by leelavg** [comment]
> the main issue is that PersistentVolumes are now not able to create

No, Kadalu is able to create PV(C) but failing to communicate the same to kubernetes 😔

**Comment by rafis** [comment]
> No, Kadalu is able to create PV(C) but failing to communicate the same to kubernetes 😔

May be I need to restart something more? My downgrade procedure was very simple:
```
kubectl -n kadalu apply -f https://github.com/kadalu/kadalu/releases/download/0.8.6/kadalu-operator.yaml
```
I have saw that kadalu operator has restarted my `kadalu-csi-provisioner-0` pod automatically afterwards. Maybe I also need to restart all csi-nodeplugins pods manually?

Also I can't disable Quotas checks:
```
# kubectl -n kadalu exec -it kadalu-csi-provisioner-0 -c kadalu-provisioner -- /bin/bash
root@kadalu-csi-provisioner-0:/# setfattr -n glusterfs.quota.disable-check -v "1" /mnt/out-dev-gluster
setfattr: /mnt/out-dev-gluster: Operation not supported
```

We are using standard GlusterFS, not the one that is Kadalu edition. Oracle Linux 7.9, GlusterFS 6.10.

**Comment by rafis** [comment]
Yay! I have returned back `gluster_options` to

kubectl -n kadalu edit kadalustorage out-dev-gluster
kubectl -n kadalu edit configmap kadalu-info

Everything works now as previously.

**Comment by leelavg** [comment]
> My downgrade procedure was very simple

- You didn't apply nodeplugin manifest and downgrades are pretty inconsistent in the first place

> Everything works now as previously.

- I suppose you edited those resources on Kadalu 0.8.6 downgraded setup

> But the main issue are not quotas

- then you shouldn't have seen the quota error

> Also I can't disable Quotas checks

- there's no need to do this afaik

glad, that you have a working setup now but thanks for bringing out these issues.
