### ISSUE TITLE
Enhancement: Add ability to tune gluster volume options

### ISSUE THREAD

**Issue by maxsivkov** [kadalu/kadalu#726]
Gluster has number of [tuning options](https://docs.gluster.org/en/latest/Administrator-Guide/Tuning-Volume-Options/).

Is is possible to specify these options upon volume creation?

There are also possibility to specify group of options (located at `/opt/var/lib/glusterd/groups`

What I'm thinking is to specify `/opt/var/lib/glusterd/groups/db-workload` on particular volume :)

**Comment by aravindavk** [comment]
Related issue: https://github.com/kadalu/kadalu/issues/680

A few selected Volume options will be available with the above issue.
