### ISSUE TITLE
CSI driver registration errors because wrong path of csi.sock

### ISSUE THREAD

**Issue by marcusaram** [kadalu/kadalu#737]
Hello, not really an issues since everything is worker as expected. But I have long time this error on the worker nodes logs. So I figured out what the reason is.

According to https://github.com/kubernetes-csi/node-driver-registrar#usage the path to the csi driver socket is in the wrong path.
The `kadalu-reg.sock` is in the correct folder `/var/lib/kubelet/plugins_registry/` but the `kadalu/csi.sock` of kadalu should not be in `/var/lib/kubelet/plugins_registry/` but in the `/var/lib/kubelet/plugins/` folder as other CSI drivers and these other drivers do not raise these errors. Full path to the CSI driver should be `/var/lib/kubelet/plugins/kadalu/csi.sock`.

I guess that kubelet the CSI driver socket also sees as registration socket and thus try to register and won't work.

Running OKD4.9
Server Version: 4.9.0-0.okd-2021-12-12-025847
Kubernetes Version: v1.22.1-1824+934e08bc2ce38f-dirty

```
Jan 06 13:05:41 worker2 hyperkube[1441]: I0106 13:05:41.102626    1441 reconciler.go:160] "OperationExecutor.RegisterPlugin started" plugin={SocketPath:/var/lib/kubelet/plugins_registry/kadalu/csi.sock Timestamp:2022-01-04 17:57:18.87658108 +0000 UTC m=+14.843640247 Handler:<nil> Name:}
Jan 06 13:05:41 worker2 hyperkube[1441]: E0106 13:05:41.104511    1441 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins_registry/kadalu/csi.sock" failed. No retries permitted until 2022-01-06 13:07:43.104473783 +0000 UTC m=+155439.071532980 (durationBeforeRetry 2m2s). Error: RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins_registry/kadalu/csi.sock, err: rpc error: code = Unimplemented desc = Method not found!
```

**Comment by leelavg** [comment]
@marcusaram 
- yes, this is a know issue, iirc there were some path changes where kubelet looks for both the sock file.
- will re-look into it

**Comment by leelavg** [comment]
- Relooked into it, multiple changes are required to fully fix it
- At the same time outcome doesn't worth the investment, will park the issue here unless any users report a breaking functionality due to this

**Comment by marcusaram** [comment]
@leelavg I understand your outcome, but the problem with this issue is that Kadalu does now not comply with the standards and that may have unexpected behavior in the future. It is possible that something will break in the future. 

Is there anything that I can do to help? Would cause the change some issues on older versions of k8s?

**Comment by leelavg** [comment]
@aravindavk & @amarts 

- Can we drop support for k8s <= v1.17?
- Latest stable release is v1.23 and I vote for dropping support for older versions which could cut off some code.

**Comment by Timoses** [comment]
Can reproduce:
```
192.168.2.37: {"ts":1655136179292.7173,"caller":"goroutinemap/goroutinemap.go:150","msg":"Operation for \"/var/lib/kubelet/plugins_registry/kadalu/csi.sock\" failed. No retries permitted until 2022-06-13 16:05:01.292514228 +0000 UTC m=+1880.258133698 (durationBeforeRetry 2m2s). Error: RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins_registry/kadalu/csi.sock, err: rpc error: code = Unimplemented desc = Method not found!\n"}
192.168.2.36: {"ts":1655136179562.5925,"caller":"goroutinemap/goroutinemap.go:150","msg":"Operation for \"/var/lib/kubelet/plugins_registry/kadalu/csi.sock\" failed. No retries permitted until 2022-06-13 16:05:01.562403402 +0000 UTC m=+1879.961747919 (durationBeforeRetry 2m2s). Error: RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins_registry/kadalu/csi.sock, err: rpc error: code = Unimplemented desc = Method not found!\n"}
192.168.2.38: {"ts":1655136190094.2192,"caller":"goroutinemap/goroutinemap.go:150","msg":"Operation for \"/var/lib/kubelet/plugins_registry/kadalu/csi.sock\" failed. No retries permitted until 2022-06-13 16:05:12.094002509 +0000 UTC m=+1890.682306911 (durationBeforeRetry 2m2s). Error: RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /var/lib/kubelet/plugins_registry/kadalu/csi.sock, err: rpc error: code = Unimplemented desc = Method not found!\n"}
```
