### ISSUE TITLE
Use Type hints for all Python code

### ISSUE THREAD

**Issue by aravindavk** [kadalu/kadalu#74]
Type hints are available in Python 3(https://www.python.org/dev/peps/pep-0484). We can use that in all Python files.

Type hints will not add any runtime overhead, since Type checks to be done with the external tool [mypy](http://mypy-lang.org) (`pip3 install mypy` and check with `mypy <python-file>`)

Example type hints:

```python
def int2str(val: int) -> str:
    if val > 10:
        return val              # Error: Int is returned here
    return "%d" % val

```

**Comment by amarts** [comment]
Should we add these in travis test?

**Comment by aravindavk** [comment]
> Should we add these in travis test?

Yes. along with the pylint tests(https://github.com/kadalu/kadalu/issues/61)

**Comment by aravindavk** [comment]
This is good to have.
