### ISSUE TITLE
How to remove archived volume?

### ISSUE THREAD

**Issue by bazuchan** [kadalu/kadalu#746]
I have configured storage pool with `pvReclaimPolicy: archive`. Created, then deleted pv, now it is archived. How do I remove archived volume to reclaim used space?

**Comment by leelavg** [comment]
@vatsa287 would you be able to work on this?

Provide a cli option which takes pool name and archived pvc name and remove it.

1. Remove the pvc folder 
2. Reduce the size in sqlite db for removed pvc
3. Remove corresponding info file

**Comment by vatsa287** [comment]
@bazuchan Earlier when `pvReclaimPolcy: archive` was written, it was made to avoid unregulated deletes of data. So it would have to be deleted manually.

@leelavg Yea would take this up & it would make handling these cases easier.
