### ISSUE TITLE
[Enhancement] Add possibility to 'retain' volume on delete

### ISSUE THREAD

**Issue by fastlorenzo** [kadalu/kadalu#747]
It would be great to have the possibility to use 'retain' mode in addition to 'delete' and 'archive' when a PV is deleted.

After investigating the code, I think this should only require minor changes.

My example use case would be: I'm using k3d to deploy a k3s cluster, with glusterfs installed on the host. when deleting the cluster, I'd like to keep the data in the original folders on glusterfs (subvol).
This would also require another enhancement: possibility to set the path name pattern for the mount paths (subvol) - similar to how we can do with https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner `pathPattern` option. (cf. #748)

**Comment by leelavg** [comment]
- So you want to use same PVC across k3d reboots?
- I don't think it's easy, yes we can retain pvc but when k3d reboots etcd will also be removed, isn't that the case?

**Comment by fastlorenzo** [comment]
yes, PVC name would be the same across reboots, that's why if the folder names could be determined based on something different than the PV name (which changes as etcd is removed), this would be feasible.
I'm currently doing that with NFS storage, but this is not reliable for some workload as NFS is quite unstable.

**Comment by leelavg** [comment]
Ack, so you meant to say trick k8s to send same name for pvc creation given everything else is predictable?

**Comment by fastlorenzo** [comment]
Well, it's not tricking k8s, I'm using Helm Charts with https://fluxcd.io/ to deploy the workload and configure the cluster, the PVC names are deterministic, they are always the same across every deployment.
Currently with NFS provisioner, I use a path pattern `PVC_NAMESPACE/PVC_NAME`, with a 'retain' option so when the cluster is deleted, the data stays at the same path on the NFS server.
Later when the cluster is re-deployed, the NFS provisioner creates back the PVC and mounts them to the same NFS folders, thus having the data available.
