### ISSUE TITLE
O_DIRECT / DirectIO as StorageClass option or mount option

### ISSUE THREAD

**Issue by netwarex** [kadalu/kadalu#763]
Hi,

I'm new to Kadalu, but I cannot find so far the option for to use DirectIO which is useful database related workloads: https://stackoverflow.com/questions/37892090/enable-direct-i-o-mode-in-glusterfs

Is this somehow manageable to do by Kadalu for a StorageClass or per mounts?

If not, would you consider to add support for that?

Thanks,
Peter

**Comment by leelavg** [comment]
@amarts could you pls help here if possible?

**Comment by amarts** [comment]
@netwarex Can you try the block method of kadalu? This is currently best way to get started...

We are working in glusterfs community to make sure proper caching layers and checks are implemented so DB work load is handled better, but for now, with kadalu, one of the Virtual Block PV is the best way to get started with the database workload

**Comment by netwarex** [comment]
Thanks, I will try that method!
