### ISSUE TITLE
StorageClass reclaimPolicy always set to "delete"

### ISSUE THREAD

**Issue by fastlorenzo** [kadalu/kadalu#765]
It looks like the creation of the storageclass doesn't take into consideration the `pvReclaimPolicy` parameter set in the `KadaluStorage`.

The `storageClass` template doesn't have the `reclaimPolicy` parameter:
https://github.com/kadalu/kadalu/blob/24a634a62949b4e3768cb05e51f209186ac39147/templates/storageclass-kadalu.custom.yaml.j2#L1-L11

The operator should set this in the template when receiving the request: 
https://github.com/kadalu/kadalu/blob/24a634a62949b4e3768cb05e51f209186ac39147/operator/main.py#L1027-L1029

Taking the value from `obj["spec"].get("pvReclaimPolicy", "delete")` should work.

# KadaluStorage

```yaml
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  creationTimestamp: "2022-02-17T14:31:55Z"
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: core
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: local-ssd-1
  namespace: kadalu
  resourceVersion: "192668056"
  uid: 343a1f9f-6200-41e2-b05c-702354e9e958
spec:
  kadalu_format: native
  pvReclaimPolicy: retain
  storage:
  - device: /dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:2:1.0-scsi-0:0:0:0-part3
    node: k8s-01
  - device: /dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:2:1.0-scsi-0:0:0:0-part3
    node: k8s-02
  - device: /dev/disk/by-path/platform-fd500000.pcie-pci-0000:01:00.0-usb-0:2:1.0-scsi-0:0:0:0-part3
    node: k8s-03
  type: Replica3
  volume_id: 4521bc03-5b04-4877-b6b6-1a467e157067
```

# StorageClass

```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"kadalu.local-ssd-1"},"parameters":{"kadalu_format":"native","storage_name":"local-ssd-1"},"provisioner":"kadalu"}
  creationTimestamp: "2022-02-17T14:32:38Z"
  name: kadalu.local-ssd-1
  resourceVersion: "192668443"
  uid: 5ed20f28-1131-40a3-9c1f-4a7b1eb213ed
parameters:
  kadalu_format: native
  storage_name: local-ssd-1
provisioner: kadalu
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

# Example PV and PVC

## PV

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: kadalu
  creationTimestamp: "2022-02-17T14:43:45Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-9141522d-42d4-4c2b-91a0-69733ff8d09b
  resourceVersion: "192672638"
  uid: d8acdc60-5e76-4b61-a565-17991b7d21b9
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: bazarr-config
    namespace: bazarr
    resourceVersion: "192672559"
    uid: 9141522d-42d4-4c2b-91a0-69733ff8d09b
  csi:
    driver: kadalu
    volumeAttributes:
      fstype: xfs
      hostvol: local-ssd-1
      kformat: native
      path: subvol/4d/48/pvc-9141522d-42d4-4c2b-91a0-69733ff8d09b
      pvtype: subvol
      storage.kubernetes.io/csiProvisionerIdentity: 1645108381876-8081-kadalu
      storage_options: ""
      type: Replica3
    volumeHandle: pvc-9141522d-42d4-4c2b-91a0-69733ff8d09b
  persistentVolumeReclaimPolicy: Delete
  storageClassName: kadalu.local-ssd-1
  volumeMode: Filesystem
status:
  phase: Bound
```

## PVC

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: bazarr
    meta.helm.sh/release-namespace: bazarr
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kadalu
    volume.kubernetes.io/storage-provisioner: kadalu
  creationTimestamp: "2022-02-17T14:43:37Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: bazarr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: bazarr
    app.kubernetes.io/version: v0.9.9
    helm.sh/chart: bazarr-10.3.0
    helm.toolkit.fluxcd.io/name: bazarr
    helm.toolkit.fluxcd.io/namespace: bazarr
  name: bazarr-config
  namespace: bazarr
  resourceVersion: "192672641"
  uid: 9141522d-42d4-4c2b-91a0-69733ff8d09b
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: kadalu.local-ssd-1
  volumeMode: Filesystem
  volumeName: pvc-9141522d-42d4-4c2b-91a0-69733ff8d09b
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  phase: Bound
```

**Comment by leelavg** [comment]
> It looks like the creation of the storageclass doesn't take into consideration the pvReclaimPolicy parameter set in the KadaluStorage.

~- Ah! Unfortunately yes, it's a bug.~
- For better/worse we don't reconcile storage class, so you could re-create it manually which I believe you know some workaround of this sort 😉
~- On a serious note, pardon the inconvenience 😔~

- Having said above, we implement it at pool level so technically your PV should've been retained 🤔

**Comment by fastlorenzo** [comment]
No issues, I'll check if I can make a PR when I have a bit of time 😄 

So you mean this is normal that the PV's retention policy shown kubectl output says `delete`, even though I set the `pvReclaimPolicy` parameter in the `kadaluStorage` config to `retain`? (just double checking, still testing now so not a big deal or any data loss .. yet 😄

**Comment by leelavg** [comment]
> PV's retention policy shown kubectl output says delete, even though I set the pvReclaimPolicy parameter in the kadaluStorage config to retain
- first and foremost, in kadalu's case there's no correlation b/n PV policy on storage class vs on pool afaic-think
- you could create multiple storageclasses on a single pool and pool is said to retain PVs all the data from child storageclasses will be retained 
- generally, I believe if you set reclaimPolicy at sc level you may loose the benefit of retaining the storage even after recreating a storage pool since k8s may not send delete event to kadalu and kadalu will backoff when user wants ro remove the pool, makes sense?

> just double checking, still testing now
- ack, pls do update the status 🙏
