### ISSUE TITLE
Suggestion: Create a separate base-image

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#77]
As of now, we use fedora30 as base-image for all our containers. And after that, each containers are prepared separately when we do `make build-containers`.

On a developer's laptop this is fine, but our CI/CD tests are taking 6 mins (out of 9 mins for total run) to build the containers.

One possibility is, we can have a separate docker file for base image, and have it uploaded at 'kadalu/base-image', and use the same and copy the files over in every container preparation.

That way, we can save time and possible errors of missing out something basic in base-image as the code gets repeated in 3 places in Dockerfile as of now.

**Comment by amarts** [comment]
This also makes our tests run within 4 mins :-) which would be a great win.

**Comment by aravindavk** [comment]
Nice.

**Comment by aravindavk** [comment]
while working on this we can also finalize on base OS which we can use. (CentOS or Ubuntu LTS)
