### ISSUE TITLE
Volume stuck on Pending with ResourceExhausted

### ISSUE THREAD

**Issue by golyalpha** [kadalu/kadalu#772]
I just tried deploying another database pod on my cluster, and notice it was stuck in pending because of unbound PVC. Looking at the PVC, I found out that Kadalu was refusing to create a volume for it:
```
  Normal   ExternalProvisioning  4m36s (x121 over 34m)  persistentvolume-controller                                           waiting for a volume to be created, either by external provisioner "kadalu" or manually created by system administrator
  Normal   Provisioning          70s (x11 over 14m)     kadalu_kadalu-csi-provisioner-0_81dbf3bd-cf3a-4cab-8a4c-69ae2ec775e7  External provisioner is provisioning volume for claim "olaris/data-postgres-0"
  Warning  ProvisioningFailed    70s (x11 over 14m)     kadalu_kadalu-csi-provisioner-0_81dbf3bd-cf3a-4cab-8a4c-69ae2ec775e7  failed to provision volume with StorageClass "kadalu.pool-1": rpc error: code = ResourceExhausted desc = No Hosting Volumes available, add more storage
```

However, there is more than enough space for the volume:
```
$ df -h /mnt/kadalu
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p2  115G   75G   36G  68% /
```
Here's the log output from `kubectl kadalu log`:  [kadalu.log](https://github.com/kadalu/kadalu/files/8232070/kadalu.log)

Kadalu version is 0.8.9

**Comment by leelavg** [comment]
- well, as a side note, Replica1 for database workload on root mount, I hope you are not looking for fault tolerance
- it's a rpi and mmc storage, am I correct in assuming that you didn't expand the mount?
- Pls include `-T` as well in `df` in general 
- What's the o/p of `getfattr -d -e text -m. /mnt/kadalu`?

@amarts there are some warnings wrt simple-quota in the logs, if possible ptal.

**Comment by golyalpha** [comment]
Nope. I'm not looking for fault tolerance. Just wanted to try out Kadalu.

"Didn't expand the mount?" Not entirely sure what you mean - do you mean expand the filesystem? If so, then yes - I have expanded the filesystem.

Here's the output of `df -Th`:
```
Filesystem     Type      Size  Used Avail Use% Mounted on
udev           devtmpfs  3.8G     0  3.8G   0% /dev
tmpfs          tmpfs     782M  3.1M  779M   1% /run
/dev/mmcblk0p2 ext4      115G   80G   30G  73% /
tmpfs          tmpfs     3.9G   16K  3.9G   1% /dev/shm
tmpfs          tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs          tmpfs     3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/loop0     squashfs  128K  128K     0 100% /snap/bare/5
/dev/loop1     squashfs  140M  140M     0 100% /snap/chromium/1911
/dev/loop2     squashfs   49M   49M     0 100% /snap/core18/2289
/dev/loop3     squashfs   49M   49M     0 100% /snap/core18/2349
/dev/loop5     squashfs   58M   58M     0 100% /snap/core20/1360
/dev/loop4     squashfs  140M  140M     0 100% /snap/chromium/1933
/dev/loop7     squashfs  229M  229M     0 100% /snap/gnome-3-38-2004/88
/dev/loop6     squashfs   66M   66M     0 100% /snap/gtk-common-themes/1519
/dev/loop9     squashfs   38M   38M     0 100% /snap/snapd/15183
/dev/loop8     squashfs   62M   62M     0 100% /snap/lxd/22530
/dev/loop10    squashfs   38M   38M     0 100% /snap/snapd/14982
/dev/loop11    squashfs  229M  229M     0 100% /snap/gnome-3-38-2004/100
/dev/loop12    squashfs   61M   61M     0 100% /snap/lxd/21843
/dev/mmcblk0p1 vfat      253M  120M  133M  48% /boot/firmware
/dev/loop13    squashfs  147M  147M     0 100% /snap/gnome-3-28-1804/160
/dev/loop14    squashfs   58M   58M     0 100% /snap/core20/1380
tmpfs          tmpfs     782M     0  782M   0% /run/user/1001
tmpfs          tmpfs     782M     0  782M   0% /run/user/1000
```

`getfattr -d -e text -m. /mnt/kadalu` outputs nothing, exit code `0`

**Comment by leelavg** [comment]
- ah! the root partition is on ext4, currently server pods assumes xfs and maybe that's the issue
- iiuc ext4 also supports xattrs however I don't want to bet on that
- i'd ask you to use the disk/path that's based on xfs
- as you just want to try kadalu, you could create a loop device and supply that as a device in CR

**Comment by golyalpha** [comment]
I'm kind of in the process of dropping the cluster, so, not right now. But my guess would be that switching to XFS as the backing filesystem would in fact fix the issue (since you say the assumption is that the backing FS is XFS)

That being said, any clue why I was able to create multiple volumes before this issue popped up?

**Comment by leelavg** [comment]
- we use xattrs to keep track of pvc usage
- maybe those xattrs wasn't set on ext4 fs from the start and wasn't limiting anything
- i only have limited knowledge on this and don't want to take a hunch

maybe @amarts / @aravindavk can better explain this and we could document what to expect if we are not on xfs

**Comment by leelavg** [comment]
Ping @amarts @aravindavk ^^
