### ISSUE TITLE
Multiple kadalus inside one cluster?

### ISSUE THREAD

**Issue by rafis** [kadalu/kadalu#773]
We have Kadalu instance installed in `kadalu` namespace. Can we add a second Kadalu instance in namespace for example `kadalu2` with different configuration, will it work?

**Comment by leelavg** [comment]
- No it'll not work and also no other CSI supports this afaik.
- Think of CSI in terms of Nodes but not Namespaces in current context.
- If multiple sockets are exposed on same node, one may overwrite and there are other issues as well.
---
- May I know the usecase?

**Comment by rafis** [comment]
Use case is we have trouble with our Gluster FS cluster. Mounting points sometimes fail with "Transport endpoint is not connected" error message. Currently we have to reboot kubernetes workers and this helps for a few days, but then errors repeats again. We want to try to smoothly migrate PVCs to another Gluster FS cluster (freshly installed) and to see if that helps. The number of PVCs is large which is why we can migrate only smoothly without interruption of work for our users. Two instances of Kadalu would allow us smooth migration.

**Comment by leelavg** [comment]
> our Gluster FS cluster. 
- is it internal or external gluster server?

> Mounting points sometimes fail with "Transport endpoint is not connected" error message.
- Could you pls raise another issue explaining reproducer steps if possible 

> Currently we have to reboot kubernetes workers and this helps for a few days, but then errors repeats again.
- So are you anticipating that the issue is in kadalu csi integration

> We want to try to smoothly migrate PVCs to another Gluster FS cluster (freshly installed) and to see if that helps.
- Even if freshly installed if the workload is similar then it may not help much, not to discourage the effort however it's better to debug the issue if you intend to use kadalu

> The number of PVCs is large which is why we can migrate only smoothly without interruption of work for our users. Two instances of Kadalu would allow us smooth migration.
- Sry, I'm not able to think through how this'll solve your issue. Could you pls explain the process if possible?
- IMHO it's not possible to have two kadalu instances running across namespaces

**Comment by rafis** [comment]
> is it internal or external gluster server?

External GlusterFS cluster with 3 equal nodes. Oracle Linux 7.9, GlusterFS 6.10.

> Could you pls raise another issue explaining reproducer steps if possible

It will be very hard to reproduce environment I think. Anyway issue is not in Kadalu, but is in GlusterFS cluster.

> So are you anticipating that the issue is in kadalu csi integration

The issue "Transport endpoint is not connected" is not in Kadalu, but is in GlusterFS cluster.

> Even if freshly installed if the workload is similar then it may not help much, not to discourage the effort however it's better to debug the issue if you intend to use kadalu

We are trying, but it is hard to do. GlusterFS is written is C and very hard to diagnose. If it would be written in Python would be much simplier :-)

> Sry, I'm not able to think through how this'll solve your issue. Could you pls explain the process if possible?

We think that we are having a GlusterFS cluster which is configured improperly, there is too much errors in glusterfs logs, but that sysops engineer who was performing configuration is not working in company anymore. We want to try to install a fresh GlusterFS cluster with default settings, just `yum install glusterfs-server` and `gluster peer probe`.

> IMHO it's not possible to have two kadalu instances running across namespaces
> No it'll not work and also no other CSI supports this afaik.

Thank you for information. I'm glad that I have asked first instead of trying on a production cluster :-)
