### ISSUE TITLE
Expose Performance metrics from node plugins

### ISSUE THREAD

**Issue by aravindavk** [kadalu/kadalu#782]
- Gluster exports the fops metrics from client and servers.
- Expose the fop metrics from each xlators and fop type.
- To collect the metrics,
    - Remove all the files in `/var/run/gluster/metrics/` directory
    - Send `USR2` signal to glusterfs process. Example: `kill -USR2 <glusterfs-pid>`
    - Open the new file created in `/var/run/gluster/metrics/` directory(Ex: `/var/run/gluster/metrics/gmetrics.reKaKi`). Parse the fields and expose the metrics (Sample file is enclosed).

[gmetrics_sample.txt](https://github.com/kadalu/kadalu/files/8352534/gmetrics_sample.txt)

References:
- glustermetrics project: https://github.com/amarts/glustermetrics/

**Comment by leelavg** [comment]
- is the referenced project feature complete? Just asking based on last commit
- I'd like to put effort on the existing code for supplying vol options and corresponding CI before providing these metrics 🤔
