### ISSUE TITLE
[BUG] Installation script has wrong links

### ISSUE THREAD

**Issue by WatchTh1** [kadalu/kadalu#783]
Installation script saves utility to /tmp/kubectl-kadalu and tries to install from /tmp/kadalu

Link to script (as provided in docs):
https://github.com/kadalu/kadalu/releases/latest/download/install.sh

Which is obviously goes wrong.

```
curl -fsSL https://github.com/kadalu/kadalu/releases/latest/download/kubectl-kadalu -o /tmp/kubectl-kadalu

install /tmp/kadalu /usr/bin/kubectl-kadalu
install /tmp/kadalu /usr/bin/oc-kadalu
```

**Comment by leelavg** [comment]
- good catch! will fix at the earliest.
- if you are fine to send a fix, it'll be great 😀
https://github.com/kadalu/kadalu/blob/devel/extras/install.sh
