### ISSUE TITLE
[RFE]: Remove Db and Info file for Size Accounting

### ISSUE THREAD

**Issue by aravindavk** [kadalu/kadalu#794]
The Storage Pool size and size of PVs stored in the embedded Sqlite3 DB within the Volume. Also, one info file is created for each PVs and stored in the Volume itself. This RFE shows how to get the required information without depending on the Database or external files.

**To get PV size and utilization**: 
- Simple quota already provides this detail when we run `df` on the sub dir where quota is set(Use stat if it is block file).

**To get Storage Pool Utilization**:
- Get the list of PVs from that Storage Pool
- Get each PV utilization
- Add PV size to get the total allocated size
- Run `df`(`statvfs`) on the Storage pool and only get the total size from that

## Why?
- Reduces the burden of maintaining additional file/db
- In a Distributed Storage pool, if a distribute group is down and Db is hashed to that distribute group then this data will not be available.

## Backward compatibility
- The proposed change is backward compatible
- After the change, Provisioner or Status commands directly calculate without using Db file. Stale Db files remain in existing setup, no effect to functionality.

If any other static metadata is required for subdir/block file, then Store it as xattr on the dir/file.

**Comment by aravindavk** [comment]
@amarts @leelavg any thoughts? ^^

**Comment by leelavg** [comment]
- I'll re-look this after #779 
- IMHO i don't like to base size related ops from k8s perspective on simple quota yet
- Sry if I'm being condesive here as I still consider simple-quota as opaque to me
