### ISSUE TITLE
"Driver name kadalu not found in the list of registered CSI drivers" after cluster reboot

### ISSUE THREAD

**Issue by Expro** [kadalu/kadalu#795]
I'm getting following issue with pods that uses Kadalu after all cluster reboot:

"MountVolume.MountDevice failed for volume "pvc-808c8ac6-1de9-4ff5-baad-88919b0dd988" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name kadalu not found in the list of registered CSI drivers"

Steps from troubleshooting didn't help. Not even full reinstall help here.

Version 0.8.13.

**Comment by leelavg** [comment]
Hello,

- What's the o/p of `kubectl get csidrivers`?
- Is nodeplugin pod in running state?
- From what version did you upgrade to latest?
- Is above error from `describe pvc`?

**Comment by Expro** [comment]
> What's the o/p of kubectl get csidrivers?
```

NAME     ATTACHREQUIRED   PODINFOONMOUNT   STORAGECAPACITY   TOKENREQUESTS   REQUIRESREPUBLISH   MODES        AGE
kadalu   false            true             false             <unset>         false               Persistent   131m
```

> Is nodeplugin pod in running state?

```
NAME                          READY   STATUS    RESTARTS   AGE
kadalu-csi-nodeplugin-fl4xr   3/3     Running   3          136m
kadalu-csi-nodeplugin-wqldp   3/3     Running   3          136m
kadalu-csi-provisioner-0      5/5     Running   5          136m
operator-df6585c7d-fh6z5      1/1     Running   1          136m
```

> From what version did you upgrade to latest?

This is fresh installation, no version upgrades yet.

> Is above error from describe pvc?

It's from `describe pod` for one of the pods that used PV provided by Kadalu.

**Comment by leelavg** [comment]
@Expro 
- Everything looks good to me
- A quick search landed here https://github.com/democratic-csi/charts/pull/11#issue-702357529
- We do take into account microk8s standard path but not the snap installed one
- If above isn't the case, could you let me know about your k8s distro and kubelet path?

**Comment by Expro** [comment]
> Everything looks good to me

Pods stared, but volumes are not mounted - if I manually mount somwhere else GlusterFS volumes that contains PVs I can see data from before cluster reboot, but after cluster reboot pods cannot see this data - they started with clean storage.

> A quick search landed here https://github.com/democratic-csi/charts/pull/11#issue-702357529

Not the case:

```
ll /var/lib/kubelet/

total 20
-rw-r--r--  1 root root  936 Apr  1 14:21 config.yaml
-rw-------  1 root root   62 Apr  1 14:22 cpu_manager_state
drwxr-xr-x  2 root root   45 Apr 15 11:03 device-plugins
-rw-r--r--  1 root root  152 Apr  1 14:21 kubeadm-flags.env
-rw-------  1 root root   61 Apr  1 14:22 memory_manager_state
drwxr-xr-x  2 root root  124 Apr  1 14:21 pki
drwxr-x---  3 root root   27 Apr  4 01:46 plugins
drwxr-x---  3 root root   43 Apr 15 11:04 plugins_registry
drwxr-x---  2 root root   26 Apr 15 11:03 pod-resources
drwxr-x--- 20 root root 4096 Apr 15 13:28 pods
```

> We do take into account microk8s standard path but not the snap installed one

None of those were used.

> If above isn't the case, could you let me know about your k8s distro and kubelet path?

Pure Kubernetes with CRI-O as runtime, on Fedora 35. 

```
whereis kubelet

kubelet: /usr/bin/kubelet
```

**Comment by leelavg** [comment]
> before cluster reboot, but after cluster reboot pods cannot see this data - they started with clean storage.
- sry a little bit confused, did you lost the data after cluster reboot?
- ntg comes to my mind of what might be the issue, could you pls provide reproduction steps if possible?

**Comment by Expro** [comment]
Sure, let me try to rephrase issue:

I have deployed fresh Kubernetes cluster via kubeadm. Deployed necessary CNI plugin and some DNS plugins, then deployed Kadalu via Helm chart. Created few StorageClasses that pointed to previously deployed GlusterFS volumes. Deployed few apps, PVs were created correctly, volumes were correctly mounted to pods, applications were able to write data that actually landed on said GlusterFS volumes in proper directory structure. Everything fine up to this point.

Then, I had to restart entire clusters (all nodes). Everything came up properly EXCEPT volumes are no longer being mounted to pods. After some times, pods starts to run, but volumes are either not mounted, or mounted incorrectly. From inside of pod, paths that are supposed to be mounted and contain data are empty. `describe pod` shows message from my initial issue post.

Data is not lost (it's still on volumes on external GlusterFS cluster), but it's no longer accessible by pods.

**Comment by Expro** [comment]
After some explorative debugging, I think I have narrowed down root of this issue to DNS. I had error in DNS configuration that affected pods ability to resolve DNS names - hosts were fine though. After correcting this error and rebooting cluster, volumes were mounted correctly.

It would be nice if such issue was handled and communicated in more clear manner.

**Comment by leelavg** [comment]
> It would be nice if such issue was handled and communicated in more clear manner.
- Frankly, this is the first time I'm hearing that DNS would cause this issue
- I can now connect the dots how DNS effected mounting of PVC however from info that I got upto now I wouldn't be able to find it
- Your debugging helped in reduction of to & fro and thanks for that
- iirc we have a mention about about checking connectivity b/n server pods however the way the issue is framed/popped up doesn't stir network suspicion 😅

Thanks a lot for trying out kadalu and raising the issues 😀

**Comment by Expro** [comment]
> Thanks a lot for trying out kadalu and raising the issues

No problem, I always hoped for GlusterFS to get better and now I can :)
