### ISSUE TITLE
[Bug]: code = ResourceExhausted desc = No Hosting Volumes available, add more storage

### ISSUE THREAD

**Issue by pantxisto** [kadalu/kadalu#804]
Hello,

**Describe the bug**
I have Kadalu managing volumes on 3 different nodes using Replica3 type. If the size of created volumes surpass the available storage, the pvc remains in pending status although I delete some of the existing pvcs and pvs and I try again to create the pvc deleting the previous one with pending status. Someway the available storage is not getting calculated as it should be.

**To Reproduce**
1. Install latest kadalu-operator and csi-nodeplugin.
2. Create an lvm with ext4 on each node.
3. Create Replica3 type storage pool.

**Expected behavior**
When the pvc and pv is deleted the storage available should be calculated again.

**Actual behavior**
The available storage is not been recalculated when the pvc and pv are deleted.

**Environment:**
kubectl-kadalu plugin: 0.8.13
kadalu pod(s) versions
pod/kadalu-csi-nodeplugin-f97gk: 0.8.13
pod/kadalu-csi-nodeplugin-k7wcq: 0.8.13
pod/kadalu-csi-nodeplugin-m24z2: 0.8.13
pod/kadalu-csi-provisioner-0: 0.8.13
pod/operator-c59d645cb-2tvnk: 0.8.13
pod/server-storage-pool-0-0: 0.8.13
pod/server-storage-pool-1-0: 0.8.13
pod/server-storage-pool-2-0: 0.8.13
 - K8S_DIST: kubernetes (kubeadm cluster)

**Screenshots or Logs**

> Events:
>   Type     Reason                Age                    From                                                                  Message
>   ----     ------                ----                   ----                                                                  -------
>   Normal   ExternalProvisioning  3m50s (x122 over 34m)  persistentvolume-controller                                           waiting for a volume to be created, either by external provisioner "kadalu" or manually created by system administrator
>   Normal   Provisioning          3m18s (x14 over 34m)   kadalu_kadalu-csi-provisioner-0_7a745806-baf3-4913-9e52-ae6beb09c852  External provisioner is provisioning volume for claim "default/prueba-pvc"
>   Warning  ProvisioningFailed    3m13s (x14 over 34m)   kadalu_kadalu-csi-provisioner-0_7a745806-baf3-4913-9e52-ae6beb09c852  failed to provision volume with StorageClass "kadalu.storage-pool": rpc error: code = ResourceExhausted desc = No Hosting Volumes available, add more storage

**Aditional context**

Inside /mnt/myvolume/brick/info/subvol I have this folders:

```
.   01  06  0b  10  13  19  22  27  30  38  3f  47  51  5a  61  65  6c  72  76  7a  81  89  90  97  9e  aa  ad  b2  b9  bf  c3  ca  d1  da  e2  e8  f4  fa
..  03  08  0e  11  16  1b  25  29  31  3a  42  4c  53  5c  62  68  70  74  77  7d  82  8d  92  9a  a7  ab  ae  b3  ba  c1  c7  cc  d3  dc  e4  e9  f5
00  04  0a  0f  12  18  21  26  2c  35  3b  43  4e  59  60  63  6a  71  75  79  7e  88  8f  93  9b  a8  ac  af  b8  be  c2  c9  ce  d9  dd  e5  ee  f7
```

However if I try to find how many of them have a json file with info I only get 16 results:
find . -name "*.json"

```
./01/9a/pvc-c2387940-9840-40ee-b212-7ed643ec7e0d.json
./47/88/pvc-2f531138-1367-4281-948a-18fa4c023494.json
./f4/76/pvc-466f547c-16ad-4eab-93ef-90c06cbaaeca.json
./11/5c/pvc-ed799e68-e8cc-48fd-b726-b818f4ca0102.json
./b8/9d/pvc-7c615d59-bbcd-4dd9-b44c-14a82fa95e7b.json
./af/f1/pvc-25aa84d3-6b7a-4c89-b57f-9ca206abac58.json
./2c/4e/pvc-2995ef51-3363-4f26-a205-4987184afb0a.json
./53/c1/pvc-7deab600-aee6-413f-82e2-2ebaac508837.json
./3f/ea/pvc-64974f6b-d22c-4d92-9d62-063f0f557127.json
./92/4d/pvc-7291f1dd-1f42-4622-a8c4-e00718594c3e.json
./81/49/pvc-c752596c-f075-4c63-8648-ffb793564038.json
./dd/2d/pvc-c18f7096-cc2a-49b3-843f-a5621d956393.json
./93/b6/pvc-77a79fcf-b0f1-4926-841e-0ab98f888c68.json
./f5/e4/pvc-28619e77-19e0-48db-8274-18d0e8922244.json
./9b/d0/pvc-43ec3102-12a0-4c07-a33b-bb22ad3ab004.json
./35/9a/pvc-1beb5595-a8f1-45be-81ed-88dd174305bb.json
```

113 folders and only 16 of them have a json file. Currently I have 14 pv and pvcs on the cluster. Is this right or is a bad sign? If there is no implementation to solve this how can I solve manually withouth damaging kadalu storage provisioning?

If I exec the command: find . -name '*.json' -exec cat {} \; the output is:

```
{"size":   10737418240, "path_prefix": "subvol/01/9a"}
{"size": 429496729600, "path_prefix": "subvol/47/88"}
{"size":     1073741824, "path_prefix": "subvol/f4/76"}
{"size": 429496729600, "path_prefix": "subvol/11/5c"}
{"size":     8589934592, "path_prefix": "subvol/b8/9d"}
{"size":   10737418240, "path_prefix": "subvol/af/f1"}
{"size":   10737418240, "path_prefix": "subvol/2c/4e"}
{"size":   21474836480, "path_prefix": "subvol/53/c1"}
{"size":     2147483648, "path_prefix": "subvol/3f/ea"}
{"size":   10737418240, "path_prefix": "subvol/92/4d"}
{"size":     8589934592, "path_prefix": "subvol/81/49"}
{"size": 107374182400, "path_prefix": "subvol/dd/2d"}
{"size":   10737418240, "path_prefix": "subvol/93/b6"}
{"size":   10737418240, "path_prefix": "subvol/f5/e4"}
{"size":   10737418240, "path_prefix": "subvol/9b/d0"}
{"size":     8589934592, "path_prefix": "subvol/35/9a"}
```
Adding all the sizes I get a result of 1091,995435008 Gi. 

Doing df -TH:

```
/dev/mapper/vg--myvolume--volume-myvolume--volume ext4      1.1T   19G 1011G   2% /mnt/myvolume
```
This is the reason to not create more pvs and pvcs, but If I add all of the sizes of pvs I get a result of 916 GB, so there are some json that have not been deleted and there should be available space.

```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                    STORAGECLASS          REASON   AGE
pvc-1beb5595-a8f1-45be-81ed-88dd174305bb   8Gi        RWO            Delete           Bound    mongodb/logs-volume-x-mongodb-1     kadalu.storage-pool            19d
pvc-25aa84d3-6b7a-4c89-b57f-9ca206abac58   10Gi       RWO            Delete           Bound    solr/data-x-solrcloud-1             kadalu.storage-pool            15d
pvc-28619e77-19e0-48db-8274-18d0e8922244   10Gi       RWO            Delete           Bound    grafana/grafana-pvc                      kadalu.storage-pool            12d
pvc-2995ef51-3363-4f26-a205-4987184afb0a   10Gi       RWO            Delete           Bound    solr/data-x-solrcloud-0             kadalu.storage-pool            15d
pvc-2f531138-1367-4281-948a-18fa4c023494   400Gi      RWO,RWX        Delete           Bound    mongodb/data-volume-x-mongodb-1     kadalu.storage-pool            19d
pvc-43ec3102-12a0-4c07-a33b-bb22ad3ab004   10Gi       RWO            Delete           Bound    solr/data-x-solrcloud-zookeeper-0   kadalu.storage-pool            15d
pvc-64974f6b-d22c-4d92-9d62-063f0f557127   2Gi        RWO            Delete           Bound    prometheus/alertmanager-pvc              kadalu.storage-pool            12d
pvc-7291f1dd-1f42-4622-a8c4-e00718594c3e   10Gi       RWO            Delete           Bound    solr/data-x-solrcloud-zookeeper-1   kadalu.storage-pool            15d
pvc-77a79fcf-b0f1-4926-841e-0ab98f888c68   10Gi       RWO            Delete           Bound    solr/data-x-solrcloud-zookeeper-2   kadalu.storage-pool            15d
pvc-7c615d59-bbcd-4dd9-b44c-14a82fa95e7b   8Gi        RWO            Delete           Bound    mongodb/logs-volume-x-mongodb-0     kadalu.storage-pool            19d
pvc-7deab600-aee6-413f-82e2-2ebaac508837   20Gi       RWO            Delete           Bound    default/docker-repo-pvc                  kadalu.storage-pool            8d
pvc-c2387940-9840-40ee-b212-7ed643ec7e0d   10Gi       RWO            Delete           Bound    solr/data-x-solrcloud-2             kadalu.storage-pool            15d
pvc-c752596c-f075-4c63-8648-ffb793564038   8Gi        RWO            Delete           Bound    prometheus/server-pvc                    kadalu.storage-pool            12d
pvc-ed799e68-e8cc-48fd-b726-b818f4ca0102   400Gi      RWO,RWX        Delete           Bound    mongodb/data-volume-x-mongodb-0     kadalu.storage-pool            19d

```

**Comment by leelavg** [comment]
Hey @pantxisto, thanks for the detailed issue.

- outright my thoughts go with usage of `ext4` since we test and support `xfs` I wasn't sure how well kadalu performs with the former
- would you be able to find out which PVC json files exist which aren't there in `kubectl get pvc`?
- by any chance did you set `pvReclaimPolicy: archive` in pool CR?
- it seems you provided `path:` in the pool CR and you've 1.1T x 3 combined logical volume across three nodes?

> 113 folders and only 16 of them have a json file.
- we are overdistributing the PVCs i think 😅, @vatsa287 if it's fine can you pls check for whole path removal when a PVC is deleted if not done already?

**Comment by pantxisto** [comment]
Hello @leelavg,

- I will make some test on a local cluster to see if I am able to replicate the behaviour and if it is solved using xfs.
- Yes.
```
sudo find . -name "pvc*"

./01/9a/pvc-c2387940-9840-40ee-b212-7ed643ec7e0d
./47/88/pvc-2f531138-1367-4281-948a-18fa4c023494
./f4/76/pvc-466f547c-16ad-4eab-93ef-90c06cbaaeca
./11/5c/pvc-ed799e68-e8cc-48fd-b726-b818f4ca0102
./b8/9d/pvc-7c615d59-bbcd-4dd9-b44c-14a82fa95e7b
./af/f1/pvc-25aa84d3-6b7a-4c89-b57f-9ca206abac58
./2c/4e/pvc-2995ef51-3363-4f26-a205-4987184afb0a
./53/c1/pvc-7deab600-aee6-413f-82e2-2ebaac508837
./3f/ea/pvc-64974f6b-d22c-4d92-9d62-063f0f557127
./92/4d/pvc-7291f1dd-1f42-4622-a8c4-e00718594c3e
./81/49/pvc-c752596c-f075-4c63-8648-ffb793564038
./dd/2d/pvc-c18f7096-cc2a-49b3-843f-a5621d956393
./93/b6/pvc-77a79fcf-b0f1-4926-841e-0ab98f888c68
./f5/e4/pvc-28619e77-19e0-48db-8274-18d0e8922244
./9b/d0/pvc-43ec3102-12a0-4c07-a33b-bb22ad3ab004
./35/9a/pvc-1beb5595-a8f1-45be-81ed-88dd174305bb

```
So the two pvc that are on filesystem but not on kubernetes cluster are:
```
./f4/76/pvc-466f547c-16ad-4eab-93ef-90c06cbaaeca
./dd/2d/pvc-c18f7096-cc2a-49b3-843f-a5621d956393
```
- To be honest I don't remember using archive, perhaps it could be... the KadaluStorage yaml spec is the next:
```
spec:
  kadalu_format: native
  pvReclaimPolicy: delete
  storage:
  - device: /dev/vg-myvolume-volume/myvolume-volume
    node: worker1
  - device: /dev/vg-myvolume-volume/myvolume-volume
    node: worker2
  - device: /dev/vg-myvolume-volume/myvolume-volume
    node: worker3
  type: Replica3
```

- Yes.

Thanks for your fast answer.

**Comment by leelavg** [comment]
- thanks for the update
- to me it seems as a straightforward delete miss
- not sure when were these PVCs removed from k8s, if the op wasn't successful k8s will keep on trying for success
- do you have any failure logs in nodeplugin and provisioner for these PVCs
- all in all the simple workaround would be as below (pls adjust accordingly if you find any discrepancy)
``` 
# k exec -it kadalu-csi-provisioner-0 -c kadalu-provisioner -- bash
# cd /kadalu
# python
>>> from volumeutils import delete_volume
>>> delete_volume('pvc-466f547c-16ad-4eab-93ef-90c06cbaaeca')
>>> delete_volume('pvc-c18f7096-cc2a-49b3-843f-a5621d956393')
``` 
- i still believe k8s will re-send rpc calls until success, not sure why your setup ended up like this 😅

**Comment by pantxisto** [comment]
- I have not been able to reproduce on local. I have not manage to make kadalu provisioning a pvc.
- After deleting both volumes I can provide pvcs again. I can provide and delete and everything works smoothly. Also a problem with reclaim policy that I had because pvs were no deleted have been resolved. :+1: 
- However, all of the actual pvcs existing in the cluster can be found inside: mountpath/brick/info/subvol but inside mounthpath/data/brick/info/subvol/ there are 3 pvcs that there are not in the cluster. I have tried to delete with given commands but it does not work. How can I delete them?
- Perhaps this strange behaviour is related to somes changes done on the firewall yesterday. Some communications between pods  were blocked and I unblock them. 
- No logs related to old pvcs found. After solving the firewall issue  yesterday I restarted all pods on kadalu namespace, perhaps have been deleted.
- I find some logs that I don't know if they should be there:

k logs kadalu-csi-nodeplugin-f97gk -c kadalu-nodeplugin -n kadalu
```
[2022-04-27 18:01:37,492] WARNING [exporter - 102:metrics] - PVC JSON file not found. PVC must have been deleted. Trying again!
[2022-04-27 18:01:38,705] WARNING [exporter - 102:metrics] - PVC JSON file not found. PVC must have been deleted. Trying again!
[2022-04-27 18:01:38,706] WARNING [exporter - 102:metrics] - PVC JSON file not found. PVC must have been deleted. Trying again!
[2022-04-27 18:01:38,707] WARNING [exporter - 102:metrics] - PVC JSON file not found. PVC must have been deleted. Trying again!
[2022-04-27 18:01:38,707] WARNING [exporter - 102:metrics] - PVC JSON file not found. PVC must have been deleted. Trying again!
[2022-04-27 18:01:38,708] WARNING [exporter - 102:metrics] - PVC JSON file not found. PVC must have been deleted. Trying again!
```

k logs kadalu-csi-provisioner-0 -c kadalu-provisioner -n kadalu

```
[2022-04-27 18:01:37,492] WARNING [exporter - 102:metrics] - PVC JSON file not found. PVC must have been deleted. Trying again!
[2022-04-27 18:01:38,705] WARNING [exporter - 102:metrics] - PVC JSON file not found. PVC must have been deleted. Trying again!
[2022-04-27 18:01:38,706] WARNING [exporter - 102:metrics] - PVC JSON file not found. PVC must have been deleted. Trying again!
[2022-04-27 18:01:38,707] WARNING [exporter - 102:metrics] - PVC JSON file not found. PVC must have been deleted. Trying again!
[2022-04-27 18:01:38,707] WARNING [exporter - 102:metrics] - PVC JSON file not found. PVC must have been deleted. Trying again!
[2022-04-27 18:01:38,708] WARNING [exporter - 102:metrics] - PVC JSON file not found. PVC must have been deleted. Trying again!
```
Thanks

**Comment by leelavg** [comment]
> Some communications between pods were blocked and I unblock them.
- uh oh, this should've mentioned earlier I think

> mounthpath/data/brick/info/subvol
- need to take a look, isn't above part of server pods?

Ask:
- what functionalities according to you aren't working as expected?
- do you see higher usage of resources (cpu & ram) being used by kadalu components?

**Comment by leelavg** [comment]
@pantxisto if your machines are stable now, pls consider closing this issue. thanks.
