### ISSUE TITLE
Fix kadalu on nomad environment

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#817]
This PR breaks kadalu from working in a Nomad environment. There is no file or directory named ..data in a nomad environment. I would propose to setup a recursive watch of /var/lib/gluster instead, and put a sleep 1 into the loop, because else it has the potential of becoming very CPU intensive.

_Originally posted by @dhpowrhost in https://github.com/kadalu/kadalu/issues/715#issuecomment-1120766134_

**Comment by leelavg** [comment]
Hi @dhpowrhost, do you have any feedback in using kadalu in Nomad?

- I find Nomad cool relative to k8s, so thinking of writing a kadalu operator for Nomad 😅
- however, need feedback from users before investing time and effort if there's no requirement

**Comment by denogio** [comment]
We are about to lauch nomad + kadalu + gluster in production. It actually works pretty stable using 0.8.6 which of course is before the aforementioned PR that causes the plugin to break in Nomad. I am pretty sure looking at the code that this can be solved easily: What kind of changes do you have in mind? I will be ready to provide you with feedback.

**Comment by leelavg** [comment]
> aforementioned PR that causes the plugin to break in Nomad
- ack, I'll spend some time to test and update the docs for latest version of Kadalu for a start

> What kind of changes do you have in mind
- i'm thinking to re-arch current operator and consolidate the functions needed by k8s and nomad
- integrate with consul and drop support for manual config entry in job files for pool cr (external/internal), I assume everyone use Consul with Nomad 🤔 
- support for gluster to run on Nomad storage nodes managed by Kadalu (ambitious but not impossible)
- I didn't put the design in paper however I feel I can make changes to make kadalu seamlessly work on k8s and nomad

btw, I hope you are aware of the limitation of fuse based storage in container environment using CSI ->  when nodeplugin supplying storage gets rebooted the workload also should be rebooted, however this'll not be hit in day to day usage and happens during upgrade, if maintenance is planned correctly it'll be all good.

**Comment by leelavg** [comment]
- could you pls comment on below @amarts and @aravindavk 
- for some reason ssh commands are taking more than 30 sec even if kadalu and gluster is running on same machine
- https://github.com/kadalu/kadalu/blob/251a0801a593e4e6bad9557789899b46262dfde6/csi/volumeutils.py#L1167-L1186
```
[...]
[2022-05-24 09:12:47,782] DEBUG [volumeutils - 1166:mount_glusterfs] - Set quota-deem-statfs for gluster directory Quota
[2022-05-24 09:13:28,513] DEBUG [controllerserver - 161:CreateVolume] - Found PV type
[...]
```
- https://github.com/kadalu/kadalu/blob/251a0801a593e4e6bad9557789899b46262dfde6/csi/controllerserver.py#L51-L71
```
[...]
[2022-05-24 09:14:50,117] DEBUG [controllerserver - 290:CreateVolume] - Set Quota using gluster directory Quota
[2022-05-24 09:15:30,734] INFO [controllerserver - 298:CreateVolume] - Volume created	 name=csi-test size=200000000 hostvol=pool pvtype=subvol volpath=subvol/5d/63/csi-test duration_seconds=162.97412061691284
[...]
```
- See the duration, it's close to ~3 min which is a lot and due to this nomad is getting timed out calls when creating vols however for k8s this seems to happen well under ~2 min
- Whatever may be case, the ask from me is
1. could you pls re-look at above ssh commands and any params that you know which can speed up the operation
2. we are calling `mount_glusterfs*` functioncs many times for a single create vol request, as moana integration is happening should this need an attention?

edit: i reduced the op from 160 to 80s, however still take a look at ssh command if we can reduce round trip

**Comment by lucemans** [comment]
+1, just dropping in here to say that we are also affected by this and in need of a patch!

**Comment by tomhatzer** [comment]
Hey everyone! 👋🏻

I‘m also going to use kadalu for my nomad cluster setup. If I can support development financially or likewise, please go ahead and tell me. Possibly some more people/companies could join me in supporting your work then?

Thank you very much for everything and have a great day!

Tom

**Comment by leelavg** [comment]
> I‘m also going to use kadalu for my nomad cluster setup. 
- good to hear this, for this particular issue I've a fix already but that's failing on k8s environment 
- will take  a look at the earliest possible 

> If I can support development financially or likewise, please go ahead and tell me. Possibly some more people/companies could join me in supporting your work then?
- this is an encouraging move, in general I'm quite interested to work with Nomad
- however my day work isn't allowing me to spend time on this 😅

@amarts @aravindavk I'm not sure of the revenue model of Kadalu as a company as of now and don't need to know as an external maintainer. So, if I may ask, can I know the opencollective/github sponsor status?

Any comments of Nomad support would be helpful, as I mentioned in one of above comments I've big plans for Nomad support 😁

**Comment by denogio** [comment]
Great. Thank you for the fix - seems like a legit fix.
I till try it when released as a docker image (not devel)
