### ISSUE TITLE
[Bug]: Reported Size different to PV size

### ISSUE THREAD

**Issue by leenooks** [kadalu/kadalu#823]
**Describe the bug**
I've created a 5GB PVC, using a dispersed volume:

```
[deon@a-1-1 arch]$ kubectl describe pvc gfs-ec-5
Name:          gfs-ec-5
Namespace:     default
StorageClass:  kadalu.gfs-ec
Status:        Bound
Volume:        pvc-eabe3fe6-e5a4-46d2-8262-9a928b7ac78a
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: kadalu
               volume.kubernetes.io/storage-provisioner: kadalu
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      5Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Used By:       pod1-5778df5ccb-nqtd5
Events:        <none>
```

However, when I allocate it to a pod, it shows up as 2x it's size. (I tried with a 1G PVC initially, and then a 5G PVC to see if it was 2x).

```
# df -h /mnt/pv
Filesystem      Size  Used Avail Use% Mounted on
kadalu:gfs-ec    11G  5.2G  4.9G  52% /mnt/pv
```

As you can see, I've filled it up with 5G of data, and then I get quota-exceeded messages - so it's enforcing the 5G size.

Is the reported size (11G in this case) a bug?

**Environment:**
Output from one of commands
1. If kubectl-kadalu plugin is installed
$ kubectl kadalu version
> kubectl-kadalu plugin: 0.8.14

 - K8S_DIST: microk8s

**Comment by leelavg** [comment]
> Is the reported size (11G in this case) a bug?
- I doubt it, `gluster volume/storage pool != single pvc` if `kadalu_format: native` is set in pool cr.

- I believe in the pool cr the disk (`device:`) you used might be either 11G or the mount path (`path:`) is of 11G in size and you created a single PVC with 5GiB.

Btw, if you are a regular gluster & k8s user pls refer https://thoughtexpo.com/exploring-kadalu-storage-in-k3d-cluster-glusterfs/ or else pls refer existing docs

**Comment by leenooks** [comment]
I'm not quite sure I follow - so let me give you more detail:

```
[deon@a-1-1 ~]$ kubectl describe storageclass kadalu.gfs-ec
Name:            kadalu.gfs-ec
IsDefaultClass:  No
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"kadalu.gfs-ec"},"parameters":{"kadalu_format":"native","storage_name":"gfs-ec"},"provisioner":"kadalu"}

Provisioner:           kadalu
Parameters:            kadalu_format=native,storage_name=gfs-ec
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>
```

And KadaluStorage shows:
```
...
Spec:
  Disperse:
    Data:             2
    Redundancy:       1
  kadalu_format:      native
  Pv Reclaim Policy:  delete
  Storage:
    Device:  /dev/sdb
    Node:    a-1-1
    Device:  /dev/sdb
    Node:    a-1-2
    Device:  /dev/sdb
    Node:    a-1-3
  Type:      Disperse
Events:      <none>
```

So, I have 3 hosts (3 node cluster) each with 100GB disk dedicated to gluster (/dev/sdb in all cases). 

So on a server:
```
root@server-gfs-ec-0-0:/# df -h|grep brick
/dev/sdb        100G  3.3G   97G   4% /bricks/gfs-ec/data
```

And this by definition the gluster volume is 200G in size.
```
root@kadalu-csi-provisioner-0:/# df
Filesystem     1K-blocks    Used Available Use% Mounted on
...
kadalu:gfs-ec   200G  8.5G  192G   5% /mnt/gfs-ec
```

When I created a 1G PVC and allocated it to a pod, exec into that pod and typing `df` it showed it as a 2GB volume.

So I created a 5G PVC and allocated it to the same pod, after exec into that pod and typing `df` it showed it as an 11GB volume.

```
[deon@a-1-1 ~]$ kubectl exec -it -ndefault pod3-6dc5cc8b84-vmjh5 -- bash
root@pod3-6dc5cc8b84-vmjh5:/# df -h
kadalu:gfs-ec    11G  5.2G  4.9G  52% /mnt/pv
```

In my testing I can only write 5GB to it (which is great), but a `df` shows it only as 50% full (which would be confusing). So I guess I'm confused why a 1GB PVC shows as 2GB, and a 5GB PVC shows as an 11GB?

**Comment by leelavg** [comment]
@amarts in simple-quota do we need to account for type of volume as well?

**Comment by amarts** [comment]
@leelavg technically no, as its handled at 'distribute' level, and it would handle the `statfs()` call properly. I don't think I have done a thorough analysis of disperse volume with simple-quota in my tests. Will run some tests and report back.

But just by the design thoughts and code overview, the volume-type shouldn't play a role here.

**Comment by amarts** [comment]
Ran some tests today, and found the issue. It needs a minor fix in glusterfs's disperse module to work. Will send the fix upstream.

**Comment by amarts** [comment]
This is happening in disperse volume type only, and the size is increased by the number of data nodes used in disperse setup. Not in replica or only distribute mode.
