### ISSUE TITLE
[Bug]: PV extend does not work for StorageClass with pv_type: Block

### ISSUE THREAD

**Issue by nzolot** [kadalu/kadalu#825]
**Describe the bug**
I've tried to provision PVC which was using StorageClass with pv_type: Block and then resize it. Kadalu-csi-provisioner failed to do so 

**To Reproduce**
1. Create KadaluStorage

```
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: storage1
spec:
  type: Replica3
  storage:
    - node: node0
      device: /dev/sdc
    - node: node1
      device: /dev/sdc
    - node: node2
      device: /dev/sdc
```

3. Create StorageClass

```
allowVolumeExpansion: true
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kadalu.storage1.db
provisioner: kadalu
parameters:
  storage_name: storage1
  pv_type: Block
```

4. Create PVC 

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv8
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: kadalu.db-storage
```

6. Extend PVC size

**Expected behavior**
PV and FileSystem on it should extended

**Actual behavior**
Kadalu-csi-provisioner fails with the next messages in logs:

```
[2022-05-21 12:06:26,913] INFO [controllerserver - 625:ControllerExpandVolume] - Existing PV size and Expansion requested PV size	 existing_pvsize=2147483648 expansion_requested_pvsize=3221225472
[2022-05-21 12:06:26,980] ERROR [_server - 454:_call_behavior] - Exception calling application: [Errno 2] No such file or directory: '/mnt/storage-pool-1/info/subvol/a8/11/pvc-07decc5a-7c87-4b70-be92-2243021a45b9.json'
Traceback (most recent call last):
  File "/kadalu/lib/python3.10/site-packages/grpc/_server.py", line 444, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/controllerserver.py", line 667, in ControllerExpandVolume
    update_subdir_volume(
  File "/kadalu/volumeutils.py", line 485, in update_subdir_volume
    update_pv_metadata(hostvol_mnt, volpath, expansion_requested_pvsize)
  File "/kadalu/volumeutils.py", line 607, in update_pv_metadata
    with open(info_file_path + ".json", "r") as info_file:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/storage-pool-1/info/subvol/a8/11/pvc-07decc5a-7c87-4b70-be92-2243021a45b9.json'
```

**Environment:**

 - Kadalu Version: 0.8.14
 - K8S_DIST: kubernetes

**Additional context**
I've tried to troubleshoot this issue myself, so here's the result of my investigation/debugging

So as I understood the cause of the error log above is because the condition that sets 'pvtype' in ControllerExpandVolume is not valid
https://github.com/kadalu/kadalu/blob/devel/csi/controllerserver.py#L635
Instead of `request.volume_capability.AccessMode` there's should be a `request.volume_capability.access_mode.mode`, because `request.volume_capability` does not have attribute AccessMode:

```
volume_id: "pvc-07decc5a-7c87-4b70-be92-2243021a45b9"
capacity_range {
  required_bytes: 2147483648
}
volume_capability {
  mount {
  }
  access_mode {
    mode: SINGLE_NODE_WRITER
  }
}
```

After updating condition, like I mentioned above, I've faced another error, this time related to mkfs.xfs command (please ignore timestamp and PVC name, this is the output of a different PVC):

```
[2022-05-21 10:19:34,473] ERROR [_server - 454:_call_behavior] - Exception calling application: [1]  mkfs.xfs: /mnt/storage-pool-1/virtblock/90/1f/pvc-b2a8e573-4e39-44d5-b9fe-501839456ade appears to contain an existing filesystem (xfs).
mkfs.xfs: Use the -f option to force overwrite.
Traceback (most recent call last):
  File "/kadalu/lib/python3.10/site-packages/grpc/_server.py", line 444, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/controllerserver.py", line 666, in ControllerExpandVolume
    update_virtblock_volume(
  File "/kadalu/volumeutils.py", line 579, in update_virtblock_volume
    execute(MKFS_XFS_CMD, volpath_full)
  File "/kadalu/kadalulib.py", line 156, in execute
    raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1]  mkfs.xfs: /mnt/storage-pool-1/virtblock/90/1f/pvc-b2a8e573-4e39-44d5-b9fe-501839456ade appears to contain an existing filesystem (xfs).
mkfs.xfs: Use the -f option to force overwrite.
```
So what happened is that in the Kadalu tried to create a XFS file system on the device that already have one - https://github.com/kadalu/kadalu/blob/devel/csi/volumeutils.py#L575 
I assume that this behavior is not valid, since making a filesystem on PV is part of 'create_block_volume' function, not 'update_virtblock_volume' function. 

And the last thing, as part of the debugging, I've tried to remove block that tries to create XFS in 'update_virtblock_volume' function and get next error:
```
[2022-05-21 11:34:59,333] ERROR [_server - 454:_call_behavior] - Exception calling application: [1]  xfs_growfs: /mnt/storage-pool-1 is not a mounted XFS filesystem
Traceback (most recent call last):
  File "/kadalu/lib/python3.10/site-packages/grpc/_server.py", line 444, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/controllerserver.py", line 665, in ControllerExpandVolume
    expand_volume(mntdir)
  File "/kadalu/volumeutils.py", line 898, in expand_volume
    execute("xfs_growfs", "-d", mountpoint)
  File "/kadalu/kadalulib.py", line 156, in execute
    raise CommandException(proc.returncode, out.strip(), err.strip())
kadalulib.CommandException: [1]  xfs_growfs: /mnt/storage-pool-1 is not a mounted XFS filesystem
```

So the last error indicates, that Kadalu tried to run xfs_growfs on '/mnt/storage-pool-1' which is not actually what I wanted, as it should run xfs_growfs for the PV, not the whole storage pool.
And here come a tricky part which I'm not sure how can be solved. In order to run xfs_growfs, the volume should be mounted and I can't find the code (except the one which is for 'nodeservers') that mounts the virtual volumes. Also, since a block volume can be attached only to 1 node, I don't think that it would be possible to mount it using 'mount_volume' function on the provisioner (kadalu-csi-provisioner-0 pod) . Actually, I did try to mount it manually by running `mount /mnt/storage-pool-1/virtblock/dd/ab/pvc-03687cff-ef5b-40e1-a7d2-8419acb3bdd0 /tmp && xfs_growfs /tmp` on 'kadalu-csi-provisioner-0' pod - that didn't end up successfully, and I believe that this is a wrong in way to do it. To me it seems like the task of extending XFS file system should be delegated to 'nodeservers' (kadalu-csi-nodeplugin pods) because they are responsible for mounting 'exclusive' volumes to node and they will be able to run 'xfs_growfs' after the volume is mounted

**Comment by leelavg** [comment]
@nzolot wow, this is a good report and analysis is added bonus, thanks a lot.

- well the bugs are evident so, not repeating them

> To me it seems like the task of extending XFS file system should be delegated to 'nodeservers' 
- sounds reasonable, let me recheck if this is the only way

> mounting 'exclusive' volumes to node
- iirc, there's nothing limiting us to make the op from provisioner in the sense that provisioner will never do IO 😅

Extra: seeing these issues it seems there's no test coverage, let's try to add that as well.

**Comment by nzolot** [comment]
hi @leelavg, thanks for the quick reply

> this is a good report and analysis is added bonus, thanks a lot.

hopefully I didn't messed up anything and understood the conceptions :smiley: 

> iirc, there's nothing limiting us to make the op from provisioner in the sense that provisioner will never do IO

I believe that we "need" to make an IO as part of xfs_growfs, I've tried to run it manually from the provisioner, as a result the file system was extended from provisioner point of view, but pod did not reflect the changes. It got even worse when I've tried to write the files from the pod - changes were not reflected on the provisioner. But maybe I'm just doing it wrong

On the other hand, I've tried to run xfs_growfs on the node and it did work as expected
```
$ df -h | grep pvc-07decc5a-7c87-4b70-be92-2243021a45b9
/dev/loop0                    1014M   40M  975M   4% /var/lib/kubelet/pods/999d5596-5550-49b6-9190-4280b4100233/volumes/kubernetes.io~csi/pvc-07decc5a-7c87-4b70-be92-2243021a45b9/mount

$ xfs_growfs /var/lib/kubelet/pods/999d5596-5550-49b6-9190-4280b4100233/volumes/kubernetes.io~csi/pvc-07decc5a-7c87-4b70-be92-2243021a45b9/mount
meta-data=/dev/loop0             isize=512    agcount=4, agsize=65536 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=1        finobt=1, sparse=1, rmapbt=0
         =                       reflink=1
data     =                       bsize=4096   blocks=262144, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
log      =internal log           bsize=4096   blocks=2560, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
data blocks changed from 262144 to 524288

$ df -h | grep pvc-07decc5a-7c87-4b70-be92-2243021a45b9
/dev/loop0                     2.0G   47M  2.0G   3% /var/lib/kubelet/pods/999d5596-5550-49b6-9190-4280b4100233/volumes/kubernetes.io~csi/pvc-07decc5a-7c87-4b70-be92-2243021a45b9/mount

```

**Comment by leelavg** [comment]
> On the other hand, I've tried to run xfs_growfs on the node and it did work as expected
- got it, it's not `volumeMode: Block` which'll be handled by k8s, however it's `pv_type: Block` which should be handled by kadalu and it seems we are missing some steps along the way
- will take a look when I'm near my workstation

**Comment by leelavg** [comment]
@nzolot 
- along with multiple fixes this issue should be fixed by #828  and will be part of next release.
- if you've a test environment you can try out devel (after 30 min) or you can wait for release and close this issue
- btw, pls note you've to set `allowVolumeExpansion: true` in your custom storage class in-order to support pv expansion

**Comment by nzolot** [comment]
hi @leelavg ,

Thanks for the fix, I'll give it a try as soon as I will have some free time

**Comment by leelavg** [comment]
- should work with v0.8.15 now, reopen if there are any issues.
