### ISSUE TITLE
[Bug]: pod/kadalu-csi-nodeplugin-XXXXX reports "E [fuse-helpers.c:203:frame_fill_groups] 0-fuse: WRITE: failed to open /proc/0/status: No such file or directory"

### ISSUE THREAD

**Issue by hunter86bg** [kadalu/kadalu#827]
**Describe the bug**
It seems that kadalu-csi-nodeplugin pod constantly errors with:
```
[2022-05-27 01:30:22.807481 +0000] E [fuse-helpers.c:203:frame_fill_groups] 0-fuse: STAT: failed to open /proc/0/status: No such file or directory
[2022-05-27 01:30:22.947896 +0000] E [fuse-helpers.c:203:frame_fill_groups] 0-fuse: WRITE: failed to open /proc/0/status: No such file or directory
```

**To Reproduce**
1. Setup a replica 3
2. Leave the setup running for 17 days

**Expected behavior**
No errors should be observed in the logs

**Actual behavior**
The pod spams with errors.

**Environment:**
kubectl-kadalu plugin: 0.8.9
kadalu pod(s) versions
pod/kadalu-csi-nodeplugin-dfjm4: 0.8.14
pod/kadalu-csi-nodeplugin-kvts6: 0.8.14
pod/kadalu-csi-provisioner-0: 0.8.14
pod/operator-54696d985f-vmrmh: 0.8.14
pod/server-gluster-0-0: 0.8.14
pod/server-gluster-1-0: 0.8.14
pod/server-gluster-2-0: 0.8.14

**Screenshots or Logs**
https://drive.google.com/file/d/1jyW5qUerREr4OUI9NE2xx51om_IkarbV/view?usp=sharing

**Additional context**

**Comment by amarts** [comment]
This is an issue fixed in GlusterFS upstream. Will send a patch to kadalu branch. Currently this is harmless other than filling the logs.
