### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by patama8** [kadalu/kadalu#829]
**Describe the bug**

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**Environment:**

 - Kadalu Version: [e.g., 0.8.6]
 - K8S_DIST: [e.g., kubernetes, openshift]

**Screenshots or Logs**
If applicable, add any screenshots to help explain your problem. Try capturing relevant logs, post them to http://gist.github.com/ and post the links in the issue.

**Additional context**

**Comment by leelavg** [comment]
Details not provided.

**Comment by patama8** [comment]
🙂🤨

**Comment by patama8** [comment]
🙂🤨
