### ISSUE TITLE
Backup and Recovery

### ISSUE THREAD

**Issue by c-seeger** [kadalu/kadalu#831]
**Is your feature request related to a problem? Please describe.**
What are the current options to handle backup and recovery szenarios

**Describe the solution you'd like**
simple tool to manage backup and recovery. Does kadalu work with velero?

**Describe alternatives you've considered**
still researching for backup and recovery strategies

**Comment by leelavg** [comment]
- it's being looked into however another feature took priority and so pls expect delay
- just wanted to update rather than leaving as unattended
