### ISSUE TITLE
Provide documentation for GitOps oriented setup and configuration

### ISSUE THREAD

**Issue by Timoses** [kadalu/kadalu#835]
A lot of times it is more desirable to provision an application via Kubernetes resources directly rather than using a CLI tool.
This allows integration with GitOps workflows and is more declarative in nature.

I'd suggest adding a section at least in the **Setup** part of the documentation how to install Kaladu declaratively: https://kadalu.io/docs/k8s-storage/latest/setup/

Two options can be offered as I see currently:
* Helm
* Raw kubernetes manifests from a release, e.g.:
    ```
     - https://github.com/kadalu/kadalu/releases/download/0.8.14/kadalu-operator.yaml
     - https://github.com/kadalu/kadalu/releases/download/0.8.14/csi-nodeplugin.yaml
    ```

This also should prevent folks from peeking into the `./manifests` directory directly which is not updated with correct version tags on commits.

**Comment by leelavg** [comment]
@Timoses we did document that here https://kadalu.io/docs/k8s-storage/latest/quick-start-yaml/.

Nevertheless, I'd say krew `kubectl krew install kadalu` iirc, will be the easiest for long term use and deploying manifests which was documented above for quick start in ops style.

**Comment by Timoses** [comment]
Oh thanks for the pointer. I overread it and jumped right to `Setup`.

Can be closed on my part.
