### ISSUE TITLE
[RFE]: Use /lib/modules as server component's kernel modules path or use configurable parameter

### ISSUE THREAD

**Issue by Timoses** [kadalu/kadalu#836]
**Is your feature request related to a problem? Please describe.**
The Kadalu server component mounts the hostPath `/usr/lib/modules`. 
This path may not exist at this specific path for every environment.
FSH states `/lib/modules` (https://refspecs.linuxfoundation.org/fhs.shtml).
In my specific case, Talos uses this `/lib/modules/` path.

**Describe the solution you'd like**
Server component should ideally use `/lib/modules` or if this leads to incompatibility issues (at which point I'd point out FHS) make it a configurable template parameter.

**Describe alternatives you've considered**
I do not see an alternative. `kustomize` is no option as it is an `operator` generated resource.

**Additional context**
Talos v1.0.4
Kadalu v0.8.14

**Comment by leelavg** [comment]
- thanks for raising the issue
- if `/lib/modules` is universally available then the change will be straightforward https://github.com/kadalu/kadalu/blob/devel/templates/server.yaml.j2#L94
- if that's not the case, we need to decide from where this option should flow into the destination manifest
- either ways, I'd like to hear from @amarts when he get time

**Comment by amarts** [comment]
I am fine with this change. This came in with e30524c8 and looks like it came from [gluster/gcs](https://github.com/gluster/gcs/blob/master/deploy/templates/gcs-manifests/gcs-gd2.yml.j2) project.

I think we can experiment even removing `gluster-kmods` section there. @aravindavk any concerns there?
