### ISSUE TITLE
[RFE]: Hardening RBAC rules

### ISSUE THREAD

**Issue by Timoses** [kadalu/kadalu#838]
**Is your feature request related to a problem? Please describe.**
Currently, Kadalu basically receives permissions onto the complete cluster. For security minded folks this is an issue and inhibits adoption of Kadalu.

**Describe the solution you'd like**
1. Revise operator RBAC permissions:
    * These should be narrowed down as much as possible (e.g. using namespaced Roles where applicable, granting only those API permissions needed for its operation)
2. Move RBAC definitions from [csi template](https://github.com/kadalu/kadalu/blob/devel/templates/csi.yaml.j2) into the operator manifest:
    * Defining them in the template obfuscates their existence. Having RBAC in one place gives a better overview.
    * Operator otherwise requires permissions to create these roles which means it can grant itself any other permissions
3. Specify separate RBAC rules for each CSI components (e.g. have a 'kadalu-external-provisioner' (cluster)role for [External Provisioner](https://github.com/kubernetes-csi/external-provisioner/blob/master/deploy/kubernetes/rbac.yaml)) which are then bound to the CSI controller service account. This should give a better overview of where RBAC requirements come from.

**Describe alternatives you've considered**
Perhaps it would also be an option to provide all RBAC related resources in an extra manifest `rbac.yaml`?

**Additional context**
I can take a look into it if you like. I'd be happy about pointers.
So far, I have identified:

**Operator's RBAC requirements** which are basically defined in the operator's calls to the API and `lib_execute(kubectl...)` calls in the `main.py` and the relating templates.

**Kadalu-Provisioner** requires [secret access](https://github.com/kadalu/kadalu/blob/devel/csi/controllerserver.py#L277) (thanks Leela for the pointer).

**CSI external components**: 
* [External provisioner](https://github.com/kubernetes-csi/external-provisioner/blob/master/deploy/kubernetes/rbac.yaml):
    * [secrets](https://github.com/kubernetes-csi/external-provisioner/blob/master/deploy/kubernetes/rbac.yaml#L24): **no** as far as I can see  (I understand it would mean the StorageClass definition would point to secrets to be passed to the CSI plugin)
    * [`PUBLISH_UNPUBLISH_VOLUME`](https://github.com/kubernetes-csi/external-provisioner/blob/master/deploy/kubernetes/rbac.yaml#L53) capability: **[yes](https://github.com/kadalu/kadalu/blob/devel/csi/protos/csi.proto#L885)**
    * [leadership election](https://github.com/kubernetes-csi/external-provisioner/blob/master/deploy/kubernetes/rbac.yaml#L77): **No**, [only one CSI controller pod via sts](https://github.com/kadalu/kadalu/blob/devel/templates/csi.yaml.j2#L178)
* [Attacher](https://github.com/kubernetes-csi/external-attacher/blob/master/deploy/kubernetes/rbac.yaml):
    * [secrets](https://github.com/kubernetes-csi/external-attacher/blob/master/deploy/kubernetes/rbac.yaml#L37): **no**, storageclasses in `templates/` do not seem to support this.
    * [leadership election](https://github.com/kubernetes-csi/external-attacher/blob/master/deploy/kubernetes/rbac.yaml#L61): **no**
* [Resizer](https://github.com/kubernetes-csi/external-resizer/blob/master/deploy/kubernetes/rbac.yaml):
    * [secrets](https://github.com/kubernetes-csi/external-resizer/blob/master/deploy/kubernetes/rbac.yaml#L25): **no**
    * [leader election](https://github.com/kubernetes-csi/external-resizer/blob/master/deploy/kubernetes/rbac.yaml#L62): **no**

Let me know what you think.

**Comment by leelavg** [comment]
@Timoses thanks for the rfe and related analysis.
- Refining rbac is required as we are sprinting towards GA (version 1.0)
- IMHO, currently kadalu supports many features even without GA and I know of users using it in prod, so rbac changes should be done with caution
- I'm thinking to move the usage of secret which should be created before deploying kadalu as of now to one of the generated storageclasses as csi supports it
- You can start working on this if you gained good enough breadth and depth of the code base (I'd say the code is straightforward with not much quirks)
- However, pls do ask for any pointers if required and I'll also take a look at rbac at the earliest

**Comment by leelavg** [comment]
Hi @Timoses 
- I want to have this conversation after initial cut is passing CI, since it's working now, do you want current PR to be merged and still like to work on moving rbac to single file in separate PR?
- If you can't take that up, I need to work on that since having all rbac in a single place seems to be the correct way for visibility and debugging.

**Comment by Timoses** [comment]
>     * I want to have this conversation after initial cut is passing CI, since it's working now, do you want current PR to be merged and still like to work on moving rbac to single file in separate PR?

I added a commit which puts it into a single `rbac.yaml`. Feel free to remove the commit or leave it in.

>     * If you can't take that up, I need to work on that since having all rbac in a single place seems to be the correct way for visibility and debugging.

Since CSI-Nodeplugin is a separate chart, I'd leave the RBAC things separate, too.
Though, perhaps it should also be called `rbac.yaml` there also then?

**Comment by leelavg** [comment]
- I'm thinking more like,
1. operator_rbac.yaml - role, rolebinding, serviceaccount of operator
2. controllerplugin_rbac.yaml - role, rolebinding, serviceaccount of csi controller (including side cars)
3. nodeplugin_rbac.yaml - similar content as above but separate chart

I believe it'll neither be too detailed (rbac file for every resource of every component) nor single bulky one, agreeable?

**Comment by Timoses** [comment]
> * I'm thinking more like,
> 
> 
>     1. operator_rbac.yaml - role, rolebinding, serviceaccount of operator
> 
>     2. controllerplugin_rbac.yaml - role, rolebinding, serviceaccount of csi controller (including side cars)
> 
>     3. nodeplugin_rbac.yaml - similar content as above but separate chart
> 
> 
> I believe it'll neither be too detailed (rbac file for every resource of every component) nor single bulky one, agreeable?

Not sure what extra info would be extracted from naming files. The (cluster)role(binding) resource names are already pretty self-explanatory, aren't they? Plus, most of the time people don't even look at rbac that closely. But if they do, it's in one file.

I don't see the advantage of separating over several files ;).
