### ISSUE TITLE
[RFE]: Code organization to improve the build/requirements issues

### ISSUE THREAD

**Issue by aravindavk** [kadalu/kadalu#847]
Code reorganization: For better reuse of common code and to avoid redundant copies of Python files.

```
$ROOT/
    - setup.py
    - kadalu/
        - __init__.py
        - common/       # Helpers
        - operator/
        - csi/
        - server/
```
- kadalu will become main package and all others are sub packages. Common code can be accessed as `from kadalu.common import execute` 
- `setup.py` can list all the dependencies in one place.
- `setup.py` also creates executables using console script
```
    entry_points={
        "console_scripts": [
            "kadalu-operator = kadalu.operator.main:main",
            "kadalu-csi = kadalu.csi.main:main",
            "kadalu-server = kadalu.server.main:main",
        ]
    },
```

In respective Dockerfile, copy this directory and install by running `python3 setup.py install` and start the respective process by calling

```
ENTRYPOINT ["kadalu-operator"]
```

Because of GRPC dependency, container image size may grow for non-csi containers. To avoid this, we can have all other dependencies listed in setup.py and install grpc separately in CSI container image.

**Comment by leelavg** [comment]
- I've some doubts around using only setup.py and not pip-compile
- Will the console_scripts takes care of copying required modules?
- Either ways, can we do a release sometime this week and work on reorganisation at the earliest?

**Comment by aravindavk** [comment]
> * I've some doubts around using only setup.py and not pip-compile

Anything is fine. Since this is controlled setup, Even virtual env is also not having many advantages compared to direct installation of modules.

> 
>     * Will the console_scripts takes care of copying required modules?

Console script creates a binary file in `/usr/bin` which calls the specified module and function. https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point

> 
>     * Either ways, can we do a release sometime this week and work on reorganisation at the earliest?

Ack for the release. This is not a release blocker.
