### ISSUE TITLE
[Bug]: High CPU usage in operator

### ISSUE THREAD

**Issue by TonyBogdanov** [kadalu/kadalu#852]
**Describe the bug**
When the operator is running on a cluster with nodes that are frequently rotated, the operator goes into a state of high CPU usage the first time a large batch of nodes are added/removed, and remains there indefinitely.

In my particular case I have 20 ephemeral nodes that are provisioned in order to handle some jobs and then deleted about 10 minutes later. During that time the daemonset creates `csi-nodeplugin` pods on each node, which the operator talks to.

The `csi-nodeplugin` pods themselves behave normally all of the time, but the operator goes crazy and stays there.

Using `iftop` on the operator pod I can see a constant ~5mb/s transfer between the pod and `kubernetes.default.svc.cluster.local`. My personal best guess is that the operator connects to the newly created csi pods and does not clean up the connections when they die.

Maybe keeps trying to poll them or something like that?

**To Reproduce**
1. Install the kadalu operator.
2. Create 20 nodes and wait for the `csi-nodeplugin` daemonset to boot up pods.
3. Delete the 20 nodes.
4. The operator remains in a high CPU usage state until it is restarted.

**Expected behavior**
The operator should remain at a sane CPU usage level.

**Actual behavior**
The operator uses too much CPU after having a batch of nodes added and then removed.

**Environment:**

 - K8S_DIST: **kubernetes**
 - kubectl-kadalu plugin: **0.8.14**
 - pod/kadalu-csi-nodeplugin-2g9rz: **0.8.14**
 - pod/kadalu-csi-nodeplugin-68567: **0.8.14**
 - pod/kadalu-csi-nodeplugin-gtd2n: **0.8.14**
 - pod/kadalu-csi-nodeplugin-hcp56: **0.8.14**
 - pod/kadalu-csi-nodeplugin-hhdtj: **0.8.14**
 - pod/kadalu-csi-nodeplugin-jx4cb: **0.8.14**
 - pod/kadalu-csi-nodeplugin-qdv6q: **0.8.14**
 - pod/kadalu-csi-nodeplugin-zbtlz: **0.8.14**
 - pod/kadalu-csi-provisioner-0: **0.8.14**
 - pod/operator-6bcc99cff4-6q428: **0.8.14**
 - pod/server-storage-0-0: **0.8.14**
 - pod/server-storage-1-0: **0.8.14**
 - pod/server-storage-2-0: **0.8.14**

**Comment by TonyBogdanov** [comment]
Persists in release: **0.8.15**.

**Comment by leelavg** [comment]
> The operator uses too much CPU after having a batch of nodes added and then removed.
- are you using metrics exported by operator?
- as you stated network transfer I believe operator is trying to get metrics from all kadalu components and when nodes being ephemeral in your use-case that might be the reason increasing the CPU
- if you aren't using prometheus scraping we need to look the issue from different perspective as operator to my knowledge doesn't communicate with nodeplugin except for this case

**Comment by TonyBogdanov** [comment]
@leelavg Thanks for the quick response and yes, I am using prometheus. I have an in-house operator handling some other stuff including auto-growing PVCs, so I need the metrics.

Now that I think about it, the operator trying to communicate with the nodes is most probably the cause of this. In addition I often get timeouts or `Internal Server Error` responses when trying to access `/metrics.json` precisly because the operator is unable to communicate with *some* nodes of the daemonset at that exact moment.

I am not sure but I think the operator tries to reach each node each time `/metrics.json` is requested. A better way, imo, would be to do that in the background at an interval and cache the summary to serve on `/metrics.json`. Would probably make the operator more lightweight as well.

**Comment by leelavg** [comment]
> operator tries to reach each node each time /metrics.json is requested
- yes, that's how it's implemented, when prom scrapes operator ep, operator will in-turn reaches out to all kadalu components for new data

> cache the summary to serve
- maybe in most of the scenarios the cache maybe invalid? for ex: in your case, a data point from nodeplugin-a might not exist after the job completes

@aravindavk any deductions for the issue?

**Comment by TonyBogdanov** [comment]
> maybe in most of the scenarios the cache maybe invalid? for ex: in your case, a data point from nodeplugin-a might not exist after the job completes

True, but it has to be a compromise either way I think.

If cached we risk stale metrics for whatever the scraping interval is configured to be. But if we scrape each time we risk high CPU and timeouts. But even if fresh metrics are more important so that the current implementation is the better way, at least it should be able to fail gracefully for unreachable nodes. Right now I either get internal server error, or an overall timeout of the metrics endpoint even if just one node is being added / removed at that particular time, meaning it breaks metrics for all other nodes as well..

**Comment by leelavg** [comment]
- ack, we can introduce the classic solution, the rate-limiter assuming prom metrics scraping are DDoS attacks 😅
- however, doesn't prometheus has a scrape interval which can be adjusted, basically fixing at the source (prom config)/outside of kadalu?
- I'd vote for adjusting prom scrape duration, we'll think of rate-limiter only as a last resort

**Comment by TonyBogdanov** [comment]
@leelavg The problem is not the rate of scraping, I mean, sure, that'll help with CPU usage overall. But the real issue is the operator *crashing* (sort of) when it's unable to reach one of the CSI nodes during a request from prometheus.

If it were able to fail gracefully and just skip that node in the metrics when prometheus asks for metrics, that'd be totally fine by me. As long as that one "broken" node doesn't break the whole request.

But more importantly, I think the high CPU comes from the operator trying to contact nodes that are long gone already, possibly accumulating the requests as more and more nodes die and new ones are added.

In my current setup I have about 20 nodes added and then deleted each hour. This means that after just one day I'll have 480 dead nodes that the operator is still trying to connect to and ask for metrics (when does the operator consider a node dead and removed?). If this is indeed the case, I don't think prometheus rate limiting can solve it.

**Comment by leelavg** [comment]
> This means that after just one day I'll have 480 dead nodes that the operator is still trying to connect to.
- makes sense, noted.

- I'll wait for @aravindavk / @vatsa287 to respond on this as I didn't get a chance to look at current metrics ops good enough
- Pls expect a delay in response, temporarily you might want to stop metrics scrapping 🤔

**Comment by TonyBogdanov** [comment]
@leelavg Actually I have a script which restarts the operator process once each 5 minutes and it works just fine this way. Which is why it's making me think about this "accumulation" scenario.

So, regardless of the number of nodes currently in the cluster, the operator works fine as long as we are not adding / removing a bunch **while** the operator is running.

I've tested it with 70 nodes and it still works nicely, so it's not about the number of resources, it's about their state (running, timing out or out-right dead).

**Comment by Expro** [comment]
I'm experiencing same issue (high CPU usage of operator), but my environment is static - 3 nodes, none added or removed. Operator starts fine and uses CPU in sane manner, but after some time it starts hammering API server, making both operator and API server pods burn CPU cycles.

**Comment by leelavg** [comment]
@Expro do you also use prometheus?

**Comment by Expro** [comment]
No.

**Comment by leelavg** [comment]
@Expro then it might be a different, better raise a separate issue.

At the same time do you see continuous error logs in operator?

**Comment by Expro** [comment]
No, nothing - operator's logs just lists ConfigMaps for StorageClasses. No new entries before and after CPU usage elevation.

**Comment by Expro** [comment]
CPU ramps up in less than 1 hour without any admin activity on cluster:
![image](https://user-images.githubusercontent.com/381025/179938112-10ad7b4c-cde1-4a45-96e8-a446708b3026.png)

I'm on 0.8.15, for 0.8.14 behaved in same way.

**Comment by leelavg** [comment]
- thanks for checking
- that chart definitely shows some issue exist in operator
- can you set `VERBOSE` env value to `yes` in operator deployment
- this will not have any side effect in a running cluster

**Comment by Expro** [comment]
Changed VERSOBE to yes. Operator did change level of details for log messages (so it was applied correctly), but there is no new log entries between time when operator was working correctly and time when operator started smashing API server. CPU ramped up without any trace in operator's log,

**Comment by a10sbraun** [comment]
I notice the same after some time, even if it idles. 
Operator (on node1) stress my K3S server (api)

```
micro-n1:~ # ps aux | grep python
USER      PID   %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      3190  0.0  0.4  19780 15868 ?        Ss   14:51   0:00 python3 /kadalu/start.py
root      3231  0.0  1.0 489752 37916 ?        Sl   14:51   0:00 python3 /kadalu/main.py
root      3232  0.1  0.9 142756 34004 ?        Sl   14:51   0:03 python3 /kadalu/exporter.py
root      3295  0.0  0.6  30228 22752 ?        Ss   14:51   0:00 python3 /kadalu/server.py
root      3377  0.1  0.8 139212 32344 ?        Sl   14:51   0:03 python3 /kadalu/exporter.py
root      3666  0.0  0.4  19780 16228 ?        Ss   14:51   0:00 python3 /kadalu/start.py
root      3679  0.0  0.9 489748 34636 ?        Sl   14:51   0:01 python3 /kadalu/main.py
root      3680  0.1  0.9 142756 33908 ?        Sl   14:51   0:03 python3 /kadalu/exporter.py
root      3848  0.0  0.4  18852 15124 ?        Ss   14:51   0:00 python3 /kadalu/start.py
root      3884 20.9  1.7  70276 63172 ?        S    14:51   9:41 python3 /kadalu/main.py
root      3885  0.1  1.0 144728 37976 ?        Sl   14:51   0:03 python3 /kadalu/exporter.py
```
![Screenshot from 2022-07-21 15-38-26](https://user-images.githubusercontent.com/74243350/180228170-6ec254eb-e1c9-44df-bfec-c65c48ed0d68.png)

and here after deleting
![Screenshot from 2022-07-21 15-48-01](https://user-images.githubusercontent.com/74243350/180229564-acc98084-8e06-4474-be54-4191d4767f28.png)

**Comment by leelavg** [comment]
- woah, three instances of same issue
- will take a look at the earliest
- I'm assuming https://github.com/kadalu/kadalu/blob/ed620e/kadalu_operator/main.py#L885-L889 is the suspect
- I may not be able to reproduce this in my dev k3d env so pls expect some delay

**Comment by leelavg** [comment]
- not able to reproduce the high cpu issue in my setup
- as the original observation is for the ephemeral nodes, in the linked PR I removed redundant data collection from nodeplugins, hopefully it should've some positive effect

**Comment by drbardin** [comment]
Updated kadalu to 0.8.17, persistent CPU spike ~45 minutes after restart of operator pod still exists, unfortunately. 

AWS EC2 t3.xlarge
Kubernetes 1.23.5 - single node cluster, non-ephemeral.

**Comment by vincentchong1** [comment]
@leelavg, what do you think may be the problem due to /kadalu/main.py L912 
https://github.com/kadalu/kadalu/blob/ed620e12493bd87f0f91beb980de7eb6c2a547dd/kadalu_operator/main.py#L912
which the while loop need to have sleep for both Try and Except?

**Comment by leelavg** [comment]
- don't think so, the `watch_stream` is a generator type thingy and only be executed when there's an interested event
- `sleep` is when we are hitting an expection everytime

If a simple reproducer can be mentioned by any one of the reporters, I'll try to fix it.

**Comment by vincentchong1** [comment]
@leelavg , may I know how to restart the main.py inside the operator.  I notice most of the ps and kill command are no longer available.  I am using 0.8.14.
high CPU usage is currently still occurring in my environment, I will like to try out something.

**Comment by leelavg** [comment]
- If possible I think it's better to update kadalu for `ps`
- I also found the issie and later included ps-util explicitly
- It's a tough task to find `main.py` unfortunately
