### ISSUE TITLE
Helm installation - KadaluStorage race condition

### ISSUE THREAD

**Issue by natanbs** [kadalu/kadalu#875]
Hi,
I am installing Kadalu (external) installing with Helm and found a race condition:
Kind KadaluStorage does not create the pv unless the operator / provisioner are in "Running" state. So KadaluStorage kind must be created only after kadalu is up and running.
And I can't use a post installation hook to create the kind object.

Currently I apply the KadaluStorage once the helm installation is completed.
This worked for me untill I needed to add a post install hook for the application. That pod is waiting for the pv and helm is waiting for the hook to complete.
Without the post install hook, helm completes before the pods and  I can proceed applying the KadaluStorage. Then the dependent pods can complete their installation. 

How should I approach this racing condition?

Regards,
Natan.

**Comment by leelavg** [comment]
- hello, thanks for raising the issue.
- this should be a straight-forward fix since we solely use helm for manifest generation now
- iirc, just moving the CRDs into `crds/` dir of helm would be good enough

will take a look at the earliest.

**Comment by leelavg** [comment]
- #877 should fix the CRD issue however there's still a chance that your app hook might fail if your workload ask for a kadalu pvc before operator is running
- do you have anything to add?

**Comment by natanbs** [comment]
Thanks,
The issue was already resolved shortly after I opened the ticket.

Thanks for your quick and efficient support!

Regards,
Natan.
