### ISSUE TITLE
[Bug]: PVC periodically falls off

### ISSUE THREAD

**Issue by ghost** [kadalu/kadalu#881]
Hello dear community!

1. `Kadalu` installed via `Helm` (`operator` + `csi-nodeplugin`)
2. Connected to external `GlusterFS` (via `KadaluStorage`)

Kubernetes version: `1.23.7`
Kadalu version: `0.8.15`

Periodically, PVC in pods become in 'Socket not connected state'. Deleting kadalu pods & pod with PVC solve the problem.

Log: https://file.io/KwgWueLB3VQu

Thanks in advance!

**Comment by leelavg** [comment]
- The log is huge and will get back to the issue, in the meantime your automation/prom scraping is hammering the kadalu metrics collection, you may want to increasing the scraping interval
```
$ grep -c '200 OK' Downloads/log.txt
62673

$ grep -cv '200 OK' Downloads/log.txt
34843
```

**Comment by leelavg** [comment]
- ntg is evident from the logs except below
```
[2022-08-02 15:05:38,088] ERROR [volumeutils - 1219:mount_glusterfs] - Unable to set quota-deem-statfs via ssh   error=[1]  Warning: Permanently added '172.16.9.170' (ECDSA) to the list of known hosts.

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified
[2022-08-02 15:05:38,088] ERROR [main - 41:mount_storage] - Unable to mount volume       hvol=dmz-gluster-ts-sdb
[2022-08-02 15:05:38,092] INFO [main - 75:main] - Server started
```
> Deleting kadalu pods & pod with PVC solve the problem.
- Simply scaling your app pod should fix this, mostly the underlying nodeplugin restarted and workloads running on that node if using kadalu pvc has lost mount availability
- This is a known issue across CSI plugins which provides FUSE based storage

**Comment by ghost** [comment]
@leelavg so your suggestion is to try is to scale `kadalu-csi-provisioner-0`?

**Comment by ghost** [comment]
or to scale pod with running app (loki e.g.)?

**Comment by leelavg** [comment]
- pod running the app if you had observed that kadalu nodeplugin on that node was restarted

**Comment by ghost** [comment]
@leelavg then why kadalu do not restart itself in order to fix this, if PVC falls of app pod?

**Comment by leelavg** [comment]
- nope, we (kadalu) will never restart the user workloads
- do you see any issues from nodeplugin to external gluster in the log @amarts, ptal when you get time

**Comment by ghost** [comment]
from nodeplugin (after killing old pods): https://file.io/5QNUzvI8gBLo
if we will receive new fall off, will send

**Comment by leelavg** [comment]
- I never mentioned to kill nodeplugin
- Below are the kadalu components if you are using external gluster
1. operator
2. provisioner
3. nodeplugin
- when you perform ops on storage pool (kadalu CR), operator is involved
- when you create/delete PVCs, provisioner is involved
- when you use the PVCs, nodeplugin is involved
- given above, let's say pvc-1 is created by provisioner and app-a claimed that pvc and k8s scheduler decided that app-a can run on node-x
- so, the pvc-1 will be mounted in the nodeplugin running on node-x and inturn mounted into app-a
- now, what I meant in earlier comment was, if for any reason nodeplugin running on node-x is restarted, app-a will not be able to access the pvc-1 and so you need to restart app-a which will make pvc-1 to be mounted on app-a
- generally, pods (app-a) are deployed using deployment/statefulset, in that scenario you can scale the replica to 0 and back to 1, even if app-a gets scheduled on a different node, let's say node-y, nodeplugin running on node-y will serve the same pvc-1 to your app-a

I hope above clears any confusion, for more info you may want to reach out to CSI docs/spec.

**Comment by ghost** [comment]
One more log: https://file.io/SH7BGpkYQKgU
Here nodeplugin starts to send a lot of errors.

**Comment by ghost** [comment]
New log when PVC falls of and nodeplugin container restarted with error: https://file.io/e524cp7Zq4HW
