### ISSUE TITLE
[RFE]: Host containers in ghcr.io (Github)

### ISSUE THREAD

**Issue by fastlorenzo** [kadalu/kadalu#902]
**Is your feature request related to a problem? Please describe.**
Docker hub implemented rate limiting for pulling containers (100 pulls /6h /ip for unauthenticated users, 200 for authenticated users).
https://docs.docker.com/docker-hub/download-rate-limit/

**Describe the solution you'd like**
It would be great to push the Kadalu containers to GitHub packages (ghcr.io), this is free and would show up on the project page on the right pane, under "packages".
This would require minimal changes on the GH actions:
- Login to GHCR using Github token
- Add tags to containers (ghcr.io/kadalu/...)
The GH Action should then push containers to both Docker Hub and GHCR

**Describe alternatives you've considered**
I could have a process to host them myself on GHCR, but it would require more effort to maintain it in sync when new versions are released.

**Additional context**
N/A

**Comment by amarts** [comment]
Thanks for the suggestion. We will surely consider this.
