### ISSUE TITLE
[Bug]: server component attempts to mount /usr/lib/modules instead of /lib/modules

### ISSUE THREAD

**Issue by Timoses** [kadalu/kadalu#904]
**Describe the bug**
The following Feature Request was intended to be solved by adapting to FSH standards: https://github.com/kadalu/kadalu/issues/836
However, the related Pull request only changed the [path mounted into the container](https://github.com/kadalu/kadalu/blob/devel/templates/server.yaml.j2#L94). Not the [path that is mounted from the Host](https://github.com/kadalu/kadalu/blob/devel/templates/server.yaml.j2#L115).

**To Reproduce**
See above links to `templates/server.yaml.j2`

**Expected behavior**
server-storage container should mount `/lib/modules`.

**Actual behavior**
It attemps to mount `/usr/lib/modules`

**Environment:**
```
> kubectl exec -it deploy/operator -n kadalu -- bash -c 'kubectl-kadalu version'
kubectl-kadalu plugin: 0.8.16
kadalu pod(s) versions
pod/kadalu-csi-nodeplugin-6mwx4: 0.8.16
pod/kadalu-csi-nodeplugin-d7mp9: 0.8.16
pod/kadalu-csi-nodeplugin-vtftz: 0.8.16
pod/kadalu-csi-provisioner-0: 0.8.16
pod/operator-687cc468bd-kz8m9: 0.8.16
Error while running the following command
$ kubectl exec -nkadalu pod/server-storage-0-0 -- bash -c echo $KADALU_VERSION

error: unable to upgrade connection: container not found ("server")

command terminated with exit code 1
```
 - K8S_DIST: kubernetes

**Screenshots or Logs**
/

**Additional context**
/

**Comment by amarts** [comment]
@Timoses thanks for pointing out. Looks like a one line fix, as you pointed.

Before one of us submit PR, would you like to send the PR ? We would surely like to have more contributors to project :slightly_smiling_face:
