### ISSUE TITLE
[RFE]: Add status to kadalustorage resource

### ISSUE THREAD

**Issue by joejulian** [kadalu/kadalu#905]
**Is your feature request related to a problem? Please describe.**
When the kadalustorage resource is created, there's a period of time in which the storage is not yet running yet there's no way to know when it's ready.

**Describe the solution you'd like**
I'd like at minimum a "ready" status that shows when the cluster is ready to serve.

Even better would be if it had statistics like pending/failed heals, split-brain files, etc.

**Describe alternatives you've considered**
I considered watching the readiness of the statefulset, but the pods are all marked ready before the volume is ready to be accessed.

**Additional context**

**Comment by amarts** [comment]
what is the best method here? You prefer to have a `kadalu` command  or some options with k8s commands ?

**Comment by joejulian** [comment]
I'm referring to `status` as defined in the [Working with Kubernetes Objects](https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/) guide.
