### ISSUE TITLE
[Bug]: csi-nodeplugin consumes all free space on a disk

### ISSUE THREAD

**Issue by goolzerg** [kadalu/kadalu#914]
**Describe the bug**
Kadalu csi-nodeplugin (kadalu-logging container) writes it's logs to emtyDir volume by default. Eventually nodeplugin's logs consume all free space on a disk. Is it possible  to send logs to stdout as Kubernetes native applications do?

**To Reproduce**
1. Deploy csi-nodeplugin to k8s cluster
2. Wait until disk space will end

**Comment by aravindavk** [comment]
Logs are sent to stdout but the enhancement is required to purge the old log files. (https://github.com/kadalu/kadalu/blob/devel/helm/kadalu/charts/csi-nodeplugin/templates/daemonset.yaml#L84).

**Comment by vatsa287** [comment]
@aravindavk @amarts 
Soln:
Add logrotate configuration ex:
```
/var/log/glusterfs/*.log {
  sharedscripts
  maxsize 10M
  minsize 100k
  rotate 3
  missingok
  compress
  delaycompress
  notifempty
  postrotate
  /usr/bin/killall -HUP glusterfs > /dev/null 2>&1 || true
  endscript
}
```
Change existing tail to `-F` to track the log file even if it is renamed or recreated.
Add a shell script as a process as a alternative to cron job in container to call logrotate configuration file twice a day.

**Comment by amarts** [comment]
Go ahead and send a PR. This may be needed in other containers too.
