### ISSUE TITLE
Deploy Kadalu on control plane nodes: 

### ISSUE THREAD

**Issue by prabhupraveen** [kadalu/kadalu#915]
**Is your feature request related to a problem? Please describe.**
In order to deploy Kadalu on control plane nodes, the taint <code>node-role.kubernetes.io/control-plane:NoSchedule</code> has to be removed. This may not be desirable because the control plane nodes then become available for all deployments. 

Worker nodes usually are disposable, while control plane nodes run critical workloads. Having a stable kadalu glusterfs PV using the control plane nodes will make the storage provisioning a critical workload which may be desirable. For example, one may want to run a container registry on the control plane nodes which will require persistent volumes mounted., however due to the taint, the required kadalu pods dont run on the control planes, and hence any attempt to mount a kadalu pvc on a pod running on the control plan gets error like  <code>MountVolume.MountDevice failed for volume "pvc-c25047dd-bf9f-4bb0-a1b2-489fe3fe8479" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name kadalu not found in the list of registered CSI drivers</code>

**Describe the solution you'd like**
I was unable to find documentation on how to deploy Kadalu on control plane nodes. If it is possible to do without removing taint, then it would be great to have the documentation updated. If it is not possible to run without removing taint, then a better solution would be to allow configuration of tolerations on the kadalu pods in-order to make them run on the control plane nodes.

**Describe alternatives you've considered**
At the moment the alternative is to run kadalu on worker nodes.

**Comment by leelavg** [comment]
@aravindavk could you pls refresh the docs, seems #878 wasn't populated

**Comment by leelavg** [comment]
- just observed that the attached PR will not work as expected and also wrong, this is one area where having a separate configmap will be helpful
- use case is, users may want glusterfs-server, provisioner & nodeplugin should be running on a specific tainted node
