### ISSUE TITLE
[Bug]: Quota is not getting reclaimed once I delete the files

### ISSUE THREAD

**Issue by mohammaddawoodshaik** [kadalu/kadalu#916]
**Describe the bug**
I have created a `Replica1` storage-pool and a PVC asking for 2G of space. I wrote the data to that PVC mount point and deleted th e same, but I see disk space is not completely freed.

**To Reproduce**
1. Create a replica1 storage-pool by specifying hostpath, which is XFS.
2. Create a PVC asking for 2G in the above-created storage-pool
3. Now create a POD by attaching the PVC
4. Exec into the pod and go to the PVC mountpoint and run the comamnd `df -h .`. Here you will see 2.1G available
5. Now create a 1G file - `dd if=/dev/zero of=testfile bs=1M count=1024`. After this again you run `df -h`, now you will see used `1.6G`
6. Now delete the file, and run `df -h` this time you see used `560M`, need help in why this extra is coming while creation of file and not freeing up after file deletion.

**Expected behavior**
There should not be any extra disk space should be utilized and even tough it is getting used, it should get freedup upon file deletion.

**Actual behavior**
There is 500M is disk space is blocked. 

**Environment:**
K8 version - 1.24
Kadalu - 0.8.17
Brick path - XFS file system
Single node setup - Replica1

                         root@pod1:/mnt/pv# df -h .
			Filesystem           Size  Used Avail Use% Mounted on
			kadalu:storage-pool  2.1G     0  2.1G   0% /mnt/pv
			root@pod1:/mnt/pv# dd if=/dev/zero of=testfile bs=1M count=1024
			1024+0 records in
			1024+0 records out
			1073741824 bytes (1.1 GB, 1.0 GiB) copied, 1.6885 s, 636 MB/s
			root@pod1:/mnt/pv# df -h .
			Filesystem           Size  Used Avail Use% Mounted on
			kadalu:storage-pool  2.1G  1.6G  465M  78% /mnt/pv
			root@pod1:/mnt/pv# ls -lah
			total 1.1G
			drwxrwxrwx 2 root root 4.0K Nov  2 07:39 .
			drwxr-xr-x 1 root root 4.0K Nov  2 07:37 ..
			-rw-r--r-- 1 root root 1.0G Nov  2 07:39 testfile
			--------
			root@<host_node>:/data/gluster/data/brick/subvol/db/e8/pvc-33dab226-8a62-47ef-8f42-d4bd9abf2a1a# df -h .
			Filesystem      Size  Used Avail Use% Mounted on
			/dev/sdb6       278G   65G  199G  25% /data
			--------
			root@pod1:/mnt/pv# rm testfile
			root@pod1:/mnt/pv# df -h .
			Filesystem           Size  Used Avail Use% Mounted on
			kadalu:storage-pool  2.1G  560M  1.5G  28% /mnt/pv
			root@pod1:/mnt/pv# ls -lah
			total 8.0K
			drwxrwxrwx 2 root root 4.0K Nov  2 07:40 .
			drwxr-xr-x 1 root root 4.0K Nov  2 07:37 ..
			--------
			root@root@<host_node>:/data/gluster/data/brick/subvol/db/e8/pvc-33dab226-8a62-47ef-8f42-d4bd9abf2a1a# df -h .
			Filesystem      Size  Used Avail Use% Mounted on
			/dev/sdb6       278G   64G  200G  25% /data
			---------
			root@pod1:/mnt/pv# dd if=/dev/zero of=testfile2 bs=1M count=1024
			dd: error writing 'testfile2': Disk quota exceeded
			dd: closing output file 'testfile2': Disk quota exceeded
			root@pod1:/mnt/pv# ls -lah
			total 881M
			drwxrwxrwx 2 root root 4.0K Nov  2 09:02 .
			drwxr-xr-x 1 root root 4.0K Nov  2 07:37 ..
			-rw-r--r-- 1 root root 881M Nov  2 09:02 testfile2

**Comment by leelavg** [comment]
- Ah! I debugged this with the user recently and #908 was raised
- Fix will be part of next release #911
