### ISSUE TITLE
[RFE]: Rewrite (/arch) Kadalu Operator to reconcile on required events

### ISSUE THREAD

**Issue by leelavg** [kadalu/kadalu#921]
- In-order not to get exhaustive I'll provide requirement and at-most one example for that specific requirement as a start

**Is your feature request related to a problem? Please describe.**
### 1. Finalizers:
- Operator should have the ability to add finalizers to Kadalu CRs and be able to act on it during deletion of Storage Pools
- When user deletes CR, our operator blocks pool deletion if there's any bound PV, however we need to extend this and reconcile deletion when user actually deletes the underlying PVCs after initial deletion of Storage Pool CR

### 2. Custom Resource:
- At the moment we are slightly good with how we are updating CRD, however having a way in defining CRD from Code and auto generating custom resources with rbac reduces cognitive effort
- Rather than pushing everything to CRD we should be able to tune the operator via ConfigMap and also have the ability to remove any fields with depreciation notice
- Not to re-hash things, implementing #905 is a must and we need to update the status in specific intervals/events

### 3. Storage Disruption:
- As part of node upgrade or any other reason if one of the storage servers is down we should be able to gate the upgrade of other nodes where server is running until we reach a healthy state & no heals are pending

### 4. Reconciliation:
- At the moment we are watching API server for any changes to Kadalu Storage CR alone, first, this increases load on API Server (unless the k8s python client is optimising this internally via generators etc), second, any modifications to kadalu-info configmap & kadalu CSI components is also an event of interest for us to act on Kadalu overall status
- Having `kubectl-kadalu` is a plus and at the same time providing a separate client (toolbox) on demand to debug storage in long run is a must (similar to #843)

### 5. Misc:
- Decouple the Storage Pool reconciliation from state of other CRs, IOW #903, we should move the per namespace secret (ssh) to per storage class secrets, ref [doc](https://kubernetes-csi.github.io/docs/secrets-and-credentials-storage-class.html)
- Let's merge the Provisioner & Nodeplugin deployments back to one and inbuilt the upgrade logic into operator itself for better handling disruptions (/upgrades)

**Describe the solution you'd like**
1. Now that we are almost done with changes to storage layer, let's enhance our operator to make use of k8s guarantees
2. I'd like to split operator functionality into two (logically), corresponding to storage ops & k8s ops as at one point I want to enhance Nomad support
3. Either rewrite the operator in golang or use python [equivalent](https://github.com/nolar/kopf)

**Describe alternatives you've considered**
1. Had a re-look at operator flow and implement at-least some of above seemed like a hack than a feature and so proposing these changes

**Additional context**
1. We better have a design doc before implementing changes 🤔

**Comment by aravindavk** [comment]
> Rather than pushing everything to CRD we should be able to tune the operator via ConfigMap and also have the ability to remove any fields with depreciation notice

This is nice. We can move Option set and other day2 Operations to Config map instead of CRD. But because of this Operator has to watch Configmap also. If everything related to the Storage pool is in CRD, then watching only CRD changes should suffice.

> At the moment we are watching API server for any changes to Kadalu Storage CR alone, first, this increases load on API Server (unless the k8s python client is optimising this internally via generators etc), second, any modifications to kadalu-info configmap & kadalu CSI components is also an event of interest for us to act on Kadalu overall status

Modifications to kadalu-info configmap is done by the Operator. Users should update CRD if any changes required, they should not update kadalu-info configmap directly. What is the use case to allow updating this config-map directly instead of updating CRD. What all events from CSI are required for Operator? Storage getting full or similar events?

Good list of features. We are not against Golang, initially our focus was to integrate Gluster with K8s without Glusterd. Do you want to evaluate the effort required to rewrite the Operator and CSI in Golang?

After 1.0 release, we can spend time on Moana integration and rewriting the Operator and CSI in Golang.

@amarts ^^

**Comment by aravindavk** [comment]
If Golang rewrite is feasible, it can be 1.x and Moana integration can be 2.0 target.

**Comment by leelavg** [comment]
> Users should update CRD if any changes required
- yes and at the same time current flow is more like tying storage & k8s operator, if we can have separate config map for operator then there's no need to update kadalu-info

> Do you want to evaluate the effort required to rewrite the Operator and CSI in Golang?
- I'm thinking for initial rewrite of only operator, as CSI is mostly stateless that can come up later
- With the available tools for golang we can re-write operator in-around (continuous) 24 hrs and 2-3 hrs more if we want some design changes in current CRD
- Around same time is required for CSI & server components plus some extra for testing infra
- As a ballpark figure I'm thinking close to 90-100 continuous hrs for project re-write

- Having said that, picking golang is due to only existing ecosystem around it and no other reason
- Might be, we can run a poll or something what does users require for 1.0

Edit:

- Assumptions are from experience working these projects [1](https://github.com/red-hat-storage/lvm-operator/commits?author=leelavg), [2](https://github.com/topolvm/topolvm/commits?author=leelavg) and [3](https://github.com/red-hat-storage/ocs-osd-deployer/commits?author=leelavg), just wanted to backup why I said what I said 😅
- It seems I overlooked the ARM support, might need to look into that and I believe there will be not hard blockers there as well

**Comment by amarts** [comment]
> If Golang rewrite is feasible, it can be 1.x and Moana integration can be 2.0 target.

@aravindavk lets not bother about golang and a release right now. We will keep the efforts by having a separate branch, an issue (mainly to document progress, benefits... - can be this one) and then then take a call on release version.

My take, with what we already have, we are good for 1.0.x releases for sure. Lets plan that this month before branching for golang efforts.
