### ISSUE TITLE
Used / remaining storage stage

### ISSUE THREAD

**Issue by Fevereiro6** [kadalu/kadalu#928]
I have a storage pool of  of Replica1 type distributed over 3 nodes of a k8s cluster.  How can I check the used/reamining storage on each of the nodes of the pool. Kadalu version used 0.8.14.

**Comment by leelavg** [comment]
```
curl -fsSL https://github.com/kadalu/kadalu/releases/latest/download/install.sh | sudo bash -x
kubectl kadalu storage-list -h
```
- https://github.com/kadalu/kadalu/tree/devel/cli#usage
- plugin available from krew repo as well
