### ISSUE TITLE
[RFE]: Non Uniform File Allocations

### ISSUE THREAD

**Issue by Ruakij** [kadalu/kadalu#938]
I am not sure if its possible to implement NUFA:
https://docs.gluster.org/en/latest/Administrator-Guide/Managing-Volumes/#non-uniform-file-allocation

I'd like to be able to store files created on nodeX only on nodeX to limit network-activity, but still be able to access the file from a different node. (Distributed Mode)

This would enable saving bandwidth in scenarios where a pod writes files and a different pod reads files, but only sporadically. 
(assuming both pods are on different nodes)

I think this could be related to: https://github.com/kadalu/kadalu/issues/858

**Comment by aravindavk** [comment]
I think this should be possible. But before confirming, I need to understand the below point from the docs page.

> "A client that is mounting a NUFA-enabled volume must be present within the trusted storage pool."

@amarts do you know how DHT will know the client's node and compare with server node to come up with the hashed node? Is it based on `glusterd-uuid` or based on a mount option?

**Comment by amarts** [comment]
> @amarts do you know how DHT will know the client's node and compare with server node to come up with the hashed node? Is it based on `glusterd-uuid` or based on a mount option?

Nufa xlator works with a simple option, which says one of the subvol as the 'local' node. We couldnt get this working smoothly with glusterd's volgen as this option was not so easy to configure. With template based volfile approach, and as we get to set the option, nufa surely can be revived. 

Logic is simple on client side. Treat one of the subvols of dht as local, and create all files there, untill we get ENOSPC (which is already handled).

All complexity is in how will client volfile decide which of the subvol is local.
