### ISSUE TITLE
[Bug]: server-xxx-0-0 pod on master node is not running after reboot master node

### ISSUE THREAD

**Issue by newbiediver** [kadalu/kadalu#939]
**Describe the bug**
I have 3 nodes in my cluster include master node. And attached 3 disk each node. So I added toleration "node-role.kubernetes.io/control-plane" in KadaluStorage yaml. All statefulset and csi-nodeplugin deployed. Then there are all ok!
But I need to reboot my cluster another issues. So I reboot all nodes in my cluster.
But one pod of server-xxx-0-0 is pending. It describe shows toleration need "node-role.kubernetes.io/control-plane"

**To Reproduce**
1. Make KadaluStorage and add master node toleration.
2. Reboot cluster.
3. Pending one pod "server-xxxx-0-0" on master node.

**Expected behavior**
All statefulset pod have to be running normally.

**Actual behavior**
One pod on master node doesn't running after reboot cluster.

**Environment:**

 - Kadalu Version: 1.0.0
 - K8S_DIST: kubernetes

**Screenshots or Logs**
Oh..Sorry. I didn't capture it.

**Additional context**
Nothing.

**Comment by newbiediver** [comment]
??? No comment. I wonder how it's going.

**Comment by vatsa287** [comment]
@newbiediver could you please post logs of csi-provisioner, nodeplugin & server pods.

`kubectl logs -nkadalu server-xxxx-0-0`
