### ISSUE TITLE
[RFE]: support kubelet_volume* metrics

### ISSUE THREAD

**Issue by gerethd** [kadalu/kadalu#956]
**Is your feature request related to a problem? Please describe.**

It would be nice if i could monitor PVC usage through the kube-state-metrics provider. If kadalu had options for metrics scraping by prmetheus, it would be nice if there was documentation on this

**Describe the solution you'd like**

Use the same standardized metrics query to view all PVCs in the cluster, falling back to kadalu specific metrics as needed.

**Describe alternatives you've considered**

Scraping kadalu operator directly -- Needs Documentation

Side cars on pods using these containers to export these metrics -- a lot of overhead to add to each and every container

**Additional context**
Would make managing and maintaining PVCs a lot easier

**Comment by leelavg** [comment]
- kadalu already exports a set of volume related metrics https://github.com/kadalu/kadalu/blob/8007188120c0b30d3c83617940c4c1c9fedbc80a/kadalu_operator/metrics.py#L3-L23
- they are exposed on kadalu operator https://github.com/kadalu/kadalu/blob/8007188120c0b30d3c83617940c4c1c9fedbc80a/helm/kadalu/charts/operator/templates/deployment.yaml#L19-L20
- - will track in #967, re-open if required
