### ISSUE TITLE
[Bug]: Signing up for slack seems broken

### ISSUE THREAD

**Issue by jdblack** [kadalu/kadalu#960]
**Describe the bug**
I'm trying to make an account on the kadalu slack with my google account, but the google integration seems broken

**To Reproduce**
1. Go to https://kadalu.slack.com/
2. Click on "Create account"
3. Click on "Continue with google"
4. PIck your google account
5.  view error message "The email address must match one of the domains listed below. Please try another email."

There is an additional message that says: 
Don’t have an @yellowchalk.com email address?
Contact the workspace administrator at kadalu for an invitation.

I suspect that the  matching domain that is being referred to is named "yellochalk

**Expected behavior**
I would expect to be able to join Slack on Kadalu with my email address

**Comment by aravindavk** [comment]
Try this direct link to join to Kadalu Slack channel https://join.slack.com/t/kadalu/shared_invite/enQtNzg1ODQ0MDA5NTM2LWMzMTc5ZTJmMjk4MzI0YWVhOGFlZTJjZjY5MDNkZWI0Y2VjMDBlNzVkZmI1NWViN2U3MDNlNDJhNjE5OTBlOGU

**Comment by leelavg** [comment]
same as #985. re-open if required.
