### ISSUE TITLE
[Bug]: Link in about section of github gives a 404

### ISSUE THREAD

**Issue by dafzor** [kadalu/kadalu#964]
**Describe the bug**
The documentation page linked in the about section of this github repo no longer exists.

https://kadalu.github.io/docs/k8s-storage/devel

The link should be updated to the current one.

**Comment by vatsa287** [comment]
@dafzor Thanks for reporting this issue. Will fix up.
Please use this link [https://docs.kadalu.tech/k8s-storage/devel/](https://docs.kadalu.tech/k8s-storage/latest/).

**Comment by aravindavk** [comment]
Updated now.
