### ISSUE TITLE
[Bug]: Slack space is closed/private

### ISSUE THREAD

**Issue by wdec** [kadalu/kadalu#985]
**Describe the bug**
The slack space kadalu.slack.com is restricted to the yellowchalk.com domain. 
Is there any other way to get in touch?

**Comment by leelavg** [comment]
@wdec Slack is available at that address, could you please share any supporting screenshot?

**Comment by wdec** [comment]
When attempting to sign in using my slack account:

<img width="931" alt="image" src="https://user-images.githubusercontent.com/888344/231984754-ddfa8838-f545-4b44-af0e-e7dd7aaccdae.png">


There's no longer the option to add my account to kadalu.slack.com. Previously it was there but was limited to the yellowchalk.com domain.

**Comment by amarts** [comment]
Looks like there is no easy way to show invite in the kadalu slack home page. Please use invite from the kadalu.tech website. Just checked that using invite, one can login.

**Comment by wdec** [comment]
> Looks like there is no easy way to show invite in the kadalu slack home page. Please use invite from the kadalu.tech website. Just checked that using invite, one can login.

That worked. Thanks
